In [1]:
library(hise)
library(dplyr)
library(ggplot2)
library(stringr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
desc <- getFileDescriptors(fileType='scRNA-seq-labeled')

In [3]:
desc <- fileDescToDataframe(desc, keep_specimens = TRUE)

In [4]:
headdesc

$descriptors
                  lastUpdated                            sample.id
1    2024-10-09T05:01:10.275Z 451e9cf5-985a-4268-91d1-4f25c7c3bc4b
2    2024-10-09T05:01:10.275Z 7589318f-5097-4a42-b32d-0083fed4b465
3    2024-10-09T05:01:10.275Z 5884c8e8-4aed-4179-b771-7be7ca01ddd3
4    2024-10-09T05:01:10.275Z 5c140d31-db89-4480-af28-a82704221c72
5    2024-10-09T05:01:10.275Z 0efe95fa-ffb0-4337-944f-8006ad3e3e19
6    2024-10-09T05:01:10.275Z f954415c-c278-4df5-b617-9e98d8d4319e
7    2024-10-09T05:01:10.275Z db4f13c2-c736-4444-b536-b21b45be5108
8    2024-10-09T05:01:10.275Z 1708a8dd-32f6-4315-9c31-e401eafc8451
9    2024-10-09T05:01:10.275Z bcedc25b-ba30-4118-8874-ea15c2b48179
10   2024-10-09T05:01:10.275Z 5348768d-dc13-4f87-8aa5-1187215a53fd
11   2024-10-09T05:01:10.275Z 0aa782e4-c8af-41bc-952c-9cecd2775f06
12   2024-10-09T05:01:10.275Z 5de2db28-ef6a-41dc-a1e5-0a938db2e720
13   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
14   2024-10-09T05:01:10.275Z d5e73974-286a-4403-a9f2-bba5da491267
15   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
16   2024-10-09T05:01:10.275Z 68b29144-4d06-4c27-b911-1974fbf19080
17   2024-10-09T05:01:10.275Z b98ef544-50eb-47c9-993f-8a3b3868b96e
18   2024-10-09T05:01:10.275Z 6261226a-0493-4f04-8059-d3968af02774
19   2024-10-09T05:01:10.275Z 06af71db-28cb-4180-9b67-756dcf547cff
20   2024-10-09T05:01:10.275Z 024da332-08cf-4886-849f-0e86a859cba4
21   2024-10-09T05:01:10.275Z 773699ec-9585-4794-b8b0-51e3ffecbf0f
22   2024-10-09T05:01:10.275Z 45dd11fb-002f-478a-9f88-cc0544cfd84f
23   2024-10-09T05:01:10.275Z 15b1093d-12b2-4b3c-84ac-b20c37b4c6c1
24   2024-10-09T05:01:10.275Z aac91ea2-407d-4673-be21-0246b106c6d3
25   2024-10-09T05:01:10.275Z 5450cef8-8f3e-4552-a6d8-987d4e6e0b08
26   2024-10-09T05:01:10.275Z 18ebf735-03cb-4f4a-88bd-93862c3ab5a7
27   2024-10-09T05:01:10.275Z b7cbab75-5ebc-4ddd-ac85-c60fbf64d6c7
28   2024-10-09T05:01:10.275Z 9ae566db-f7e3-49b5-b7c1-e2ee68b3c5fe
29   2024-10-09T05:01:10.275Z 258c817d-fb20-47e9-b54b-4b2f54979e86
30   2024-10-09T05:01:10.275Z 098bcd30-9f7e-4c63-931b-06570412a24a
31   2024-10-09T05:01:10.275Z 87af0508-cf62-4a76-a48a-89ee2225d3a5
32   2024-10-09T05:01:10.275Z 60795b66-245f-46e2-a003-865a25d6bbca
33   2024-10-09T05:01:10.275Z b2b63fc6-74c0-4755-a923-1d5c03a8e849
34   2024-10-09T05:01:10.275Z d416e0f0-a550-49a6-aafa-102e585bfb9a
35   2024-10-09T05:01:10.275Z 07929fb6-e2b5-4247-8910-61689b81b022
36   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
37   2024-10-09T05:01:10.275Z f1ec0265-26d2-4dbe-8f9a-434d4ee46adf
38   2024-10-09T05:01:10.275Z fa82315e-049d-46a1-bca1-63e5ade7e3a3
39   2024-10-09T05:01:10.275Z df4a778c-dd8c-4018-b004-fbca1dfb8cde
40   2024-10-09T05:01:10.275Z 00fdc2db-2ec2-4019-8c47-6ba774e2dc74
41   2024-10-09T05:01:10.275Z 470990d0-1e92-4196-b633-bd075701ebb8
42   2024-10-09T05:01:10.275Z d416e0f0-a550-49a6-aafa-102e585bfb9a
43   2024-10-09T05:01:10.275Z ef27a753-7ced-4e35-a8d0-3a64e9883a74
44   2024-10-09T05:01:10.275Z 0ac68c00-e8e7-458f-b358-b70e236757b8
45   2024-10-09T05:01:10.275Z 95dd5591-95b8-421f-9e8a-ea9a7320f977
46   2024-10-09T05:01:10.275Z 9326979b-1467-4d1d-89e6-01246d77a960
47   2024-10-09T05:01:10.275Z f59f067e-851a-49b7-ae24-6e95a5b8d387
48   2024-10-09T05:01:10.275Z a35a5c27-8d7d-4f75-8e5c-0ce00c7f8a6e
49   2024-10-09T05:01:10.275Z 7ce0acd0-7712-4264-9241-0ff7772404d6
50   2024-10-09T05:01:10.275Z 21fd49b4-9dc4-4204-adad-56f771681694
51   2024-10-09T05:01:10.275Z 6d97c82f-8baf-4b75-9974-677581813b1d
52   2024-10-09T05:01:10.275Z 93de4ac7-7700-4971-88c0-8e9112159f5e
53   2024-10-09T05:01:10.275Z f83e15b8-76fe-4691-99f9-0f89cc2d77a9
54   2024-10-09T05:01:10.275Z c3e54c16-7146-419c-8a3c-71c3479b0aea
55   2024-10-09T05:01:10.275Z 5ac5e40f-79dd-4a87-b7c1-a3cbd1f1661d
56   2024-10-09T05:01:10.275Z 3210dcfc-7ca5-4460-927e-6e39a30197dc
57   2024-10-09T05:01:10.275Z d6aa7710-e5c7-4401-ac9d-d323fbc45e9d
58   2024-10-09T05:01:10.275Z 8f93d8e2-d786-4565-bb5e-47ac95d38f57
59   2024-10-09T05:01:10.275Z 0e719429-42cf-4684-95e1-780d3e4d02ea
60   2024-10-09T05:01:10.275Z 1319ac2a-1d65-4d7d-a701-c97d2638f76d
61   2024-10-09T05:01:10.275Z 6bd4ab6a-2242-4920-a7a8-66659398ff10
62   2024-10-09T05:01:10.275Z 7c12d03c-0c99-4a70-a7b1-5eea8bac9a57
63   2024-10-09T05:01:10.275Z ea69d42b-8097-4d66-bdf9-521ea0daa4b0
64   2024-10-09T05:01:10.275Z b98ef544-50eb-47c9-993f-8a3b3868b96e
65   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
66   2024-10-09T05:01:10.275Z 69339d49-93bf-4d0c-b3c2-eaca579a056c
67   2024-10-09T05:01:10.275Z 1708a8dd-32f6-4315-9c31-e401eafc8451
68   2024-10-09T05:01:10.275Z fc465161-4f96-4f43-99a0-c205b2366591
69   2024-10-09T05:01:10.275Z 83d3f7f5-c121-4f3a-a0e7-fa2b29a06f6f
70   2024-10-09T05:01:10.275Z 2c623015-a99e-4c8c-b610-3aaa2f2c3f23
71   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
72   2024-10-09T05:01:10.275Z fc582f90-4645-49c1-bd90-1efe93fc5fbc
73   2024-10-09T05:01:10.275Z ca96bc80-7693-4667-902d-2ed9b31b410b
74   2024-10-09T05:01:10.275Z a52e28b2-5bf2-4224-9d70-72c9ac84aa42
75   2024-10-09T05:01:10.275Z 10154ef0-695f-4b2d-90b7-9c0eec289125
76   2024-10-09T05:01:10.275Z 53a0435b-7f84-4598-bd0f-5fbe66a87abc
77   2024-10-09T05:01:10.275Z ce4321b6-82f6-4000-a1af-87da28b7e080
78   2024-10-09T05:01:10.275Z 6c60b100-812d-4568-9c08-8a0e0e83a455
79   2024-10-09T05:01:10.275Z fc465161-4f96-4f43-99a0-c205b2366591
80   2024-10-09T05:01:10.275Z 045566d1-3836-45b0-bea2-09867bfffc53
81   2024-10-09T05:01:10.275Z 6d925fad-32ca-447d-998a-4d15b869275f
82   2024-10-09T05:01:10.275Z baff9194-c34c-439f-a51b-5a49e13914cc
83   2024-10-09T05:01:10.275Z fa6ca30c-44c7-467e-9cd1-4b7fb2b8444b
84   2024-10-09T05:01:10.275Z 455fe1fd-9330-4b76-b7ea-99bfeff5d6dd
85   2024-10-09T05:01:10.275Z 8fbae916-bafb-45a2-9127-7c54c24a650d
86   2024-10-09T05:01:10.275Z 09738572-2434-427a-9add-fe2bfcddde3e
87   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
88   2024-10-09T05:01:10.275Z 28e5f9a5-6a44-42ed-bad5-b1f417601860
89   2024-10-09T05:01:10.275Z 2a709058-97bc-4622-846c-6d6398c9175d
90   2024-10-09T05:01:10.275Z c4a1ac51-cc6e-4cd3-898d-6081845fa906
91   2024-10-09T05:01:10.275Z a6d0cd7c-1de0-4ab7-9176-bd53ec159cd0
92   2024-10-09T05:01:10.275Z 2626107f-a07d-45db-b9d2-89f4e30cd3d6
93   2024-10-09T05:01:10.275Z 286bd31d-ec4c-4dd9-981f-097bcd2963a1
94   2024-10-09T05:01:10.275Z d416e0f0-a550-49a6-aafa-102e585bfb9a
95   2024-10-09T05:01:10.275Z 2cc6fc92-867a-4a41-a87a-5a8740dc42db
96   2024-10-09T05:01:10.275Z 1f571ee5-c549-4939-8f45-b6fcb2c6c328
97   2024-10-09T05:01:10.275Z 8053b4da-be6b-4d07-a025-b15d41610355
98   2024-10-09T05:01:10.275Z 91037ea5-000f-485e-8eeb-b2222be07d2b
99   2024-10-09T05:01:10.275Z 588b4989-c02b-40b6-aed2-398de05ba326
100  2024-10-09T05:01:10.275Z 03dcdc5f-1921-4e71-b966-4c16c5a44878
101  2024-10-09T05:01:10.275Z 74a1ee99-ca49-4d43-b894-b3588611406a
102  2024-10-09T05:01:10.275Z 587fc2fc-3e60-4cf8-aef2-7c1a8a567177
103  2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
104  2024-10-09T05:01:10.275Z 24028264-a8ef-445c-ac9b-037d93d9e9dd
105  2024-10-09T05:01:10.275Z 017d064a-8765-4b80-ab47-1812caf1e8eb
106  2024-10-09T05:01:10.275Z c4a1ac51-cc6e-4cd3-898d-6081845fa906
107  2024-10-09T05:01:10.275Z 286bd31d-ec4c-4dd9-981f-097bcd2963a1
108  2024-10-09T05:01:10.275Z b4032e29-d4f9-4e4b-ba99-48177793d01a
109  2024-10-09T05:01:10.275Z 38738d58-c593-4ce7-a620-a4c00a47d912
110  2024-10-09T05:01:10.275Z 88fada56-c54d-493f-815e-cb6f0c61f84c
111  2024-10-09T05:01:10.275Z 1833f478-05de-449c-9a4c-6aff93baf582
112  2024-10-09T05:01:10.275Z 04a47900-e736-4ee3-ac26-b4487cf8179b
113  2024-10-09T05:01:10.275Z 6cd98a5c-18a5-460e-a245-e2d791388927
114  2024-10-09T05:01:10.275Z 452dd3bd-9992-4c86-b1e7-89496f566fc1
115  2024-10-09T05:01:10.275Z 8756660b-fe10-4173-8fcd-712e72dc7f4a
116  2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
117  2024-10-09T05:01:10.275Z 68821537-48c7-4929-8988-b255602bf8a0
118  2024-10-09T05:01:10.275Z 25ec8d13-7fa6-4c15-9aff-2ba705d139c6
119  2024-10-09T05:01:10.275Z d56467f9-10f8-4a11-b219-2215e9b8c211
120  2024-10-09T05:01:10.275Z 66ff531a-0dc0-4c3e-ac35-c551721b9145
121  2024-10-09T05:01:10.275Z 9ce12fe0-a7ba-44aa-bbba-c1b169b366f2
122  2024-10-09T05:01:10.275Z a02dfb74-20da-412e-be62-bd924d5d79b6
123  2024-10-09T05:01:10.275Z 5dfc7459-4731-4475-8a6f-b9d8f38a244d
124  2024-10-09T05:01:10.275Z c46b58d0-9c10-4bae-916b-eb655d42bddb
125  2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
126  2024-10-09T05:01:10.275Z 32fb92d1-11ee-45dc-a650-83516794cdbb
127  2024-10-09T05:01:10.275Z 9559ec4d-5b37-4a46-85bd-8202fc32b1ed
128  2024-10-09T05:01:10.275Z c8680b0c-3b84-4c39-a5b0-dd946457e82b
129  2024-10-09T05:01:10.275Z b1329bae-e55b-4836-8784-04012893a82f
130  2024-10-09T05:01:10.275Z ccfaefc5-7c7b-4175-aede-6086b5fdb263
131  2024-10-09T05:01:10.275Z 4d3f91ad-955a-4ab8-bacc-4485bd54fba7
132  2024-10-09T05:01:10.275Z 53a0435b-7f84-4598-bd0f-5fbe66a87abc
133  2024-10-09T05:01:10.275Z cbf53533-ff70-4158-8ae4-4a50e6d37336
134  2024-10-09T05:01:10.275Z 1011bb65-1c0e-44dd-87a4-77cb21fa6895
135  2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
136  2024-10-09T05:01:10.275Z 51d87d79-9186-4abf-b5fe-712e72c87cfc
137  2024-10-09T05:01:10.275Z 1657921b-206b-498a-9cfd-0d3ec9abab46
138  2024-10-09T05:01:10.275Z 4901f24a-575d-4196-a051-2a660a0cf3f3
139  2024-10-09T05:01:10.275Z 7fa461e7-8ed9-447f-991c-2eb52e4c7461
140  2024-10-09T05:01:10.275Z fa69454b-f968-4117-88b2-85716fdfb38a
141  2024-10-09T05:01:10.275Z 0c451ab1-b521-4e6f-8dd2-1a5105957ae8
142  2024-10-09T05:01:10.275Z ae7db12b-ac83-464e-9874-5d9a091eec83
143  2024-10-09T05:01:10.275Z 67024cd8-0176-4486-a1da-326d0a527b9b
144  2024-10-09T05:01:10.275Z d416e0f0-a550-49a6-aafa-102e585bfb9a
145  2024-10-09T05:01:10.275Z 11e797ff-6046-45cb-80ac-df4a755f35c1
146  2024-10-09T05:01:10.275Z f8568feb-7675-4148-a1dc-a2339a4511e1
147  2024-10-09T05:01:10.275Z c5277c6e-bb55-4696-8a81-e227ae0b1c96
148  2024-10-09T05:01:10.275Z 0a4975ae-25c6-4d01-9ca9-a41ac4ea4a4e
149  2024-10-09T05:01:10.275Z 4ec61ff9-7907-4c62-aaaa-ce6037639365
150  2024-10-09T05:01:10.275Z bb079d60-0638-4cfc-8b70-e8b2439580bf
151  2024-10-09T05:01:10.275Z cdcc4a26-a1f7-4175-b4e2-28b4f30ccbba
152  2024-10-09T05:01:10.275Z 0f8aae24-246a-4f0e-9595-1bd49b9b1dc5
153  2024-10-09T05:01:10.275Z 5d5ee3b1-5b39-4000-85b3-f94e3ff1e7c0
154  2024-10-09T05:01:10.275Z e446c1a6-e479-4b3b-9037-fa3bc8293836
155  2024-10-09T05:01:10.275Z 537a30f4-4da8-4c07-85a4-f2ff49aab3c7
156  2024-10-09T05:01:10.275Z d416e0f0-a550-49a6-aafa-102e585bfb9a
157  2024-10-09T05:01:10.275Z 5053dae3-a053-4f79-832d-d9b918bca186
158  2024-10-09T05:01:10.275Z 3b45b74a-06fb-4300-a60c-01fe710fb9e0
159  2024-10-09T05:01:10.275Z 4234ec2a-b792-4e83-8414-fa1765a8e25b
160  2024-10-09T05:01:10.275Z 12850d27-6e4c-4ec0-8a7c-65e48405a10a
161  2024-10-09T05:01:10.275Z 9461fdb7-d462-4e09-8463-5e1ed12ab0be
162  2024-10-09T05:01:10.275Z 89892e95-44ab-48d9-9ffb-65dfc1c47f17
163  2024-10-09T05:01:10.275Z d80eff20-e500-485f-82eb-3636de361622
164  2024-10-09T05:01:10.275Z c95c58fd-80d9-4155-ac9b-9cf0538627e2
165  2024-10-09T05:01:10.275Z 2621f84b-29d4-45b0-a6da-b7af32b21dab
166  2024-10-09T05:01:10.275Z a35a5c27-8d7d-4f75-8e5c-0ce00c7f8a6e
167  2024-10-09T05:01:10.275Z d6aa7710-e5c7-4401-ac9d-d323fbc45e9d
168  2024-10-09T05:01:10.275Z d416e0f0-a550-49a6-aafa-102e585bfb9a
169  2024-10-09T05:01:10.275Z f8408ac9-b34f-4708-8831-4bcb9955c20e
170  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
171  2024-10-09T05:01:10.275Z f367a700-af7a-4dbb-b026-f18cd8d91af2
172  2024-10-09T05:01:10.275Z 19c9fa88-17a3-41d6-94d0-07798ffab7fa
173  2024-10-09T05:01:10.275Z 78bd767f-474b-4f4a-a4d6-7bfbbd24007e
174  2024-10-09T05:01:10.275Z f00246e6-7f3b-4eff-944e-5f8364bfefd1
175  2024-10-09T05:01:10.275Z 1edde673-3571-4c5a-8536-33aa5531307b
176  2024-10-09T05:01:10.275Z d0d3603a-28d4-4003-b21e-e06bb68b5ec9
177  2024-10-09T05:01:10.275Z d7436a84-4d9c-4da4-a951-4d010e31f81d
178  2024-10-09T05:01:10.275Z d31ce06b-6e83-490d-84f2-ecfffe743e80
179  2024-10-09T05:01:10.275Z c9cf1096-3fa3-45c9-a7f0-bad95990ffd7
180  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
181  2024-10-09T05:01:10.275Z e29a0d8c-81c7-4854-a34e-4b08487a9aab
182  2024-10-09T05:01:10.275Z dccb4fc1-6400-498e-97ae-b55dcee64f6b
183  2024-10-09T05:01:10.275Z 9786fc91-eb82-4105-9281-457c73206110
184  2024-10-09T05:01:10.275Z 6357d6ae-7c48-4d72-a1f8-02ab6a8eb0f8
185  2024-10-09T05:01:10.275Z fb31d27b-71f8-418d-94e8-efe138b5ec24
186  2024-10-09T05:01:10.275Z 1c63b656-9554-4917-8228-1b2118457bfd
187  2024-10-09T05:01:10.275Z 8f52ea6b-9a70-4374-a0f7-9e97a6cfa305
188  2024-10-09T05:01:10.275Z bf060477-80ff-4094-8a5f-681c494351b3
189  2024-10-09T05:01:10.275Z 32d97371-b5e9-473f-93c4-f374b2668000
190  2024-10-09T05:01:10.275Z ac5be10e-f71f-4615-b1c2-360d65aac648
191  2024-10-09T05:01:10.275Z 4edb39de-4ab5-4970-9e2b-b25941647950
192  2024-10-09T05:01:10.275Z d64637bf-1d3b-4906-8586-99474f5a1eb9
193  2024-10-09T05:01:10.275Z 85ba197c-32a9-468a-b0a9-49d48db12923
194  2024-10-09T05:01:10.275Z 1c07aa08-bb49-4f92-a10c-1f86b1e4d3ad
195  2024-10-09T05:01:10.275Z e4b2cc2f-1a4e-47c7-91ff-9ddc7ba13e97
196  2024-10-09T05:01:10.275Z 2c85e732-bcdb-426b-ba81-65ee837430e6
197  2024-10-09T05:01:10.275Z 5eb98c59-22af-412c-9492-f51327f393ce
198  2024-10-09T05:01:10.275Z ee443b9a-2c86-4049-b1c8-e631d2351287
199  2024-10-09T05:01:10.275Z 7319d4ae-0904-4c72-8a09-f061e372a6d0
200  2024-10-09T05:01:10.275Z dc6588a9-ef3c-45be-8308-0f96fe5b4686
201  2024-10-09T05:01:10.275Z 38aea1c7-5ce1-4bce-8c63-6c0c054d42d6
202  2024-10-09T05:01:10.275Z ea00fbaf-2fbd-49c7-9c9d-ebd952c8822c
203  2024-10-09T05:01:10.275Z ccc54c97-0f1b-449f-8f5a-00407bef6677
204  2024-10-09T05:01:10.275Z cafcdab3-b629-4c3d-9080-6f5c3483411f
205  2024-10-09T05:01:10.275Z 1d76b861-3289-4f4d-acf5-e4b87cbff510
206  2024-10-09T05:01:10.275Z a5727fe4-73e8-4b27-b1e1-2faadd0004ea
207  2024-10-09T05:01:10.275Z d34bcb37-bdfd-47c2-8752-3b736d6ca8d7
208  2024-10-09T05:01:10.275Z 2bd26d24-a021-4cd2-82b1-3e8cffa5f7df
209  2024-10-09T05:01:10.275Z 621064ff-b30c-4906-8eac-58d63b64cf48
210  2024-10-09T05:01:10.275Z b33f643c-0e08-43dd-b1c6-f65e5288921e
211  2024-10-09T05:01:10.275Z c5595661-47f2-48d4-8869-bb42cdf4e999
212  2024-10-09T05:01:10.275Z d4f735d1-13d0-4d7e-9de0-f19a73a5624d
213  2024-10-09T05:01:10.275Z 24edd4c0-14bf-47ee-ab37-2f19df9221bd
214  2024-10-09T05:01:10.275Z c01f36ae-5176-48ac-9315-c2c3fa7713c0
215  2024-10-09T05:01:10.275Z 82d4c9b2-6db3-42bb-b8dd-6b05e3cf894a
216  2024-10-09T05:01:10.275Z 49a9f13a-cba0-4243-94e0-99d198c85a1b
217  2024-10-09T05:01:10.275Z f0a8853c-64e9-4dbf-9888-63976a9af906
218  2024-10-09T05:01:10.275Z 118aa7f1-3e98-4c4b-a06b-507ef087a9ae
219  2024-10-09T05:01:10.275Z a626952b-68cd-44d0-8cd6-b5663f4c6096
220  2024-10-09T05:01:10.275Z d1ff46b9-fcd1-4c20-837f-e5debb5d90f1
221  2024-10-09T05:01:10.275Z ecd2921c-772a-43c4-94d2-ea665a70a837
222  2024-10-09T05:01:10.275Z d9157ab7-3e3e-42d0-9fe8-70db0a7584f1
223  2024-10-09T05:01:10.275Z 775feb08-ec99-4fe1-a055-e550081c6091
224  2024-10-09T05:01:10.275Z 0803fd9e-ce8e-4c1f-9c09-8151c84ba7e5
225  2024-10-09T05:01:10.275Z 40f8828b-aea2-405f-822d-f657edc102ca
226  2024-10-09T05:01:10.275Z 61cc2993-9870-432c-83e3-5ae89324364a
227  2024-10-09T05:01:10.275Z 84351cd4-635c-425a-bc1b-2842bbfaa71a
228  2024-10-09T05:01:10.275Z cf201358-8a59-4e46-a9b7-dc6c1c2794fe
229  2024-10-09T05:01:10.275Z 5427a932-36fe-4b62-b020-6497c82579e8
230  2024-10-09T05:01:10.275Z 0aee8b1b-9ebb-42f1-8982-50f619f401f6
231  2024-10-09T05:01:10.275Z a504877f-045d-443d-9368-63b0df35565d
232  2024-10-09T05:01:10.275Z 8bfa97f6-03a4-4a44-9ddd-d6a2f83c5d59
233  2024-10-09T05:01:10.275Z 834b3a1a-b4c5-47b5-8a0c-a1ba1e449a5f
234  2024-10-09T05:01:10.275Z 5920383e-ae4b-47f0-8b9f-bb8d50a755c3
235  2024-10-09T05:01:10.275Z e563368b-0abf-4aee-8acc-32ced320bfe9
236  2024-10-09T05:01:10.275Z 814776eb-36a2-4487-ae9b-9675562e915c
237  2024-10-09T05:01:10.275Z a31b3e4b-d301-4a57-8eb2-e5cc086a1689
238  2024-10-09T05:01:10.275Z 10a55413-ec3f-4d03-98fa-0339e90e6d2f
239  2024-10-09T05:01:10.275Z 36896ccf-0b2b-48cd-8f94-6802904f839f
240  2024-10-09T05:01:10.275Z aeff80dc-4321-4702-a718-777971e7239e
241  2024-10-09T05:01:10.275Z aff2073f-ac18-4e64-824c-91fd0b44f849
242  2024-10-09T05:01:10.275Z a52fd056-4fba-4231-be6e-ef6b4b3aea3b
243  2024-10-09T05:01:10.275Z 1fd26278-f482-4eca-9185-0990a510cf9c
244  2024-10-09T05:01:10.275Z 4af92209-19a1-465d-b7b6-74f77563fc59
245  2024-10-09T05:01:10.275Z 7236639e-ed4e-49de-9982-ee5002a73f07
246  2024-10-09T05:01:10.275Z fe28cc44-9bc1-44f2-9ce6-dcc4364708fb
247  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
248  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
249  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
250  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
251  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
252  2024-10-09T05:01:10.275Z 5b76824d-59c5-4f5c-b150-82b70555cd34
253  2024-10-09T05:01:10.275Z 30346065-6cb3-49a0-9b5b-830ac29c0d0f
254  2024-10-09T05:01:10.275Z 49d2454b-de2b-4343-bd84-e12555431be1
255  2024-10-09T05:01:10.275Z cbca528d-ba38-4fee-9d3b-1864b77447b9
256  2024-10-09T05:01:10.275Z 188df108-9224-4988-958f-64b7949f4da2
257  2024-10-09T05:01:10.275Z fab65981-e478-43e7-992a-f7a02c9dae3b
258  2024-10-09T05:01:10.275Z a551408b-c546-4cde-8ca4-14d585bf17b8
259  2024-10-09T05:01:10.275Z 33d9d3ef-6f37-4cb3-b308-10e81585708c
260  2024-10-09T05:01:10.275Z 7319d4ae-0904-4c72-8a09-f061e372a6d0
261  2024-10-09T05:01:10.275Z b10a247a-e67f-4c90-8d6a-1b8b111a9891
262  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
263  2024-10-09T05:01:10.275Z c4e91b1f-b44f-479d-afa7-cca94ca901b3
264  2024-10-09T05:01:10.275Z da8f0b7c-e606-4620-861c-8909322dd7be
265  2024-10-09T05:01:10.275Z 860067e4-3222-4ea0-a9eb-117ce838a2e3
266  2024-10-09T05:01:10.275Z 75d2b17c-e40a-42a2-bc14-d2172fc7dc26
267  2024-10-09T05:01:10.275Z 173bcaca-a42e-4679-91e4-56b05334b7df
268  2024-10-09T05:01:10.275Z a9fd0cad-5e3f-4d43-b6e7-716aafe17d9c
269  2024-10-09T05:01:10.275Z 2bae0d72-9593-4fd5-99d8-3de2286a46a5
270  2024-10-09T05:01:10.275Z cda392ec-4972-43e4-916a-0b080e12c11c
271  2024-10-09T05:01:10.275Z e67948fb-8911-416c-a755-7b233db46adc
272  2024-10-09T05:01:10.275Z 5427a932-36fe-4b62-b020-6497c82579e8
273  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
274  2024-10-09T05:01:10.275Z 84351cd4-635c-425a-bc1b-2842bbfaa71a
275  2024-10-09T05:01:10.275Z ee443b9a-2c86-4049-b1c8-e631d2351287
276  2024-10-09T05:01:10.275Z 5920383e-ae4b-47f0-8b9f-bb8d50a755c3
277  2024-10-09T05:01:10.275Z 78909ed5-1e5d-403b-b349-fa6f6cb6743c
278  2024-10-09T05:01:10.275Z a504877f-045d-443d-9368-63b0df35565d
279  2024-10-09T05:01:10.275Z 61cc2993-9870-432c-83e3-5ae89324364a
280  2024-10-09T05:01:10.275Z 23421a54-1cbd-4d27-b6d7-b3e95772ac61
281  2024-10-09T05:01:10.275Z d7f7413e-7f7b-452d-82ac-e366c8ab46f8
282  2024-10-09T05:01:10.275Z d99f31ec-c852-4623-a3b9-804f90fca696
283  2024-10-09T05:01:10.275Z 5294fe84-11cc-4eec-83f2-c93625106621
284  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69
285  2024-10-09T05:01:10.275Z a94c648e-f6e2-4850-a0ac-f087f1962c21
286  2024-10-09T05:01:10.275Z dc719970-3a57-48bb-9a29-832e74902b3c
287  2024-10-09T05:01:10.275Z b689da9a-1b1b-4b42-bd36-42dda839c6fd
288  2024-10-09T05:01:10.275Z fbb6c4a7-6e34-4f58-9e6b-06f68e6e767c
289  2024-10-09T05:01:10.275Z fd61b5a1-3008-4f5b-af8a-61d96702fffe
290  2024-10-09T05:01:10.275Z 5060da10-b6a2-477f-82e1-ee1b75d1db5d
291  2024-10-09T05:01:10.275Z 79437049-b37e-454e-8490-75d040952728
292  2024-10-09T05:01:10.275Z 910f67f7-a3ed-4624-8452-4d71bfa1bf26
293  2024-10-09T05:01:10.275Z 86f58b43-f366-4929-a3b4-0a8db253cbf3
294  2024-10-09T05:01:10.275Z 100fb04e-259b-4ca7-aaf8-21277df36770
295  2024-10-09T05:01:10.275Z 72a42120-098b-4d96-a225-0414ff7b4d47
296  2024-10-09T05:01:10.275Z f72426b7-3747-4416-b2ec-4d80b41d0f5a
297  2024-10-09T05:01:10.275Z 9db12509-19e6-4e69-bfd6-df5dbbcc7a69

In [5]:
all_desc <- desc$descriptors
all_desc$specimens.specimenType <- desc$specimens$specimens.specimenType
all_desc$specimens.specimenGuid <- desc$specimens$specimens.specimenGuid

In [6]:
all_desc

     lastUpdated              sample.id
1    2024-10-09T05:01:10.275Z 451e9cf5-985a-4268-91d1-4f25c7c3bc4b
2    2024-10-09T05:01:10.275Z 7589318f-5097-4a42-b32d-0083fed4b465
3    2024-10-09T05:01:10.275Z 5884c8e8-4aed-4179-b771-7be7ca01ddd3
4    2024-10-09T05:01:10.275Z 5c140d31-db89-4480-af28-a82704221c72
5    2024-10-09T05:01:10.275Z 0efe95fa-ffb0-4337-944f-8006ad3e3e19
6    2024-10-09T05:01:10.275Z f954415c-c278-4df5-b617-9e98d8d4319e
7    2024-10-09T05:01:10.275Z db4f13c2-c736-4444-b536-b21b45be5108
8    2024-10-09T05:01:10.275Z 1708a8dd-32f6-4315-9c31-e401eafc8451
9    2024-10-09T05:01:10.275Z bcedc25b-ba30-4118-8874-ea15c2b48179
10   2024-10-09T05:01:10.275Z 5348768d-dc13-4f87-8aa5-1187215a53fd
11   2024-10-09T05:01:10.275Z 0aa782e4-c8af-41bc-952c-9cecd2775f06
12   2024-10-09T05:01:10.275Z 5de2db28-ef6a-41dc-a1e5-0a938db2e720
13   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
14   2024-10-09T05:01:10.275Z d5e73974-286a-4403-a9f2-bba5da491267
15   2024-10-09T05:01:10.275Z ab41a4ec-dc84-430e-a41b-1b4bfb5bf7e4
16   2024-10-09T05:01:10.275Z 68b29144-4d06-4c27-b911-1974fbf19080
17   2024-10-09T05:01:10.275Z b98ef544-50eb-47c9-993f-8a3b3868b96e
18   2024-10-09T05:01:10.275Z 6261226a-0493-4f04-8059-d3968af02774
19   2024-10-09T05:01:10.275Z 06af71db-28cb-4180-9b67-756dcf547cff
20   2024-10-09T05:01:10.275Z 024da332-08cf-4886-849f-0e86a859cba4
21   2024-10-09T05:01:10.275Z 773699ec-9585-4794-b8b0-51e3ffecbf0f
22   2024-10-09T05:01:10.275Z 45dd11fb-002f-478a-9f88-cc0544cfd84f
23   2024-10-09T05:01:10.275Z 15b1093d-12b2-4b3c-84ac-b20c37b4c6c1
24   2024-10-09T05:01:10.275Z aac91ea2-407d-4673-be21-0246b106c6d3
25   2024-10-09T05:01:10.275Z 5450cef8-8f3e-4552-a6d8-987d4e6e0b08
26   2024-10-09T05:01:10.275Z 18ebf735-03cb-4f4a-88bd-93862c3ab5a7
27   2024-10-09T05:01:10.275Z b7cbab75-5ebc-4ddd-ac85-c60fbf64d6c7
28   2024-10-09T05:01:10.275Z 9ae566db-f7e3-49b5-b7c1-e2ee68b3c5fe
29   2024-10-09T05:01:10.275Z 258c817d-fb20-47e9-b54b-4b2f54979e86
30   2024-10-09T05:01:10.275Z 098bcd30-9f7e-4c63-931b-06570412a24a
⋮    ⋮                        ⋮
2607 2024-10-09T05:01:10.275Z 18231fc1-9ad4-4fde-a0b4-2daaa02d8e62
2608 2024-10-09T05:01:10.275Z 738a3c49-a7a2-4ef9-9e2b-85fce7f93548
2609 2024-10-09T05:01:10.275Z 07b2f67d-e8df-42f4-a3c9-922f55d444f3
2610 2024-10-09T05:01:10.275Z 92f38b76-dc15-4cc7-a030-899fdb24ce75
2611 2024-10-09T05:01:10.275Z dfad8475-bd96-457e-a3bb-1ed869a25e52
2612 2024-10-09T05:01:10.275Z 731e2569-ba95-480f-a62f-8117601f7481
2613 2024-10-09T05:01:10.275Z 6089f3f6-3046-41ee-9048-c90b385c0d04
2614 2024-10-09T05:01:10.275Z 89845255-a53c-4d97-90b8-21f2a0439702
2615 2024-10-09T05:01:10.275Z b5f5c2c8-8508-4cd5-ae24-91030a903fb5
2616 2024-10-09T05:01:10.275Z e7a673dd-2f2d-4b2a-b8bb-ba8a40041629
2617 2024-10-09T05:01:10.275Z 11bc8c7b-bb6c-4924-9b3c-db8d87dae566
2618 2024-10-09T05:01:10.275Z 2e449862-bfbd-412f-9307-5c9084d6c236
2619 2024-10-09T05:01:10.275Z 4e311065-a49c-42a7-903f-e61715751dd5
2620 2024-10-09T05:01:10.275Z efff0f4d-76b6-48d9-a204-068cb0e85507
2621 2024-10-09T05:01:10.275Z 7fc0d02a-4beb-4726-902e-30b412a2ee7e
2622 2024-10-09T05:01:10.275Z f99cfeb7-3eec-42fd-9e1b-295e33fa0a17
2623 2024-10-09T05:01:10.275Z fed50e4a-dab2-4be6-a02e-a530f0416234
2624 2024-10-09T05:01:10.275Z 19be425d-2a2d-4d4e-b74b-2dddd9e15f06
2625 2024-10-09T05:01:10.275Z 9cf66881-cd88-4e98-9deb-b65ff0eed14b
2626 2024-10-09T05:01:10.275Z bfa1f771-e1f5-4fff-9975-efc514bd2a1c
2627 2024-10-09T05:01:10.275Z 55640cef-8c6c-4e39-8c55-14a152a2420f
2628 2024-10-09T05:01:10.275Z 2eeb4d1c-c606-4a26-b369-8a5878bc1230
2629 2024-10-09T05:01:10.275Z af23fbfc-41a2-4b72-a9be-4a931c58d9d8
2630 2024-10-09T05:01:10.275Z e5a5e9b2-c56d-4683-a586-d3ba15618365
2631 2024-10-09T05:01:10.275Z 6771c4c6-3059-4720-a664-ace4a5c08253
2632 2024-10-09T05:01:10.275Z d2a01bca-02a2-4368-ad00-5c6227f48327
2633 2024-10-09T05:01:10.275Z 3e04a8f5-efc6-4fae-8c24-89ffa9c17fe8
2634 2024-10-09T05:01:10.275Z 6a843dc9-769f-4114-b1fe-046ef1bd4c53
2635 2024-10-09T05:01:10.275Z 1988b698-cb2c-48a0-9187-fd3b186537a9
2636 2024-10-09T05:01:10.275Z 5bd1f2bc-dbdb-44f7-96d4-d876abd7c595
     sample.bridgingControl sample.sampleKitGuid sample.visitName
1    false                  KT02739              Other - Non-Flu
2    false                  KT02757              Other - Non-Flu
3    false                  KT02752              Other - Non-Flu
4    false                  KT03089              Flu Year 2 Day 90
5    false                  KT04685              Other - Non-Flu
6    false                  KT02772              Other - Non-Flu
7    false                  KT02747              Other - Non-Flu
8    false                  KT02745              Other - Non-Flu
9    false                  KT02750              Other - Non-Flu
10   false                  KT03079              Flu Year 2 Day 90
11   false                  KT03069              Flu Year 2 Day 90
12   false                  KT03900              Flu Year 3 Stand-Alone
13   false                  KT01500
14   false                  KT02709              Other - Non-Flu
15   false                  KT01500
16   false                  KT02068              Other - Non-Flu
17   false                  KT02070              Other - Non-Flu
18   false                  KT02728              Other - Non-Flu
19   false                  KT02726              Other - Non-Flu
20   false                  KT02695              Flu Year 1 Day 90
21   false                  KT02688              Other - Non-Flu
22   false                  KT02081              Flu Year 1 Day 7
23   false                  KT02073              Flu Year 1 Stand-Alone
24   false                  KT02078              Flu Year 1 Day 0
25   false                  KT02080              Other - Non-Flu
26   false                  KT04436              Other - Non-Flu
27   false                  KT04435              Other - Non-Flu
28   false                  KT04437              Other - Non-Flu
29   false                  KT02612              Other - Non-Flu
30   false                  KT02613              Other - Non-Flu
⋮    ⋮                      ⋮                    ⋮
2607 false                  KT06717
2608 false                  KT06719
2609 false                  KT06722
2610 false                  KT06729
2611 false                  KT06728
2612 false                  KT06746
2613 false                  KT06725
2614 false                  KT06743
2615 false                  KT06741
2616 false                  KT06723
2617 false                  KT06737
2618 false                  KT06731
2619 false                  KT06734
2620 false                  KT06735
2621 true                   KT01500
2622 false                  KT06727
2623 false                  KT06721
2624 false                  KT06732
2625 false                  KT06718
2626 false                  KT06739
2627 false                  KT06720
2628 false                  KT06724
2629 false                  KT06726
2630 false                  KT06738
2631 false                  KT06736
2632 false                  KT06742
2633 false                  KT06744
2634 false                  KT06745
2635 false                  KT06733
2636 false                  KT06730
     sample.visitDetails             sample.drawDate
1    MM Post Induction 2-Cycles      2022-10-01T00:00:00Z
2    MM Pre-Treatment                2022-08-01T00:00:00Z
3    MM Post Induction 2-Cycles      2022-07-01T00:00:00Z
4    N/A - Flu-Series Timepoint Only 2022-01-01T00:00:00Z
5    MM End Induction 1st Draw       2022-11-01T00:00:00Z
6    MM End Induction 1st Draw       2022-10-01T00:00:00Z
7    MM Post Induction 2-Cycles      2022-06-01T00:00:00Z
8    MM Post Transplant 60 Days      2022-06-01T00:00:00Z
9    MM Post Induction 2-Cycles      2022-07-01T00:00:00Z
10   N/A - Flu-Series Timepoint Only 2022-01-01T00:00:00Z
11   N/A - Flu-Series Timepoint Only 2022-01-01T00:00:00Z
12   N/A - Flu-Series Timepoint Only 2022-03-01T00:00:00Z
13                                   2019-09-01T00:00:00Z
14   MM Pre-Treatment                2022-03-01T00:00:00Z
15                                   2019-09-01T00:00:00Z
16   MM Post Induction 2-Cycles      2021-10-01T00:00:00Z
17   MM Post Induction 2-Cycles      2021-11-01T00:00:00Z
18   MM Pre-Treatment                2022-05-01T00:00:00Z
19   MM Pre-Treatment                2022-05-01T00:00:00Z
20   N/A - Flu-Series Timepoint Only 2022-03-01T00:00:00Z
21   MM Post Induction 2-Cycles      2022-02-01T00:00:00Z
22   N/A - Flu-Series Timepoint Only 2021-12-01T00:00:00Z
23   N/A - Flu-Series Timepoint Only 2021-11-01T00:00:00Z
24   N/A - Flu-Series Timepoint Only 2021-12-01T00:00:00Z
25   MM Pre-Treatment                2021-12-01T00:00:00Z
26   MM End Induction 1st Draw       2022-11-01T00:00:00Z
27   MM End Induction 1st Draw       2022-10-01T00:00:00Z
28   MM End Induction 1st Draw       2022-11-01T00:00:00Z
29   MM Pre-Treatment                2022-05-01T00:00:00Z
30   MM Pre-Treatment                2022-05-01T00:00:00Z
⋮    ⋮                               ⋮
2607                                 2019-11-01T00:00:00Z
2608                                 2020-03-01T00:00:00Z
2609                                 2018-10-01T00:00:00Z
2610                                 2023-06-01T00:00:00Z
2611                                 2019-10-01T00:00:00Z
2612                                 2017-05-01T00:00:00Z
2613                                 2019-10-01T00:00:00Z
2614                                 2005-06-01T00:00:00Z
2615                                 2011-08-01T00:00:00Z
2616                                 2023-03-01T00:00:00Z
2617                                 2017-12-01T00:00:00Z
2618                                 2023-02-01T00:00:00Z
2619                                 2021-08-01T00:00:00Z
2620                                 2022-03-01T00:00:00Z
2621                                 2019-09-01T00:00:00Z
2622                                 2022-04-01T00:00:00Z
2623                                 2023-06-01T00:00:00Z
2624                                 2023-08-01T00:00:00Z
2625                                 2022-10-01T00:00:00Z
2626                                 2016-06-01T00:00:00Z
2627                                 2023-09-01T00:00:00Z
2628                                 2018-05-01T00:00:00Z
2629                                 2022-12-01T00:00:00Z
2630                                 2018-09-01T00:00:00Z
2631                                 2018-08-01T00:00:00Z
2632                                 2023-07-01T00:00:00Z
2633                                 2018-02-01T00:00:00Z
2634                                 2010-04-01T00:00:00Z
2635                                 2023-03-01T00:00:00Z
2636                                 2023-08-01T00:00:00Z
     sample.daysSinceFirstVisit sample.diseaseStatesRecordedAtVisit
1    77                         Multiple Myeloma
2    0                          Multiple Myeloma
3    72                         Multiple Myeloma
4    541                        NA
5    189                        Multiple Myeloma
6    155                        Multiple Myeloma
7    78                         Multiple Myeloma
8    278                        Multiple Myeloma
9    64                         Multiple Myeloma
10   400                        NA
11   499                        NA
12   450                        NA
13                              NA
14   0                          NA
15                              NA
16   42                         NA
17   62                         NA
18   0                          NA
19   0                          NA
20   378                        NA
21   64                         NA
22   306                        NA
23   269                        NA
24   297                        NA
25   0                          NA
26   189                        Multiple Myeloma
27   155                        Multiple Myeloma
28   232                        Multiple Myeloma
29   0                          NA
30   0                          NA
⋮    ⋮                          ⋮
2607                            NA
2608                            NA
2609                            NA
2610                            NA
2611                            NA
2612                            NA
2613                            NA
2614                            NA
2615                            NA
2616                            NA
2617                            NA
2618                            NA
2619                            NA
2620                            NA
2621                            NA
2622                            NA
2623                            NA
2624                            NA
2625                            NA
2626                            NA
2627                            NA
2628                            NA
2629                            NA
2630                            NA
2631                            NA
2632                            NA
2633                            NA
2634                            NA
2635                            NA
2636                            NA
     file.id                              ⋯ subject.subjectGuid
1    ba71d552-b287-4b79-9153-56a50e7c2245 ⋯ FH1022
2    af7081f5-7f66-440e-bb53-2ad6c2aa1e73 ⋯ FH1022
3    b65ca25c-eb60-4976-93fe-a01f9f917f71 ⋯ FH1020
4    b0efd336-fa15-4986-902c-4f316927afd5 ⋯ BR2024
5    16548655-5e66-4c82-ba35-18b039b8e5aa ⋯ FH1020
6    6f0057cc-c6af-444d-9c48-ed11a3e947a4 ⋯ FH1021
7    4b67b687-7a11-4a30-94c0-c3f803228903 ⋯ FH1016
8    de74b22e-1b94-4df2-886a-f23149de75e9 ⋯ FH1017
9    def41df0-2095-4a8e-99b0-371efccc0b40 ⋯ FH1021
10   ddfa9d88-2d83-4859-9158-4a5c14eb498c ⋯ BR2053
11   113968bd-0a0b-40e4-bde0-5d92548974b2 ⋯ BR2028
12   3009bbc0-a6a3-42f6-ae5d-ce29f9136878 ⋯ BR2053
13   8d9d60a2-ca80-4b80-b6be-b94bbb55a3fd ⋯ HMN169517
14   8cf74249-9fdd-402d-964b-f7daece6c40f ⋯ FH1016
15   5fe86cba-c297-46df-bff5-0dd45367308b ⋯ HMN169517
16   550eae53-aee2-4944-832b-a2780a9c3c9e ⋯ FH1018
17   6a0c4540-dc1b-409a-b49d-e283f63aeb81 ⋯ FH1017
18   842dab49-05f0-4635-92b0-c970a3e17e4f ⋯ FH1021
19   af865011-8ba6-45ec-beca-40f1c6a655cc ⋯ FH1020
20   048fab73-6dd7-4136-bb81-044a8ecd181a ⋯ FH1012
21   d20bbabc-d1d8-4e2a-b3e9-976b1b29b915 ⋯ FH1019
22   36b27346-7ac0-4352-b6a4-a5a59041dd59 ⋯ FH1012
23   833548bf-7d82-4960-8ad3-868ca3fff71d ⋯ FH1012
24   839aff89-d084-4122-a2ba-9b929498d0e9 ⋯ FH1012
25   65db7cd1-adb7-47e8-b019-618975b76313 ⋯ FH1019
26   a237caab-5c02-45ce-93d3-177102bca8c2 ⋯ FH1020
27   e900e1a0-32bd-40c3-8930-f2045af736b9 ⋯ FH1021
28   be1d62f5-186a-4e41-af2d-f7dab0609ef9 ⋯ FH1016
29   8fc4f3cc-2d64-4c74-9dd8-f7051bde2507 ⋯ FH1020
30   a9208600-6116-4afd-b610-4b73a79abed7 ⋯ FH1021
⋮    ⋮                                    ⋱ ⋮
2607 4f6b1b2d-070a-4e21-a8a4-66d284d1d504 ⋯ BR3001
2608 197c9490-f7ca-427d-a832-ad6f6dc8c28f ⋯ BR3003
2609 7f8bc145-b86f-4088-b129-9be62bbeda0e ⋯ BR3006
2610 c3908f6f-e55c-4ebf-ba1f-e5f928bec15a ⋯ BR3013
2611 5a1eae4e-e261-47b2-b77c-9176a9ed49d6 ⋯ BR3012
2612 6a7ead78-9cb5-47ef-ba52-ef0c622e8f53 ⋯ BR3030
2613 c852ca84-326a-4175-ab32-77b21fedb4b7 ⋯ BR3009
2614 dc943a96-d9c6-49a7-91b1-482a24d47321 ⋯ BR3027
2615 49bb2902-f0d1-4bfc-83ce-78d0b80f1710 ⋯ BR3025
2616 8facecca-84dc-4df1-93ba-de837971b9d0 ⋯ BR3007
2617 eaba666e-bacd-43c1-895e-cbf0329d1538 ⋯ BR3021
2618 de71c5be-989b-4f4b-8426-e4096bd95cee ⋯ BR3015
2619 f99a48ea-4aaa-438f-b90a-42037860a44c ⋯ BR3018
2620 cea0b82d-e77b-4f6b-ab99-6ac687eee6f4 ⋯ BR3019
2621 9a45de58-7ff4-4af5-b9c0-43785df5d8b0 ⋯ HMN169517
2622 29e34658-a6ba-41b9-8fee-81e120448dea ⋯ BR3011
2623 62551e5d-1a07-4181-9bef-e2e5ea5b5673 ⋯ BR3005
2624 0140c3db-afc6-41ad-8f9f-fadb9e739ef4 ⋯ BR3016
2625 43fae4ad-6901-43f6-a048-1869a587d91a ⋯ BR3002
2626 f173aed5-9838-4732-b4f5-7d195e8ff17f ⋯ BR3023
2627 5ccb769d-d1a3-4b48-9bf7-bb4e3a90d450 ⋯ BR3004
2628 0a714613-c7ab-4df4-af21-04b5635852ad ⋯ BR3008
2629 5283439e-3a06-40b9-8d5c-1f58eb9a89f5 ⋯ BR3010
2630 2714ea3f-c55c-489c-bb40-d4e7ef05d37d ⋯ BR3022
2631 7c75ec79-37ea-45cb-8c13-f2e46a5b3af0 ⋯ BR3020
2632 ee1f11b0-3bc7-40b9-b538-343fae3198bf ⋯ BR3026
2633 a5692208-ef84-41de-b547-56bbacab57d7 ⋯ BR3028
2634 eeb8c570-38d6-4ee3-befc-2910afeb06f8 ⋯ BR3029
2635 d2799fe3-d4b3-4e35-ae57-a2973b80acca ⋯ BR3017
2636 59b97079-7246-4e48-8fa6-77befb010b8d ⋯ BR3014
     cohort.cohortGuid file.userTags.details file.userTags.group
1    FH1               NA                    NA
2    FH1               NA                    NA
3    FH1               NA                    NA
4    BR2               NA                    NA
5    FH1               NA                    NA
6    FH1               NA                    NA
7    FH1               NA                    NA
8    FH1               NA                    NA
9    FH1               NA                    NA
10   BR2               NA                    NA
11   BR2               NA                    NA
12   BR2               NA                    NA
13   BIOIVT            NA                    NA
14   FH1               NA                    NA
15   BIOIVT            NA                    NA
16   FH1               NA                    NA
17   FH1               NA                    NA
18   FH1               NA                    NA
19   FH1               NA                    NA
20   FH1               NA                    NA
21   FH1               NA                    NA
22   FH1               NA                    NA
23   FH1               NA                    NA
24   FH1               NA                    NA
25   FH1               NA                    NA
26   FH1
27   FH1
28   FH1
29   FH1
30   FH1
⋮    ⋮                 ⋮                     ⋮
2607 BR3
2608 BR3
2609 BR3
2610 BR3
2611 BR3
2612 BR3
2613 BR3
2614 BR3
2615 BR3
2616 BR3
2617 BR3
2618 BR3
2619 BR3
2620 BR3
2621 BIOIVT
2622 BR3
2623 BR3
2624 BR3
2625 BR3
2626 BR3
2627 BR3
2628 BR3
2629 BR3
2630 BR3
2631 BR3
2632 BR3
2633 BR3
2634 BR3
2635 BR3
2636 BR3
     file.userTags.name      file.userTags.origin file.userTags.other
1    NA                      NA                   NA
2    NA                      NA                   NA
3    NA                      NA                   NA
4    NA                      NA                   NA
5    NA                      NA                   NA
6    NA                      NA                   NA
7    NA                      NA                   NA
8    NA                      NA                   NA
9    NA                      NA                   NA
10   NA                      NA                   NA
11   NA                      NA                   NA
12   NA                      NA                   NA
13   NA                      NA                   NA
14   NA                      NA                   NA
15   NA                      NA                   NA
16   NA                      NA                   NA
17   NA                      NA                   NA
18   NA                      NA                   NA
19   NA                      NA                   NA
20   NA                      NA                   NA
21   NA                      NA                   NA
22   NA                      NA                   NA
23   NA                      NA                   NA
24   NA                      NA                   NA
25   NA                      NA                   NA
26   B162-CITE-5
27   B162-CITE-5
28   B162-CITE-5
29   B162-CITE-5
30   B162-CITE-5
⋮    ⋮                       ⋮                    ⋮
2607 EXP-00955-FC-00541-TEA1
2608 EXP-00955-FC-00541-TEA1
2609 EXP-00955-FC-00541-TEA1
2610 EXP-00955-FC-00541-TEA1
2611 EXP-00955-FC-00541-TEA1
2612 EXP-00955-FC-00541-TEA1
2613 EXP-00955-FC-00541-TEA1
2614 EXP-00955-FC-00541-TEA1
2615 EXP-00955-FC-00541-TEA1
2616 EXP-00955-FC-00541-TEA1
2617 EXP-00955-FC-00541-TEA1
2618 EXP-00955-FC-00541-TEA1
2619 EXP-00955-FC-00541-TEA1
2620 EXP-00955-FC-00541-TEA1
2621 EXP-00956-FC-00547-TEA
2622 EXP-00956-FC-00547-TEA
2623 EXP-00956-FC-00547-TEA
2624 EXP-00956-FC-00547-TEA

In [6]:
#scrna_desc <- filter(all_desc, ! file.batchID %in% c('EXP-00243','EXP-00454','EXP-00776','EXP-00791','EXP-00955','EXP-00956'))
scrna_desc <- filter(all_desc, ! file.batchID %in% c('B065'))

In [7]:
cusd <- filter(scrna_desc, cohort.cohortGuid %in% c('UP1'))
dim(cusd)

[1] 222  32

In [8]:
table(duplicated(cusd$sample.sampleKitGuid))

FALSE  TRUE
  218     4

In [27]:
## samples selected in current RA study
ra141 <- c("KT00070","KT00058","KT00057","KT00077","KT00060","KT00056","KT00052","KT00064","KT00063","KT00065","KT00076","KT00069","KT00074","KT00221","KT00067","KT00068","KT00075","KT00073","KT00086","KT00090","KT00081","KT00211","KT00095","KT00092","KT00084","KT00087","KT00088","KT00443","KT00420","KT00436","KT00461","KT00453","KT00477","KT00480","KT00465","KT00463","KT00473","KT00464","KT00468","KT04115","KT02177","KT02971","KT02992","KT02969","KT02958","KT02953","KT02985","KT02970","KT02974","KT04072","KT02957","KT02952","KT02978","KT04118","KT04092","KT04445","KT04633","KT03931","KT04652","KT04634","KT04933","KT04937","KT04671","KT04906","KT04905","KT00120","KT00114","KT00108","KT00107","KT00118","KT02287","KT02292","KT02284","KT02286","KT02303","KT02298","KT02135","KT02845","KT00055","KT04113","KT04108","KT00072","KT02132","KT04462","KT02844","KT00447","KT04085","KT02963","KT00474","KT02975","KT04924","KT02856","KT02139","KT02141","KT02140","KT02981","KT04625","KT00109","KT00790","KT00777","KT00778","KT00493","KT00440","KT00227","KT00099","KT00492","KT00208","KT00082","KT00416","KT00219","KT04474","KT04102","KT02817","KT00097","KT02948","KT00497","KT04105","KT02839","KT02133","KT00424","KT00093","KT00500","KT00202","KT03936","KT04103","KT00409","KT02823","KT00467","KT03930","KT02830","KT00482","KT02164","KT02854","KT02853","KT00478","KT02136","KT03939","KT02968","KT03932","KT00103","KT00105")

In [9]:
dup = cusd[duplicated(cusd$sample.sampleKitGuid),]
all_dup_samp <- unique(dup$sample.sampleKitGuid)

all_dups = filter(cusd, sample.sampleKitGuid %in% all_dup_samp)

In [10]:
dim(all_dups)
length(unique(all_dups$sample.sampleKitGuid))

[1]  8 32

[1] 4

In [11]:
unique_samp = filter(cusd, ! sample.sampleKitGuid %in% all_dup_samp)
dim(unique_samp)

[1] 214  32

In [13]:
table(unique_samp$'specimens.specimenType')

                   PBMC      Plasma Tempus Tube
          2          96         115           1

In [14]:
unique_samp$'specimens.specimenType'

  [1] "PBMC"        "PBMC"        "Plasma"      ""            "PBMC"
  [6] "Plasma"      "PBMC"        "Plasma"      "Plasma"      "PBMC"
 [11] "PBMC"        "Plasma"      "PBMC"        "PBMC"        "PBMC"
 [16] "PBMC"        "PBMC"        "Plasma"      "PBMC"        "Plasma"
 [21] "Plasma"      "Plasma"      "PBMC"        "PBMC"        "PBMC"
 [26] "Plasma"      "PBMC"        "PBMC"        "Plasma"      "Plasma"
 [31] "PBMC"        "Tempus Tube" "Plasma"      "PBMC"        "Plasma"
 [36] ""            "PBMC"        "PBMC"        "PBMC"        "Plasma"
 [41] "PBMC"        "Plasma"      "Plasma"      "Plasma"      "Plasma"
 [46] "PBMC"        "Plasma"      "PBMC"        "Plasma"      "Plasma"
 [51] "Plasma"      "PBMC"        "Plasma"      "Plasma"      "Plasma"
 [56] "Plasma"      "Plasma"      "PBMC"        "Plasma"      "PBMC"
 [61] "PBMC"        "PBMC"        "Plasma"      "PBMC"        "PBMC"
 [66] "Plasma"      "PBMC"        "Plasma"      "PBMC"        "Plasma"
 [71] "PBMC"        "PBMC"        "Plasma"      "Plasma"      "Plasma"
 [76] "Plasma"      "Plasma"      "Plasma"      "Plasma"      "PBMC"
 [81] "Plasma"      "PBMC"        "PBMC"        "PBMC"        "Plasma"
 [86] "Plasma"      "PBMC"        "Plasma"      "PBMC"        "PBMC"
 [91] "PBMC"        "Plasma"      "PBMC"        "Plasma"      "PBMC"
 [96] "PBMC"        "Plasma"      "PBMC"        "Plasma"      "PBMC"
[101] "Plasma"      "Plasma"      "PBMC"        "PBMC"        "PBMC"
[106] "PBMC"        "Plasma"      "Plasma"      "Plasma"      "Plasma"
[111] "Plasma"      "Plasma"      "Plasma"      "Plasma"      "PBMC"
[116] "Plasma"      "Plasma"      "Plasma"      "PBMC"        "PBMC"
[121] "PBMC"        "PBMC"        "Plasma"      "Plasma"      "PBMC"
[126] "Plasma"      "PBMC"        "PBMC"        "PBMC"        "Plasma"
[131] "Plasma"      "Plasma"      "Plasma"      "Plasma"      "Plasma"
[136] "Plasma"      "Plasma"      "Plasma"      "Plasma"      "Plasma"
[141] "PBMC"        "PBMC"        "Plasma"      "Plasma"      "Plasma"
[146] "Plasma"      "Plasma"      "Plasma"      "PBMC"        "PBMC"
[151] "PBMC"        "Plasma"      "Plasma"      "PBMC"        "Plasma"
[156] "PBMC"        "PBMC"        "Plasma"      "PBMC"        "PBMC"
[161] "Plasma"      "Plasma"      "Plasma"      "PBMC"        "PBMC"
[166] "Plasma"      "PBMC"        "Plasma"      "Plasma"      "PBMC"
[171] "PBMC"        "Plasma"      "PBMC"        "Plasma"      "Plasma"
[176] "PBMC"        "PBMC"        "PBMC"        "PBMC"        "PBMC"
[181] "Plasma"      "Plasma"      "PBMC"        "Plasma"      "Plasma"
[186] "Plasma"      "PBMC"        "Plasma"      "PBMC"        "Plasma"
[191] "Plasma"      "PBMC"        "Plasma"      "PBMC"        "PBMC"
[196] "Plasma"      "Plasma"      "Plasma"      "PBMC"        "Plasma"
[201] "Plasma"      "PBMC"        "Plasma"      "PBMC"        "PBMC"
[206] "PBMC"        "PBMC"        "PBMC"        "Plasma"      "Plasma"
[211] "Plasma"      "Plasma"      "Plasma"      "Plasma"

In [38]:
setwd('/home/jupyter/')

In [39]:
all_dups <- all_dups %>% arrange(file.batchID)
write.csv(all_dups, 'cusd_allduplicateSamples.csv')

In [40]:
dim(cusd)

[1] 612  32

In [41]:
write.csv(cusd, 'allCU-SDsamples_includingDuplicates.csv')

### Duplicates removed through manual review of the duplicated samples. 
Some samples were processed in mulitple batches due to experimental errors or data QC flags. For such samples only the latest run that passed QC is considered to retain unique samples in the dataset. These samples were selected through manual review and discussion with wet-lab to confirm their integrity. The file ids of the selected samples are listed below.

In [42]:
selected_ids <- c('bff40a9d-15ba-4af3-b277-bc94a53765f0', 'acd4a08c-1de6-4778-ae1b-f2ad2ff24420', '96b76772-f8a5-4472-a85d-73f8a11e5667', 'b5020ad1-139f-4c73-8651-56ddd4713742', '1312850d-c89e-46b9-a1c1-1c3a8518e7b9', '34f7fb29-e412-4f92-8770-55f8e19d40fe', '45456368-ab47-403a-98a8-b5249b2dddee', 'bbf02995-03de-4010-99fd-1e8b559badb2', '80b598ae-8e7c-4776-872e-e426163fe2fb', 'f59e3c98-582b-4ef7-87c1-09d6425843c5', '5e3ce6b9-95a9-4893-8123-b9b7a5d5c9d8', 'f90e1830-6440-4db0-a2df-fa71f1b088aa', '455c7c7c-ceb4-48d5-81ee-6b8bcaa7eb02', 'ee66797f-ef97-49df-87e4-853e2cb84f44', '8fcff6ce-ebd3-442a-b608-2f301b4d1f8c', 'e4dbe2fc-fc8b-40fe-b546-fcade3ae995c', '1703d258-9f00-447f-9f00-4702d5aef553', '3c7afa9d-9dc2-4933-b4b3-b67b0dd0d8b3', 'b7601874-9628-498a-a1a9-3d3a1d9de2e6', '9cfaeae1-aebb-427f-9e09-daae1b8d9549', 'b65365e6-5d2e-49d5-8627-e1c5fe45c042', '0ef45c44-9083-40a3-846c-f68b26901572', 'aeed82a9-042f-4b6d-8f48-cbc732806502', 'fe0cc666-bdac-484e-bb3e-792f5cb9fb08', '24d6f4e4-b704-442f-a886-23282b381286', '92bb95c6-17c5-40f5-8868-066fbcaabf35', 'bee488bc-4a87-474c-8532-1dfaa5cfb93d', '0d12b6ff-ad7d-43dc-b215-9ffc5e486512', '1254856a-a747-4228-92b1-93d8062115cf', '3b2c1cff-67d3-4715-8ccb-d4b769f21a55', '3dfaf983-3e4c-48b8-9e48-e8a12482898f', 'a1cd9778-36cb-4949-aab6-70cde4409892', '073b76b3-ecf7-451d-adff-6cc5ea05f9e3', 'bd5bacfe-0822-43b9-ab79-dad3081351cb', 'a9d36b41-2bf0-4b54-b8b7-200587117d52', '11335eba-3ccc-4a0a-892d-a72727906a6a', '12abd8e9-1360-4fb9-9fc4-56ee98a143ed', '46f50f2c-7780-4e46-9092-357a6dad5235', '9f989635-d713-4233-b04c-da73427f7514', 'fd7be30d-a014-418f-ac0d-d08443f9ab64', 'e2d397aa-f365-4be5-a6e6-c189f9df1bb1', 'aa58afa5-d46e-407a-b737-ce9c53b4c568', 'ccee65fa-77d3-419b-8956-d24fdfd95f31', '84844967-a3c6-42db-b8a8-f0c255d4df60', '35033f85-9f29-4895-bab2-fd6c8967925b', '154166ff-5b1f-437f-89d6-1df5786945ba', 'e8b5c180-a4ed-439a-8e46-e40ffba14be1', 'ccd401b0-ec62-42bd-bef0-bd2de94730d7', '7b12934f-2716-416d-9280-1b1b5c99395c', 'beef3311-cc62-432d-a17b-72bcaec46839', '57b82b69-9c10-49df-a333-dc9ae9b737c1', '9dc98077-cac0-4967-90d7-18b541f44a82', 'f92397ac-f530-44ce-aea9-a37b06dd9ec0', 'e49ff1f7-ec03-400a-8fd0-9ea75c03430f', '96c840a5-80eb-431f-99ec-0d87316e9d7a', 'cb9a83ac-5ef2-4b1b-b2f8-a8a7e1ee923b', 'dad81603-3655-40f8-a6c5-9abd1d83dabc', '0a3c3ce1-2006-4a07-a086-362a1eda303b', '11e96530-4753-4515-98aa-5607bcc0e862', 'afa5be57-28ae-4f69-aa52-de6fe8b955e7', 'd1c6a86c-9d10-4790-9ebf-abb88162cf01', 'f7abac4a-1eae-4db5-ad94-0bc633945c34', '1d39c673-d868-4ad1-b90a-8cc3d682c150', '28c20f99-550b-4ce1-ad10-fa08df774f12', '3e2d73c3-ec39-42d3-8b44-7cdacd4a53bc', '8aa30541-2766-4c70-9ec9-977a671ec2ef', '82ac4092-e1fc-4290-b741-2dd1937c7f73', '0a34b5d2-3e09-42ce-80da-0e5b31da0c0a', '87855ddf-ae22-43f2-ab49-c88aafc2ec38', '406465af-54e4-4666-9d46-029ec4793e84', '8273a07a-1845-445c-ac48-25dc6f59563a', '892e7f04-347c-466a-a6f4-d500057f13d6', '7ff46467-f17b-4dab-907f-ed63686611ce', '568a9fd4-2c67-4302-86a9-051fffe19160', 'b76c7e87-9a01-4f58-9e3b-c782cdf1cc47', '6244b0e1-1177-4975-ae26-fa1a5a5ece64', '258e7598-14b4-48dc-861e-d0170d7c8671', '71e3d707-b194-4bb7-8e5b-1c2f8bade9fd', '5dd9a323-260c-4689-aebf-0b551ba9a553', 'fb14bff6-5ef3-4bec-aa95-bcd7584e0dbb', 'cde675c9-df12-4f91-8796-e6054764000c', '6fdfe908-fadc-453d-acad-9e19bd84eaf4', 'c13caf20-d4dd-42e7-af97-c0effcb234d9', '350f6167-4406-459a-96d3-8d67f6e139a1', '3c6873c8-b271-46b3-be80-f386b95215af', '08a37bc2-527d-4125-aa35-589c4aa2191a', 'b8c1361e-d945-431f-9678-4484c7fb7335', 'e897dfd6-d482-4aa6-8a7a-d7ec7a8d7d2d', 'a0081350-3a7e-408a-84bc-e23bbc990f1c', '277741f8-316b-478f-83e4-f16ca3db4d55', 'd54d7b1a-c2cc-46a9-b1f1-cd927b097a87', 'e8c336b6-f843-4368-a248-bf913c8ff60b', 'dd6d7a10-c1d3-4cc6-932a-5a937de5952b', '6e262c85-6d18-440e-97e1-441d3edb5895', '07b121f8-e655-4c07-ac75-21aa478364c3', 'fbef56ba-f481-415e-b7b8-ca08c45b5ee2', 'ae6e0424-d847-462f-8453-408745f4b70a', 'd27b47b8-61bf-4728-a869-aecad7ab9ae6', '15e214ab-7230-4df9-beca-fce1c8c51f66', '2e88281f-a3e6-41e9-b046-23ec14af2ecb', 'b8de3ef6-f1e2-48af-897b-32d4f5725ccb', 'e9740f82-2c03-49cf-bd22-6665ee8d7f42', '128c0c89-71dc-461f-aeb9-9b2002c52cc3', '9ea90cc2-734e-4a4f-af0e-47db26e60f25', 'b564d367-182a-433f-87aa-86133a0dc835', '251b30f7-5db3-4f25-9040-6563d8855205', 'aa03faeb-7493-460c-87f7-0ce08a5b1dc9', 'fc0ff57a-5dd8-470b-a6e4-f3441ab7dbaf', 'a0025939-5b52-462a-8b43-e94d4915d385', 'a4e3b63f-60dd-47c9-b861-a655095d76bd', '545d8ace-0d1c-4757-b6ee-3dce25271361', 'd644b67f-0b19-4294-a384-5b91cf6b29b8', '435aa4b6-f4f2-4099-9a34-c842449437ea', '24230a7d-7d7f-40f7-92fc-0475318a6b31', '25daa479-a3bf-4f97-98b8-98e064141b74', '14c9b8dd-6aea-46ba-b03c-4460bb485a53', '07c5b451-2fd0-4162-9a14-5be4d7e8f7eb', 'b23b5597-61bc-42e6-a720-00a519551363', '9db4b1c9-7347-4adc-8d19-9a13256ab3fb', 'd3e57d2e-a9c2-48d5-8a4b-313aeb9d2d57', '8910d740-c017-4e2b-bee9-831317cd0356', 'fa52d9c8-1a24-43bb-9735-7bcf79c19436', '69706653-3e20-4030-a63a-cc50695cab12', '1731f0fb-7799-47a4-9d8a-c85250d61cd5', '08dcc4ef-6432-4025-b234-ba6aeb364f50', 'ac28a95d-d7c9-4dfd-b497-edc3137f863f', '183b1385-a856-4a40-bf3f-5e3d283c40bd', '25979893-37fa-4e5d-b076-a178049ed67e', '8d8df0fc-e81b-4fff-a244-594f0f73ac86', 'd13ed528-9a2d-4416-9e1a-4286c3d3f00c', 'c2e033aa-080d-4467-affc-4e6c5317473f', '4992f0af-05b3-4f74-b24b-2283c4032868', '80926f94-ce68-42a7-b88b-e4d24b12f8a1', '34d31395-5f5d-48cc-b367-67c69fbca158', '789f8369-3dcd-48f5-a021-d18e9a9fdcfc', '39659dc6-0114-49f6-80fc-878cd1beda6a', 'ad67742b-3748-4236-95c6-f376027d2e12', 'dfdd3ba6-892b-490d-8dba-41399dc5cbcc', '17037033-95d5-46e6-992b-c22476bba0d6', '27851481-5f0c-47d9-8d48-a2ee37eb360c', '90c0b0e3-233e-44d2-88f6-ad57c82f1f2c', '390baf58-64df-4c49-9f24-469200eba58e', '5ad56621-7b06-4a88-9fdb-f1ab83754b09', 'fe111261-17b0-4e76-9353-7285a2a5be9b', '60248e5c-78b6-4783-ad4c-6686829ecd53', 'b5e33393-e037-4e1b-9a92-c6e8368ac7a8', '8794ac15-a4c5-4f3b-ba9a-828b176a2779', 'ad7f5b05-46e9-46fa-b679-8703a4dd6b5e', 'b7fdc9a3-6028-47b2-b420-9c17367feeae', '871d707a-4e22-4f57-a8fb-d2490aa46bb2', '67493914-83d8-41ca-89c5-b51bcfecd440', '72c8cbdb-b1b4-4ce3-98e5-d681f20dcd95', 'bc95a1db-fc70-487c-b5c8-7c7ff6b0a6b9', '6805fec6-c9d4-4cb4-be30-9f44a0f14dae', 'd7fb61d2-581d-4fcd-96cf-7cea125b7724', '293cee68-5fc4-4bbb-b6c6-1204b15ed828', '6cc751b3-e0e6-40ce-954b-889225ca045a', '64ad2d90-b8cb-4053-9aa0-3c69b509bbbc', '10533fe6-db23-4e95-8780-fed40749d19e', '6dad3663-9710-42ca-83d0-ab1647b264a6', '976b2d0b-1e22-4e04-8c95-9667e1c9ae5f', '1b2037fc-c094-42c5-94b1-8f52cd363bbe', 'd3524aa1-079b-4639-90fb-42c90aef975b', 'e9860126-8e53-4db5-b7a3-1157ff59b4b0', '520d6585-0b6c-44e2-9716-5d9a0c9afd13', 'fba4e908-7eca-4e5f-80e2-7b11dd0ca79d', '27b536f3-9486-430d-9baa-1d85b49ef72f', '48c3dbb7-046b-4ebd-92cd-0151db682b62', '01fbfd58-da4a-4dc4-840c-5e0796a3204d', 'c87df9d9-74fc-4586-bb37-ec1f6f0276f9', 'a284ab68-934e-402d-8f21-78ca8cad5aa8', '23392ca3-a83c-49c1-815f-029209bb92a0', '44511b67-b314-49fb-9733-413b5bc55baa', 'b900066e-fce6-4d63-971e-5ad7d908771c', 'bfca01ec-1f80-4dd0-8ed4-2dfb3aec34af', '78dffc9b-8384-4a54-b677-e12595233d93', 'ba140463-4302-4673-a0d8-fe287bd259a7', '56ed77db-020d-4196-b9a0-ef0059af5de2', '21f1bbc3-6f1e-4383-bb4b-7f4429dfd28c', 'bf0253e0-3e13-49fc-8009-eee6ab6d8427', '9c6dc610-51f5-4377-93ae-037d4c61c22e', 'ec4e55c3-b269-455b-bf5d-e839d2379018', 'e6b778ce-832a-4ac0-ab5b-6b50e0bdb339', '13298900-9d07-49b9-99c8-388bcd64def2', 'dc4b6795-b316-47e5-b0bf-2c0ef769256d', '2475a112-e302-4dd4-bae6-dd120147f7aa', 'd331e2b4-70b2-4c87-a3e2-476a7033ece7', '2bcb9d3d-260e-41f3-bfc5-8828f163a96e', 'c2415793-f866-435f-a5cd-138516e5ff76', '492e204c-03a2-4eaf-a601-d8a400898e2e', '8f15fcc7-f57e-48d4-9f73-92a56e9c1494', 'abc2bcc8-57ac-4115-8f9c-dac0c6ac5f6f', 'a1d4a74d-c210-48d9-b148-7b3cb9e968d1', '88e783cb-e01f-4a91-a104-afc1d3cf9a4e', 'b8e73a85-74bf-4536-9648-518ad06e5270', 'ae14f85f-3ca1-447b-8be7-9b4a15028ecc', '5de8ed1f-f4e3-4fff-9655-7169644324b1', 'c1bb1f1e-2bda-44c3-b725-42b1eb491200', '3544747c-9c5e-4458-af95-ec631f63b798', '3549b59f-3296-41df-b434-5eaa5b612502', 'a5b8655f-8e1e-4ffb-9166-12027bdee9d7', '17b5a38b-979d-4864-8b1f-fd0aefd4c488', '4845cefb-4aa3-48bd-8bdf-e30dc9944a80', 'a8860b27-43a7-459b-a1f9-1f91fa44f726', 'cf7c6d06-5581-4db1-ae81-b8b5a3bf11b4', 'c52ba218-8afe-45a3-9195-ff1c6bc78113', 'd89e7173-f5f9-4161-b466-00385f556b74', '860d4571-40b4-4cbf-ac9f-024aa2bf991f', 'ed0705e6-9537-485b-aa8d-8d1784a45a19', 'c0c50843-0c3c-4de9-bd50-d9c9dfde02de', '10a07752-e10d-43f9-aa55-d850a075cd04', 'afabea47-e6a6-472f-81e0-1b1514dc768a', '4e3e9ee0-eb1d-468f-a78a-63c4214db447', '7a002c4b-197e-4576-abec-ff7451857e92', '712d335f-9c02-42c3-8ddc-072f681d2665', '39e6b8d9-dc55-46a9-b0c2-a4b32f7d9f6a', '3d4efc8f-5810-4c94-89a7-829f9cbbf5a9', '5b82fbb4-81c5-420a-8a2a-48c6b8603f08', '8006e957-aeff-435f-894d-74770b1c5c88', '4781a446-95ab-4325-968d-3408f16fa6ca', '62c51989-bef3-4ef3-9417-a6bed338f930', 'e4bc6b80-aa39-46fc-89f8-c381afd069fc', '35284025-5cb0-452b-af4a-6c74e83a8873', '75747395-f6a3-4414-92f0-e61695d089a1', '0cfaf55a-b34a-4195-8c3c-bcee17168494', '90e3f99b-18ab-4c62-b540-1f48abb053ed', 'e58983bf-c2db-4a60-92f6-eab9d6e35efc', '1c0e2a11-7a7e-4153-9965-d02a9c6546c0', '74e15de8-e032-4471-ac97-a743e2133056', 'e38089aa-31ec-49d0-981c-dc23a2acba12', '6f00f96b-9831-4352-bd1a-423bf184f10f', '3a00ef7e-60f0-440d-8fc9-44796b6fdb79', 'e7c096af-f34f-40d4-8e21-6d90640e6f92', 'ba9502ea-fde5-4473-b917-f4af937f55c0', 'fbd090aa-ee3e-47d0-8faf-b00ace46dcf3', '360395bc-61ee-4f55-8d9a-9e3a3b8f24bb', 'af23829f-98df-47ed-a141-0a939bbbe958', '679bbca6-14ab-4718-bbe4-e3715f9ca1ff', '70a09944-c8c8-4d47-90e7-15f36037f490', '7a36d3b9-4efb-46a6-be72-52615e8482ef', '2da3fe8b-ec3a-4b2d-9e22-72d997fae94c', '813a34ad-e70c-45b9-9738-d0dd4db5df47', '6df0e991-63ed-463e-baa5-f9890ba5b0a9', 'fc191b65-f1fd-42b5-95a0-d82519c7cbf7', '5974e16d-65b2-40c3-b8a7-69f1824604f6', '2a136041-0d33-4485-9d11-9a74833d44c5', '4fa7fccb-8065-4f4d-b55b-602085550549', '1af45850-8859-4add-8a57-069ce97971ee', '463901c0-41f9-4e92-9886-e43c67a18df5', '4e0b8e1a-320e-4649-93ae-0278797b5bc3', '21caa489-22e8-48c9-ae8d-43bd5751e371', '57de52f7-b9d3-472f-b411-dd8631133454', 'bf43dfa7-ad18-4edd-8eef-1d8740c208fb', 'ce0de164-2d41-4e04-9e34-9cd31cba1a9b', '04898d9a-57fe-4215-8ad9-c32b3f725d4e', '8f21518a-25a9-4ddd-856c-59caa1197a82', '5345fcc2-0976-4111-a231-cc22834dca3e', 'a2e6def2-1103-4176-bb47-1c13352278b0', '64aaa507-69cf-4de4-a0be-1c97e97deffb', '2a703737-04f7-441c-93ee-b3fcaa9a76d6', '7f3152f8-2868-4a66-94ac-bfbff1a91a06', 'c43cd1ed-6042-402c-8fcc-9bf2bf534b40', 'ab9ce13d-2e4d-4a2d-990f-c93aaa05ce01', '26f0f9c2-4a6f-4ebd-9909-4756cd925eaf', '24a2b2fa-4b07-4dae-8829-1fb497dc2034', '3f1aad3d-6ed8-441b-884a-acf2afb47af2', '366ef40a-2241-4852-a985-14f9ef616964', 'e9810289-b13a-42c4-9f29-580329281169', '734be1e8-f8af-4806-af96-b5ab788d051e', '5215eda2-0cb0-4008-94f6-9f6ee6d31d71', '03ba594a-2da3-4a3f-941e-be9006d12b02', '1e7006bd-d7ac-4dee-9a3e-1d50ae315d90', '41caa9d3-12e4-432b-8352-aa012905b823', 'd5720dff-ea39-4b45-9e45-b7459b779ee6', 'a2829968-97f2-48c8-bc0a-2989850aebf1', 'd75a9be9-7092-4915-8532-b75c99a885fe', '6b48b8b3-6848-4f2f-bc63-c2ccd7819948', '7e8f9b5f-0af6-4b8e-94e3-51027891dca0', '6b383ac8-f09b-446b-9366-c71090966909', '86aaca68-bc0d-4a3d-af47-13d9e8697ceb', '741aff6a-f326-4f82-a8ae-e1e15c8e2b1d', '9e281ea0-c0e0-4fb3-9393-1e8dab196faf', 'ae217759-04d0-4afb-8144-76ef58d1c88a', '82039365-4d2c-4dc6-8084-b2593d5fb8f4', 'ddbb6500-e453-4ad1-9d0b-874efbbea637', '58a68e43-cc40-4b5a-a4b5-5fe9fe73efd1', '8253b307-b67d-43c7-a7b0-583e3b2d4fa4', '9d5e3916-f176-441b-ade1-b87e654b6bd8', 'e5977adb-da4e-4118-b299-7d55a22c3a2d', '3ab95812-0556-40ca-8c6c-4af2e7b5dbad', '925030d5-7e07-46e1-9b0a-8884f9af6d1f', 'cc72dd8f-ecd1-4c98-b855-dd38f91373f6', '14042fd5-f422-4e3a-bace-aa7cdaa0a34e', 'b02f374a-fe0e-4e2f-bdaf-99692c8f54e8', '15ce48c3-9ec3-4a35-9baf-225979bde0ca', 'f9e6c413-6104-4f58-b271-6d93176d5e90', '8927001f-bd1e-4346-b4b0-a71a09e9265b', 'abaee28a-67ce-4395-802a-51a55c56e008', '019a509f-0f52-44bf-9261-0b1787e1d465', 'b9cbbebb-4c71-49f4-a188-ff90d5cb1625', '846cf3f6-1dd4-478c-9a94-ecfeee9b0ba1', 'c989a9bf-8f4e-42b0-be38-f43bd0cc1164', '6c2adc05-75db-42be-8459-9c4fcf139640', '90efed61-4b63-41a2-8541-7b8926f33609', 'cc1cd692-aab5-4229-a187-e750ebc83690', 'b47267c2-2c2b-425a-aba6-d54fdc2a859f', '2e96eb21-aea8-40f1-a103-2dd8a2b3e40d', '653f73bb-d5f1-40a4-bc5a-b241d90cc26b', 'dccaed53-078f-41b5-aab1-e1c4416775f0', '618d5f0f-9553-4493-b828-f79504844c93', '51b53f2f-4fb8-41e9-993d-5060142e994b', '81c8776e-935b-48fa-8f13-e34a20863e5b', '761f70d2-bdac-4c3d-84fb-a78721172204', 'fd419f04-169c-46af-8391-c521f6d096bd', '1a189de9-af4d-4780-8335-35090a2e80f2', '9ce7a8a6-5cc7-4af9-bc3d-5f4e77ca16d5', 'ae77a2f3-84b3-444c-85ac-43d7c3d09148', 'd5316f99-5de7-4b9d-8bc4-d94da9a2ae57', 'b6584735-d941-4013-a7ff-16a1fb75513d', 'c64a2c79-a446-4781-8273-a2e4cbf8658d', '61e0caba-7857-4934-8147-6d9f893d76a5', '4446c49c-f182-4b5a-a18e-627d1dde4577', '391abb76-b999-43a3-a60b-f7f5f2d2ce39', '8814e46e-2aa5-444a-bc2a-e6f41781b14a', '0ff16338-11c9-4896-a9cd-094b5f68f46b', 'fcf102c7-88b9-43fc-aa75-72e57ca9da58', 'fc56d72b-e398-45e4-952c-0d3b6c620e7d', '83a149aa-5025-4f80-a3a0-b88a4fd60be7', 'd9080585-5e41-4047-a7db-011724b52787', 'f80b691e-20e0-48f0-ac83-3114659bdd9d', '1de0fcb3-27e5-47a9-9eae-009a7505eed9', 'a3e2f32d-3bbc-4c9a-b3e3-3ee3bbccc63e', 'cf61676c-44ed-4b3e-a1cd-b12baf1dac14', '36c45051-b63a-4661-bad4-dc44eb9cd66d', '602a1aff-50a9-45c1-97e6-b7320d035e79', 'face5af5-1fa1-458a-8d6f-181ad63f816a', 'cb3e2921-b3ac-4b3f-aec5-47707b866977', 'af90923b-280f-4585-9e3a-20a00c3f5f24', 'f1ea73b7-08ea-4aaa-ac06-b069144663b0', '35435f00-fb90-41f5-9a08-bdd17e48a041', '238c6174-3fd3-480d-b1c8-2d16b22e3b74', 'e61883ab-bdc9-4a37-83d4-f9b573a62e7a', '68eaee39-7f50-44cf-802a-e1a3157f2673', 'a7537652-3d57-4b5b-84fc-20061baafb00', '4b024c46-d03b-49ac-90fe-d796da57d340', '7ae02790-c0f6-45f6-ae49-3b80cbce610b', '8eabc7d7-6ea2-4b25-a63b-890286897dbe', '78690b19-e60d-4a64-aca9-386f26185593', 'd43328d4-1f70-4165-b81d-9feb9c5c6d7a', '039cb815-da81-4907-a1c0-36db00c0b297', '04cbfe8e-f44f-45cb-8ede-0b092c85397f', 'bc44f5c2-e728-4b0d-854f-8797af607f30', '2b211502-3946-4a74-8f2c-c62b483710af', '2321efeb-9dee-411d-8e20-9832cfec653d', 'df47dbac-808e-43af-ba30-749a6e763134', 'e8d78447-0d81-42f9-a4d6-1f7fcad9ed22', '72d98900-b63e-477e-8ac6-04414774e6c8', '855aeafb-a170-4365-b055-4c0fdc902379', '77fd1e42-a602-4d7e-8105-c037f279a5e4', 'd627d5ad-d847-4e95-8ba6-a6ff2ebe8c16', '10c894bd-01e0-4be0-be41-810f45b13eb1', 'b0869c09-df3f-4acc-8301-76ace1ea5455', '9d1d7bec-3e59-4cc3-9565-4e78777a9dca', '4e73cf8e-f4fd-432b-a5b3-83349905c0f9', '60844f28-b607-46a6-8e21-7ed87922459c', 'd30ec314-b75c-4644-a1ff-f36d371a438a', 'efb23f33-7f72-4b41-801f-405f1c5a0c9f', 'f75df6e2-cea2-4a71-8321-98871793801c', '4fe47a82-4bb6-437e-81fb-dff27a80ebf4', 'a18c4f8a-2d33-4bc9-adee-8c105b54f34a', 'ea466985-009d-4951-87c0-1dcd651ceb94', '9c43d40d-198e-41e7-a300-1ec06d12cd0c', '4102a70c-0bea-4444-9a36-ee97164b6538', '96c9a044-59be-4aba-acea-ea475d6636f1', 'f764ab64-71a2-4019-b70f-f590df32bb3a', '0a0c8ec3-7171-4154-bf9c-1ac457d71ad1', '2f54e8d2-d663-4927-8789-13d98736666f', 'c3957bad-73f3-468d-9709-7f7ecf4bfad1', 'd7ab50a4-6f76-4c11-a00b-ba734b4ad2e4', '851e509e-6dfd-4a43-9a2e-994b27983cd3', '8dd918fb-4d1a-40ae-b1ee-cf91f5dbe527', '3bfcfdf8-8db6-4975-b1e0-7ac8140879e9', 'e57cfa7b-09f8-471c-85cd-5f70dbfa1e4f', 'a5ba03b5-7a53-4041-90af-61976b3697c9', 'bac89eba-5f89-40bf-8b65-b95f7ff2c2d5', 'daabeea7-5471-41dc-a247-334fe077aca1', '9d3f9daf-76af-471a-9881-9398aab38293', '160c2b90-e644-4db6-8cfc-36f99993dab0', '4c725c00-e145-4982-8c7b-2d81556dd776', 'd9f57374-3c89-4d09-8171-112f1030c62f', 'cab80713-d591-4d58-a1ce-98bdfe4f75bc', 'bce1b712-09d4-4fd7-9d31-20c945c9fcf8', '044d5da4-8fd9-428f-acb4-f1afcc4b7312', 'd757772d-e2d8-4061-9957-2589dcde07be', '8e3f3734-d60c-4716-8c36-6bff6eb9acd9', '9296c55c-8ca8-46fa-a26b-2e86aee3d35e',
                  '0ceabd5e-57d4-4b48-a0f3-0130457f023f', '48e3fdb7-7b70-4d3e-bfc6-d65ad4428f18', 'd12ce4d0-a353-4cae-9fb2-303dd68f2f8f', '2bc869c4-d0b6-44c8-9644-361a2c905d29', 'a35d3e12-8981-49cd-b9ea-e1baa0d3deb6', 'ec22410e-2bd7-4c03-83ca-06cb412069bb', '2f3d7adf-f315-460b-a795-d14681adc50e', '3c6eb659-bb75-450e-ae32-f58d2f363dde', '1c9bd6d1-7ef5-4d6f-9521-e085951709e6', 'b2587977-5313-417c-a592-96ff364f65c2', 'e2727333-bad1-4413-a8cb-69b17db15e48', '652f1171-b50f-47e6-9ecd-20767265fe2b', '397db33b-ddf1-4d5b-bd50-a77e03ed2cb3', '12a92802-a0dd-4185-a6ee-06b8ecfffbf2', 'abe3a84f-c75c-465d-a8dc-67524d9731d4', '084c118f-340f-4b88-bd30-a6dc90e9a66b', '62d75802-46c4-4e10-aece-2258a504c6c8', 'a0002ce4-2515-4860-b3ce-9bebb6f25078', 'b30698c5-4149-43b7-8ae4-0b52429ca689', 'e164570c-bcfb-43b9-bb21-24b6f2220edc', '32e7b936-72af-4cdd-9bc5-2a51d962436d', '6935e257-61bf-4838-b391-aadbb693df1a', '1bfccdb4-9f3b-4c72-90e1-952a06c536a9', '7129c71f-5870-4fd1-8b37-4baa34e8bfb6', '367fab93-6237-42d4-91d3-65ce4f6565db', '3b965f6a-f2c7-438b-83c1-224cf43b534c', '8cb9ccd6-16e8-4238-8fd8-c86f3b5652ae', 'e49fb6f7-c276-4f8c-bd30-38421282bd04', '79d46e4d-da2a-4d2c-a0ed-c1ab96093513', 'aa471654-f008-4ef4-ad30-d6c9b9b78f23', '21b4b829-2d16-4b6b-bc6f-d76a37d3aca8', 'f1690b52-e822-4239-a109-ee54e6bbad04', '6b9801e0-2454-4cf1-bf4c-2e4bce21f1a0', '97948e41-9824-46f5-8e5f-c487f7a66f31', 'd94c92c5-094c-43e6-a1b3-ea374951cfc4', 'd2daf6bd-8f4e-4346-935a-30c408263eb0', '02143ca5-ade5-4d79-a212-0b80193d1a90', 'd62db1ce-08d3-44d0-be48-deb105c21d2b', '31eec86e-33fe-4376-b4ed-bd2c99222361', '972667a4-fa46-4dd7-8063-d54e396b6892', '21c012a4-01c4-44e1-9d21-dbbbd3d099ed', '86717383-b814-4c1d-b58b-a6f3bc5c4ae3', '8b915c5e-360b-4a9b-b17b-162e35c95900', '3b75205c-ee1b-46d1-a8a0-7352efbd7a49', '0110d716-86bd-4966-8b30-e5051fe7e4e1', '201d53ad-7028-4c72-b93f-00ed7318d6e1', '1cbae569-6583-4602-b7b7-53620d0c0b6e', 'fccfb5b7-76d5-42c0-af49-8f3b3c0b3ded', '48d3ee34-127e-48cd-9568-5af318312b0e', '8e6e14bb-8e22-4561-bce2-d50e07b63e70', '0a7639bf-0589-443e-8a18-798ac96cfc29', '084e2a20-531c-41ff-a3e0-a484b37cfa70', 'eb86c720-fa90-45ae-9bfa-b8383a21fcc9', '4303dc88-ec36-487f-afaa-33bd536eb8a0', 'bbb7a492-ff4e-4f60-ba58-347b2db94b4b', 'fcc8a3c3-5fa1-46b3-b8f3-6c8fe3bc936f', 'ded29475-c45e-41e1-9f9c-d4a59654bafc', '1f38df10-4ed2-4cc7-9da7-c2841649c9a1', 'b7240333-1610-4d40-8790-1e6fe50ff8ac', '66f52458-2531-4700-a6cd-a08ec80f3849', '1e262c3b-65ba-4dee-bd2a-2757820729e3', '71323ce1-08b0-4d71-969a-890160b696aa', '213da5b5-7198-4adc-9861-078e4c8c6368', 'eda5e9b5-b244-4997-8fe9-1647bb0fb021', '0a3f4ec9-df33-4d81-bb93-58deebbfa3ba', '9dce9d67-baa1-44fc-bd33-0bd5dfa0d3d8', 'c058934a-6b57-4560-8b56-67dac7ef0579', '3e8b0afb-c7ab-434d-a89d-197adea9ad1a', '25eff424-4b8b-4b6c-935a-0b32f3c933d5', '5500cd67-1052-4882-9183-db3278ce9079', '4c390768-f61e-4929-8495-0ba2a4495ad3', '92118a4a-afe1-44e0-ae63-e9486b8ba1ea', '2cf4f328-ea1a-434e-ba83-44cd0fb421da', '1e86a172-8a81-467f-a208-692da5ade7a1', '3d03750d-2cd5-42af-bf4d-4c1aca4b8b97', 'ec141396-83c6-4ff6-bd32-34041466b35f', '5b9a067a-639e-428f-b2b6-508a15414ef5', '0e6bf139-40db-4e32-8280-55d5f8acbf2a', 'bf7c3142-c326-471d-baa6-9f8ee4aa460d', '60861ad2-7b59-4f2a-9a25-b0b4cbfd959e', '917782c1-b378-414b-ae3a-4e49954e04e5', 'ebb43a80-13c5-4255-b772-9fffb4222c1e', '458d5770-340c-4750-b7cd-4fada37ed0e0', 'd5865b1f-2278-43ea-bd8a-7ce0450d105b', '0914dc3d-7d99-4ca9-8e75-a0f004b5aa3a', '6c81db7f-0c23-40f5-94c2-5a610737527e', 'b94ca386-a43b-4b3c-92f5-e1b1b838757a', '0bda1472-af7c-47aa-92d4-760c32ed18d0', '4e48a56c-efbe-478b-a3f4-0835308cf344', 'fc2ae059-042a-4a69-9946-fcec4590be6a', '0663733f-9215-420f-8cbf-95f86be1107d', 'de6d9b9c-4bf7-4408-a1c0-3dd66aa38ab6', '349c414f-7509-4df4-beb3-e4e73aa068b4', 'bd9d1f04-7009-4c36-a323-0c2e129a823e', 'a6c9e53c-2141-466e-a85d-888de92fbad3', 'b6411e00-2ba7-4fde-ae28-d338c533f8e0', '2fadf567-27c9-4850-b467-fe4077916330', '487ad49a-ae59-450c-ab9a-e1f121735339', 'c2441884-40f3-4297-abac-ba1bc32d54f3', '57aa4381-2729-4b9d-9f6b-ffbe9ae14d58', '10052303-e9a3-4e80-83ed-1746beb5a9eb', '2cab1cbd-27a7-4cc2-84a6-0a26307f5c83', '813cb709-7c3d-43cb-9c11-ced9129f2fe3', 'da538e4c-320a-48cc-ab92-89e530bf59d2', '0eb22b37-7a79-4e5a-8b78-e38e7b9c6f6a', '2fd35e47-5c60-4bd5-9b43-fa54b2f4fde3', 'f059f0ec-e8b5-4719-9dda-58886ad31e32', 'ea04ddcc-9462-46e5-b2b2-184fcde2b8c6', 'd28edbd2-ee3f-4a9f-a0a6-17ad0e8b176a', 'a7165df8-6f62-4fb1-b047-1eef10c3b029', '2a4d316a-86c6-40ab-89bf-c795bc50d2b5', '45c301b3-7995-4de2-9ff6-55613e6cb9f1', '3d76edfb-44fc-4d2d-9e53-9226f2af5a64', '6aaf4e00-d489-4bdd-815b-54bd367efb55', 'de07abec-6c49-4ff0-8dae-8c59df1b4144', '758a45dd-5ee4-4e90-b6e4-3b438bcfd4df')

In [43]:
length(selected_ids)

[1] 512

In [44]:
setwd('/home/jupyter/')

In [45]:
getwd()

[1] "/home/jupyter"

In [46]:
cusd_final <- filter(cusd, file.id %in% selected_ids)
dim(cusd_final)

[1] 512  32

In [47]:
all(ra141 %in% cusd_final$sample.sampleKitGuid)
all(selected_ids %in% cusd_final$file.id)

[1] TRUE

[1] TRUE

In [51]:
ss <- getStudySpaces()
ss[[3]]$name
ssid <- ss[[3]]$id

[1] "Authorization token invalid or expired."
[1] "Retrying..."

[1] "preRA cross-sectional + earlyRA + Longitudinal analysis"

In [56]:
write.csv(cusd_final, 'CU_SD_512scRNAsamp_duplicatesResolved.csv')

In [57]:
desc_file <- '/home/jupyter/CU_SD_512scRNAsamp_duplicatesResolved.csv'
desc_file

[1] "/home/jupyter/CU_SD_512scRNAsamp_duplicatesResolved.csv"

In [60]:
uploadFiles(
  files = as.list(desc_file),
  studySpaceId = ssid,
  title = '512 CU-SD Sample Metadata',
  inputFileIds = list(c("bff40a9d-15ba-4af3-b277-bc94a53765f0")),
  destination = '512_CU-SD_Sample-HISEDescriptors',
  doPrompt = TRUE
)

[1] "Cannot determine the current notebook."
[1] "1) /home/jupyter/01-Python_label_predictions_celltypist.ipynb"
[1] "2) /home/jupyter/readFiles.ipynb"
[1] "3) /home/jupyter/02-Python_doublet_detection.ipynb"

Please select (1-3)  2

You are trying to upload the following files:  /home/jupyter/CU_SD_512scRNAsamp_duplicatesResolved.csv

(y/n) Y

$files
$files[[1]]
[1] "/home/jupyter/CU_SD_512scRNAsamp_duplicatesResolved.csv"


$traceId
[1] "bd3f2511-39fa-4a63-abc7-99a3bd87afd1"