# Assemble subset .h5ad files

For QC and inspection of our cell type labels, we'll assemble samples based on subject metadata to get some reusable units that will be manageable for downstream analysis. 

To each of these subsets, we'll add our cell type label predictions and scrublet scores and calls.

We'll carry these subsets forward into QC filtering and cell type-based doublet and mislabeling clean-up in later notebooks.

## Load Packages

`anndata`: Data structures for scRNA-seq  
`datetime`: date and time functions  
`h5py`: HDF5 file I/O  
`hisepy`: The HISE SDK for Python  
`os`: operating system calls  
`pandas`: DataFrame data structures  
`re`: Regular expressions  
`scanpy`: scRNA-seq analysis  
`scipy.sparse`: Spare matrix data structures

In [1]:
import anndata
from datetime import date
import h5py
import hisepy
import os
import pandas as pd
from pandas.api.types import is_object_dtype
import re
import scanpy as sc
import scipy.sparse as scs
import numpy as np

## Helper functions

In [2]:
def cache_uuid_path(uuid):
    cache_path = '/home/jupyter/cache/{u}'.format(u = uuid)
    if not os.path.isdir(cache_path):
        hise_res = hisepy.reader.cache_files([uuid])
    filename = os.listdir(cache_path)[0]
    cache_file = '{p}/{f}'.format(p = cache_path, f = filename)
    return cache_file

In [3]:
hisepy.__version__

'0.3.0'

In [4]:
def read_csv_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = pd.read_csv(cache_file)
    return res

In [5]:
def read_parquet_uuid(uuid):
    cache_file = cache_uuid_path(uuid)
    res = pd.read_parquet(cache_file)
    return res

Functions to read pipeline .h5 files as anndata

In [6]:
# define a function to read count data
def read_mat(h5_con):
    mat = scs.csc_matrix(
        (h5_con['matrix']['data'][:], # Count values
         h5_con['matrix']['indices'][:], # Row indices
         h5_con['matrix']['indptr'][:]), # Pointers for column positions
        shape = tuple(h5_con['matrix']['shape'][:]) # Matrix dimensions
    )
    return mat

# define a function to read obeservation metadata (i.e. cell metadata)
def read_obs(h5con):
    bc = h5con['matrix']['barcodes'][:]
    bc = [x.decode('UTF-8') for x in bc]

    # Initialized the DataFrame with cell barcodes
    obs_df = pd.DataFrame({ 'barcodes' : bc })

    # Get the list of available metadata columns
    obs_columns = h5con['matrix']['observations'].keys()
    
    # For each column
    for col in obs_columns:
        # Read the values
        values = h5con['matrix']['observations'][col][:]
        # Check for byte storage
        if(isinstance(values[0], (bytes, bytearray))):
            # Decode byte strings
            values = [x.decode('UTF-8') for x in values]
        # Add column to the DataFrame
        obs_df[col] = values

    obs_df = obs_df.set_index('barcodes', drop = False)
    
    return obs_df

# define a function to construct anndata object from a h5 file
def read_h5_anndata(h5_file):
    h5_con = h5py.File(h5_file, mode = 'r')
    # extract the expression matrix
    mat = read_mat(h5_con)
    # extract gene names
    genes = h5_con['matrix']['features']['name'][:]
    genes = [x.decode('UTF-8') for x in genes]
    # extract metadata
    obs_df = read_obs(h5_con)
    # construct anndata
    adata = anndata.AnnData(mat.T,
                             obs = obs_df)
    # make sure the gene names aligned
    adata.var_names = genes

    adata.var_names_make_unique()
    return adata

In [7]:
def element_id(n = 3):
    import periodictable
    from random import randrange
    rand_el = []
    for i in range(n):
        el = randrange(0,118)
        rand_el.append(periodictable.elements[el].name)
    rand_str = '-'.join(rand_el)
    return rand_str

## Read sample metadata from HISE

In [9]:
in_uuids = []

In [10]:
## sample_meta_uuid from previous step
sample_meta_uuid = 'cb01d5b1-40d8-4940-b61c-86d78de4528b'
sample_meta = read_csv_uuid(sample_meta_uuid)
in_uuids.append(sample_meta_uuid)

We only need to keep some of the metadata columns that pertain to cohort, subject, and sample. We'll also keep the originating File GUID to help us keep track of provenance. Let's select just these columns:

In [17]:
sample_meta.columns.tolist()

['Unnamed: 0',
 'lastUpdated',
 'sample.id',
 'sample.bridgingControl',
 'sample.sampleKitGuid',
 'sample.visitName',
 'sample.visitDetails',
 'sample.drawDate',
 'sample.daysSinceFirstVisit',
 'file.id',
 'file.name',
 'file.batchID',
 'file.panel',
 'file.pool',
 'file.fileType',
 'file.userTags.details',
 'file.userTags.group',
 'file.userTags.name',
 'file.userTags.origin',
 'file.userTags.other',
 'file.userTags.version',
 'file.majorVersion',
 'subject.id',
 'subject.biologicalSex',
 'subject.birthYear',
 'subject.ethnicity',
 'subject.partnerCode',
 'subject.race',
 'subject.subjectGuid',
 'cohort.cohortGuid',
 'specimens.specimenType',
 'specimens.specimenGuid']

In [18]:
set(sample_meta[ 'file.batchID'])

{'B053',
 'B060',
 'B063',
 'B093',
 'B094',
 'B096',
 'B102',
 'B128',
 'B130',
 'B132',
 'B138',
 'B144',
 'B148',
 'B161'}

In [19]:
keep_meta = [
    'cohort.cohortGuid',
    'subject.subjectGuid', 'subject.biologicalSex', 
    'subject.race', 'subject.ethnicity', 'subject.birthYear',
    'sample.sampleKitGuid', 'sample.visitName', 'sample.drawDate',
    'specimens.specimenGuid','specimens.specimenType',
    'file.id', 'file.batchID'
]

In [20]:
sample_meta = sample_meta[keep_meta]

## Read labels and doublet calls from HISE

In [21]:
## search_id values from previous steps
label_search_id = 'silicon-californium-cerium'
doublet_search_id = 'magnesium-osmium-arsenic'

search_string = '|'.join([label_search_id, doublet_search_id])

Retrieve files stored in our HISE project store

In [22]:
ps_df = hisepy.list_files_in_project_store('Dyna_IHandA')
ps_df = ps_df[['id', 'name']]

In [25]:
ps_df

,id,name
0,0180d34e-bcb4-4b81-9214-818641ec54e3,AIFI-2024-02-05T23:47:28.925924866Z/br1-br2_cl...
1,223b4aa9-19fc-41e1-8bea-43682e5ac278,AIFI-2024-02-08T21:29:39.75691749Z/ref_h5_meta...
2,dca28828-3485-420e-872e-fee33d1898cb,AIFI-2024-02-09T23:39:41.138930843Z/EXP-00776_...
3,c945e0c5-4bfd-4b18-a990-d496252d5de7,AIFI-2024-02-10T06:30:21.185363381Z/ref_subjec...
4,cf3a852c-3222-4004-9144-30d43680ef2b,AIFI-2024-02-10T06:30:28.260682402Z/ref_subjec...
5,7184a685-7b0a-4edc-8730-f821277d9375,AIFI-PSP-2024-02-13T00:15:54.372169127Z/EXP-00...
6,d3ad68f3-b43c-4c6f-992c-8877b14d08f6,AIFI-2024-03-14T19:57:18.196621831Z/diha_AIFI_...
7,7df0f24c-a764-4473-bcb5-180022e85a4c,AIFI-2024-03-14T19:58:19.322053234Z/diha_AIFI_...
8,0b126dd5-7a35-4f86-85a8-6af37a4e1842,AIFI-2024-03-14T22:33:45.917841335Z/diha_AIFI_...
9,546d0304-714c-4244-8899-a665283eec2e,AIFI-2024-03-14T22:33:51.869481839Z/diha_AIFI_...
10,1e147809-919c-4ffa-a442-cc8f2807174c,AIFI-2024-03-15T16:04:24.371403102Z/diha_AIFI_...
11,ede79db5-ada9-4f6f-a0ce-460f8e5e36b3,AIFI-2024-03-15T16:04:30.577114541Z/diha_AIFI_...
12,da1a4e3a-24c1-453a-8b08-19ee56c0c597,AIFI-2024-04-24T18:51:13.44077624Z/SF4_CMVStat...
13,28fac788-8707-4329-988d-88d89e22c7c5,AIFI-2024-05-07T22:07:43.223096925Z/BRI_BR1_BR...
14,9034d426-6447-4c3e-b9ff-4ca3e814a15f,AIFI-2024-05-08T22:52:37.768043221Z/AIFI_pbmc_...
15,ff8878a6-bd90-4183-8554-4bb24032df44,AIFI-2024-05-09T21:48:31.723281555Z/BRI_BR1_BR...
16,aca65fc2-c9b1-46c5-b700-0c759193f132,AIFI-2024-05-12T20:45:53.942484193Z/meta_data_...
17,b0672a9c-3137-4522-bd60-224867ee912e,AIFI-2024-05-12T20:50:10.364785182Z/meta_data_...
18,0157dda1-6b00-47ce-b9ec-72fc9ead8fc8,AIFI-2024-05-12T20:54:28.518828059Z/Color_Anno...
19,408f8fb0-ac2e-4ae3-a6c0-7b2e79e47391,AIFI-2024-05-17T03:11:11.144139522Z/SF4_meta_d...
20,12707797-5716-4d1a-8cca-843c38aae03c,AIFI-2024-05-20T17:37:20.489915641Z/meta_data_...
21,4d343cf0-07f7-4e39-9301-cc2898369a0d,AIFI-2024-05-20T18:20:47.633875525Z/diha_categ...
22,df68e382-a14e-4d86-b5c8-25963c084a54,AIFI-2024-07-11T03:39:26.135923016Z/MSD Recent...
23,3dd84f81-4392-4f66-996a-335975e9b40e,AIFI-2024-07-11T15:36:17.470438438Z/EXP-01111 ...
24,f283bb9f-ba64-4e82-a253-851a823d373a,AIFI-2024-07-11T15:37:20.295976259Z/IHA_01089_...
25,c90dcc54-f8c5-4132-87dd-7fb1ffe2700c,AIFI-2024-07-11T15:54:29.198331354Z/EXP-01111 ...
26,00ccd84d-68c1-494b-82b2-f293b5fe19af,AIFI-2024-07-11T15:54:34.906027369Z/EXP-01111 ...
27,bb2e2294-a5d1-4305-9028-bf2844fa5a4b,AIFI-2024-07-11T15:54:38.180084574Z/EXP-01111 ...
28,c31a8867-b823-4693-b541-9395032ef502,AIFI-2024-07-11T16:01:22.212436797Z/EXP-01111 ...
29,e7be843a-0cac-4308-888a-adc03a3edc07,AIFI-2024-07-11T16:01:27.316269985Z/EXP-01111 ...
30,b25dd445-3e04-4086-83b9-c0851db2fd38,AIFI-2024-07-11T16:01:30.491655538Z/EXP-01111 ...
31,93837e91-cd3a-48cc-9cab-d59f0054b7cd,AIFI-2024-07-11T16:08:57.510443234Z/HAI_pilot_...
32,b5b658c9-79c6-4978-b6d4-41356af8f63d,AIFI-2024-07-11T16:09:02.241499458Z/MSD_HAI_Pi...
33,96652b13-591e-41d8-88ee-d3b4efeb9305,AIFI-2024-07-11T16:12:02.994624515Z/MSD_HAI_Pi...
34,14f0482a-cd85-455d-a1cb-8d8d2b014acc,AIFI-2024-07-11T16:12:07.365223053Z/HAI_pilot_...
35,4e057794-f0b2-4ce7-9154-64ad1a34b359,AIFI-2024-07-11T16:17:39.123179069Z/HAI_pilot_...
36,76971c3d-f6e1-4549-824c-0930e7d86787,AIFI-2024-07-11T16:17:42.325444732Z/MSD_HAI_Pi...
37,63d470e3-b826-47e1-ae13-327b777ce936,AIFI-2024-07-11T16:19:50.448208899Z/MSD_HAI_Pi...
38,a9c22887-e3b1-4e09-bce2-70f813085728,AIFI-2024-07-11T16:21:27.702901312Z/MSD_HAI_Pi...
39,65bac66d-b112-4759-bf83-9dc86fe9244a,AIFI-2024-07-11T16:21:43.082373545Z/MSD_HAI_Pi...
40,8f64272d-5ff7-4b06-9212-4f9713fba3fe,AIFI-2024-07-11T16:23:38.653836146Z/MSD_HAI_Pi...
41,9c100dc9-60a7-4b98-90e7-69277b451c36,AIFI-2024-07-11T16:25:28.39063145Z/MSD_HAI_Pil...
42,87b6988c-a6e6-4dae-ac93-19706473c39a,AIFI-2024-07-11T16:27:40.295431004Z/EXP-01072 ...
43,54c99b71-bfa0-40d4-bb64-87bdab8b5d95,AIFI-2024-07-11T16:29:57.548634559Z/EXP-01072 ...
44,d0586978-716c-4df6-9b09-7d8d9f9d5a78,AIFI-2024-07-11T16:30:02.473228489Z/EXP-01072 ...
45,d2d62fc4-0c42-4061-a4f0-6c04aa73c2cc,AIFI-2024-07-11T16:30:09.447844645Z/EXP-01072 ...
46,05c17621-df0d-4fdf-b97a-cdfd1bb46982,AIFI-2024-08-12T19:02:41.970707897Z/diha_categ...
47,cb01d5b1-40d8-4940-b61c-86d78de4528b,218_UP1_Sample-HISEDescriptors/allUP-SDsamples...
48,797138f7-50ac-4230-b2b8-35805578c49a,silicon-californium-cerium/ra_celltypist_AIFI_...
49,041ef46f-483d-4a3d-900c-64c97072da7c,silicon-californium-cerium/ra_celltypist_AIFI_...
50,cebba0b4-23b8-4fb9-97b2-a41686f2cf00,silicon-californium-cerium/ra_celltypist_AIFI_...
51,a5300b3e-4739-47be-8fc0-cb1039ff710d,silicon-californium-cerium/ra_celltypist_AIFI_...
52,ed3c5bbf-376e-43d5-9b00-cefb7de09ca8,silicon-californium-cerium/ra_celltypist_AIFI_...
53,5942d3fa-9efe-43e2-9e48-81b6cecdf089,silicon-californium-cerium/ra_celltypist_AIFI_...
54,a4e6ffa1-972d-4cdf-82e8-57a592b40505,magnesium-osmium-arsenic/up1_scrublet_results_...
55,e7c9a970-5075-4af5-a797-403b03848019,magnesium-osmium-arsenic/up1_scrublet_results_...

Filter for files from the previous notebook using our search_id

In [26]:
search_df = ps_df[ps_df['name'].str.contains(search_string)]
search_df = search_df[search_df['name'].str.contains('.parquet')]
search_df = search_df.sort_values('name')

In [27]:
search_df['name'].tolist()

['magnesium-osmium-arsenic/up1_scrublet_results_2024-08-16.parquet',
 'silicon-californium-cerium/ra_celltypist_AIFI_L1_2024-08-15.parquet',
 'silicon-californium-cerium/ra_celltypist_AIFI_L2_2024-08-15.parquet',
 'silicon-californium-cerium/ra_celltypist_AIFI_L3_2024-08-15.parquet']

In [28]:
search_df

,id,name
55,e7c9a970-5075-4af5-a797-403b03848019,magnesium-osmium-arsenic/up1_scrublet_results_...
49,041ef46f-483d-4a3d-900c-64c97072da7c,silicon-californium-cerium/ra_celltypist_AIFI_...
51,a5300b3e-4739-47be-8fc0-cb1039ff710d,silicon-californium-cerium/ra_celltypist_AIFI_...
53,5942d3fa-9efe-43e2-9e48-81b6cecdf089,silicon-californium-cerium/ra_celltypist_AIFI_...

## Read and combine label sets to simplify merges

In [29]:
label_list = []
for uuid in search_df['id']:
    res = read_parquet_uuid(uuid)
    res = res.set_index('barcodes', drop = True)
    label_list.append(res)

In [30]:
all_labels = pd.concat(label_list, axis = 1)

In [31]:
all_labels = all_labels.reset_index(drop = False)
all_labels.head()

,barcodes,predicted_doublet,doublet_score,AIFI_L1,over_clustering,majority_voting,AIFI_L1_score,AIFI_L2,over_clustering,majority_voting,AIFI_L2_score,AIFI_L3,over_clustering,majority_voting,AIFI_L3_score
0,b9993ec4872b11ebb599de5a8c2059ae,False,0.060170,T cell,70,T cell,0.997307,Proliferating NK cell,70,Memory CD4 T cell,0.027022,Memory CD4 Treg,70,CM CD4 T cell,0.999993
1,b99942fc872b11ebb599de5a8c2059ae,False,0.013071,T cell,22,T cell,0.999338,Memory CD8 T cell,22,Memory CD8 T cell,0.955047,KLRF1- GZMB+ CD27- EM CD8 T cell,22,KLRF1+ GZMB+ CD27- EM CD8 T cell,1.000000
2,b9996f66872b11ebb599de5a8c2059ae,False,0.120700,T cell,142,T cell,1.000000,Naive CD8 T cell,142,Naive CD8 T cell,0.984279,Core naive CD8 T cell,142,Core naive CD8 T cell,1.000000
3,b99971c8872b11ebb599de5a8c2059ae,False,0.018831,Monocyte,23,Monocyte,0.999258,CD14 monocyte,23,CD14 monocyte,0.997393,Core CD14 monocyte,23,Core CD14 monocyte,1.000000
4,b9997290872b11ebb599de5a8c2059ae,False,0.026079,Monocyte,46,Monocyte,0.999999,CD14 monocyte,46,CD14 monocyte,0.999497,ISG+ CD14 monocyte,46,Core CD14 monocyte,1.000000

## Define subsets

In [33]:
len(sample_meta)

218

In [36]:
subset_column = 'subset_grp'

grps = ["set1", "set2"]

num_repeats = len(sample_meta) // len(grps)


assigned_values = np.repeat(grps, num_repeats)

np.random.seed(202405)
np.random.shuffle(assigned_values)

sample_meta.loc[:, subset_column] = assigned_values

In [37]:
subset_counts = sample_meta[subset_column].value_counts()
subset_counts

subset_grp
set1    109
set2    109
Name: count, dtype: int64

In [38]:
subset_sample_meta = sample_meta.groupby(subset_column)

In [39]:
sample_meta.head()

,cohort.cohortGuid,subject.subjectGuid,subject.biologicalSex,subject.race,subject.ethnicity,subject.birthYear,sample.sampleKitGuid,sample.visitName,sample.drawDate,specimens.specimenGuid,specimens.specimenType,file.id,file.batchID,subset_grp
0,UP1,UP1001,Female,African American,Non-Hispanic origin,2009,KT00826,Flu Year 1 Day 90,2020-12-01T00:00:00Z,PB00826-07,PBMC,4aa6a6ac-e14c-4c41-9c44-9783c4252f20,B053,set1
1,UP1,UP1001,Female,African American,Non-Hispanic origin,2009,KT00891,Flu Year 1 Day 180-360,2021-03-01T00:00:00Z,PL00891-20,Plasma,c70d0dfe-4223-467f-998b-254247765793,B063,set2
2,UP1,UP1001,Female,African American,Non-Hispanic origin,2009,KT00124,Flu Year 1 Pre-Vac 7-12 Weeks,2020-08-01T00:00:00Z,TP00124-01,Tempus Tube,8eb7283b-0394-4ca9-8646-15ae4a206fe6,B053,set1
3,UP1,UP1001,Female,African American,Non-Hispanic origin,2009,KT00199,Flu Year 1 Day 7,2020-09-01T00:00:00Z,PL00199-23,NaN,92945be5-51fc-4aea-9bcc-fde6bacd2301,B053,set1
4,UP1,UP1001,Female,African American,Non-Hispanic origin,2009,KT00943,COVID-19 Visit 3,2021-06-01T00:00:00Z,PB00943-11,PBMC,6db37504-2857-4774-8263-2331408cc405,B093,set2

## Read and assemble anndata objects for each subset

In [42]:
df.shape

(109, 14)

In [43]:
group_input_dict = {}
group_adata_dict = {}
for group, df in subset_sample_meta:
    group_name = group
    #df = df.iloc[0:5] # Remove for full run
    group_uuids = df['file.id'].tolist()
    group_input_dict[group_name] = group_uuids

    # Cache files
    cache_dir = '/home/jupyter/cache'
    cache_paths = []
    for uuid in group_uuids:
        cache_path = '{d}/{u}'.format(d = cache_dir, u = uuid)
        if not os.path.isdir(cache_path):
            hise_res = hisepy.reader.cache_files([uuid])
        cache_paths.append(cache_path)

    # Get cached file paths
    cache_files = []
    for cache_path in cache_paths:
        fn = os.listdir(cache_path)[0]
        cache_files.append('{d}/{f}'.format(d = cache_path, f = fn))

    # Read cached files as anndata
    adata_list = []
    for cache_file in cache_files:
        adata = read_h5_anndata(cache_file)
        adata_list.append(adata)
    group_adata = sc.concat(adata_list)
    
    group_adata_dict[group_name] = group_adata

downloading fileID: cf8a34e7-fab9-46ef-bfca-06d76dce5005
Files have been successfully downloaded!
downloading fileID: d817713c-74b0-4fa1-bde5-d4d9a35ae4a8
Files have been successfully downloaded!
downloading fileID: f2f12b37-7adc-45c7-b5fc-73cedcb44c1e
Files have been successfully downloaded!
downloading fileID: f68c79f5-8bea-48d6-b6b2-728e7c7dd8d2
Files have been successfully downloaded!
downloading fileID: 8c81c819-4e8b-45b2-8926-9b388e4f9049
Files have been successfully downloaded!
downloading fileID: 86dd368f-1ec3-46d9-83a5-a76272e4c784
Files have been successfully downloaded!
downloading fileID: 9bef6cc0-5535-4fe0-b6b3-9de0a68c28ef
Files have been successfully downloaded!
downloading fileID: 0335062a-299b-406c-a939-3eddd83b2c2e
Files have been successfully downloaded!
downloading fileID: 79e9c5f6-c9d8-4f57-95ba-1786abc1d4aa
Files have been successfully downloaded!
downloading fileID: 84412166-dd18-45d9-b407-23ba4ac1a77f
Files have been successfully downloaded!
downloading fileID: f8ec5ea0-afcb-436a-b471-acc415e8621a
Files have been successfully downloaded!
downloading fileID: cf634817-20e8-4ccf-bf35-83af97a86ef4
Files have been successfully downloaded!
downloading fileID: 02e68eb9-be93-4766-81c6-f0763c264794
Files have been successfully downloaded!
downloading fileID: 02398e52-d43f-4f4e-80ac-8d585b95e1bb
Files have been successfully downloaded!
downloading fileID: c1951745-1913-4e0b-a7d2-7ef235e2a73c
Files have been successfully downloaded!
downloading fileID: 14786a94-905f-4d7e-8742-9e377b862629
Files have been successfully downloaded!
downloading fileID: 5311f0d1-a47b-4d5c-a096-aba8160e3ad7
Files have been successfully downloaded!
downloading fileID: 6365dd3e-e8ac-47e3-9c3c-7cbd7b4b6ecf
Files have been successfully downloaded!
downloading fileID: 31665389-646c-4632-928a-4c92128b8271
Files have been successfully downloaded!
downloading fileID: 7d3aa1cb-08c4-45a4-ac0f-2787f76641e4
Files have been successfully downloaded!
downloading fileID: d8446f60-0f83-4ceb-a0d7-5f0b1f044d3e
Files have been successfully downloaded!
downloading fileID: 9ae56cdd-1577-4110-88e2-1f5641d7303d
Files have been successfully downloaded!
downloading fileID: d28febcb-1a37-4f0d-bfd8-30dc3512c948
Files have been successfully downloaded!
downloading fileID: e85db21a-5728-4b7a-a25b-2e95b6f0561b
Files have been successfully downloaded!
downloading fileID: 1291af71-ac95-47b6-8c8d-9b2ee4b0ed4e
Files have been successfully downloaded!
downloading fileID: 8aac47fa-65b5-4fa4-95eb-1c7d4f0c4843
Files have been successfully downloaded!
downloading fileID: c02a1400-b607-4cfe-908a-2af038bfcaa2
Files have been successfully downloaded!
downloading fileID: b9ff0306-5fa5-4543-b335-a74d12c135d2
Files have been successfully downloaded!
downloading fileID: 5c3fb52e-46e5-4cb9-ae12-8eae7ba3b285
Files have been successfully downloaded!
downloading fileID: 04faa448-18e1-41a4-aebd-59b5993617f8
Files have been successfully downloaded!
downloading fileID: 21694a97-91de-4d4c-b37a-9ccb93f9e110
Files have been successfully downloaded!
downloading fileID: 0ef6cef2-9e78-471a-a9f2-b72f8ed99222
Files have been successfully downloaded!
downloading fileID: ef1b7789-2b89-408e-aee4-9980ed7a0629
Files have been successfully downloaded!
downloading fileID: 260f2b56-aa08-4a42-a7af-95706798b860
Files have been successfully downloaded!
downloading fileID: bbbc558b-a706-4ecd-9f8f-4953ba1c8f88
Files have been successfully downloaded!
downloading fileID: f1a1bba5-5d57-42a1-a41c-4193dfc0dee9
Files have been successfully downloaded!
downloading fileID: 80b1de43-62fd-453d-8615-ca65415efb92
Files have been successfully downloaded!
downloading fileID: bfca7e07-35aa-4755-b7d6-356031225b94
Files have been successfully downloaded!
downloading fileID: 65cf9d50-7919-42ed-8cf0-0ac05e5f911a
Files have been successfully downloaded!
downloading fileID: 551acb44-a425-49fe-9e77-e59823d349d9
Files have been successfully downloaded!
downloading fileID: 68cd9bef-360a-4497-bfd6-76cd2e7cd87b
Files have been successfully downloaded!
downloading fileID: f96e3dc4-0c12-4a5c-b55e-ec72f51a623c
Files have been successfully downloaded!
downloading fileID: c70d0dfe-4223-467f-998b-254247765793
Files have been successfully downloaded!
downloading fileID: 6db37504-2857-4774-8263-2331408cc405
Files have been successfully downloaded!
downloading fileID: 0a6567d8-6d7a-461e-b067-ee20f77d736f
Files have been successfully downloaded!
downloading fileID: ff9d4e77-16d5-498f-8c34-64dd4b6fd7e0
Files have been successfully downloaded!
downloading fileID: 502480b2-5056-4a76-bdfe-a40e5664e31f
Files have been successfully downloaded!
downloading fileID: 1d05a3a2-3e08-48bd-ad2e-46aa04017fd1
Files have been successfully downloaded!
downloading fileID: c48f6b5f-dbc8-445c-ac2a-4200fde23798
Files have been successfully downloaded!
downloading fileID: 39834db0-971f-4546-bb1d-e3a9d8266686
Files have been successfully downloaded!
downloading fileID: a28dfbb8-6dc3-4db7-a5f0-7d93b8008796
Files have been successfully downloaded!
downloading fileID: 8409e8c6-def7-447f-8fcf-82862a9bbfd8
Files have been successfully downloaded!
downloading fileID: 687ff240-2df0-4e50-b30e-a9cd045c5ff5
Files have been successfully downloaded!
downloading fileID: 5136ba72-e472-4b75-8eb8-d26b921cc4dc
Files have been successfully downloaded!
downloading fileID: e1c6a3ac-d0cd-4802-adff-8410206f268e
Files have been successfully downloaded!
downloading fileID: e5e86eb9-2957-41ab-8255-e725dc1c5a70
Files have been successfully downloaded!
downloading fileID: 5813339d-4889-4ea9-a770-a1101530e680
Files have been successfully downloaded!
downloading fileID: 84251167-04e2-4948-a5a3-38be41c17590
Files have been successfully downloaded!
downloading fileID: 1d963c9d-232b-4eac-83df-4f7f82bc0e69
Files have been successfully downloaded!
downloading fileID: 7da5e2d0-9187-404c-90a3-9003e7c5c92a
Files have been successfully downloaded!
downloading fileID: a8197f23-c392-4f8e-ad83-d6fbbd3abdef
Files have been successfully downloaded!
downloading fileID: e6c8aff1-fb90-4333-8293-2c6d422959f7
Files have been successfully downloaded!
downloading fileID: 5a6c45e0-db6d-4697-b4ad-bbef03d6b268
Files have been successfully downloaded!
downloading fileID: a7520eda-1dca-483f-80ed-93a705529bcb
Files have been successfully downloaded!
downloading fileID: d2cfe006-8df9-49e6-b288-8033e970ff7a
Files have been successfully downloaded!
downloading fileID: d5830a35-fd7d-449c-b7e2-6e568bb12c5c
Files have been successfully downloaded!
downloading fileID: 5e81ebcb-dc36-40fa-ac35-1d8404301083
Files have been successfully downloaded!
downloading fileID: a460244d-bd8d-4b26-b308-a001fba94c5a
Files have been successfully downloaded!
downloading fileID: e2bd4673-e284-416a-824a-c2e5bb5173d6
Files have been successfully downloaded!
downloading fileID: 4c1df71f-0482-4a39-b87c-ab6626f8af23
Files have been successfully downloaded!
downloading fileID: 81c175e2-037c-4309-9ed7-030320eb7dcc
Files have been successfully downloaded!
downloading fileID: a74a10fe-6fe8-4e21-b757-4d95e333e983
Files have been successfully downloaded!
downloading fileID: bc0a4572-a749-4a6a-99a1-ba71f300ec8e
Files have been successfully downloaded!
downloading fileID: b4da886a-fc9d-4174-9461-a50ebf8cb9f0
Files have been successfully downloaded!
downloading fileID: e395ceb8-cc59-4877-bcd4-9abb01521ab8
Files have been successfully downloaded!
downloading fileID: 71f4272d-db8a-4ce3-ac5b-106b54bb0e24
Files have been successfully downloaded!
downloading fileID: 61338c7a-079d-4381-9e4d-5961613f7d9a
Files have been successfully downloaded!
downloading fileID: e2ddd7ee-6f3e-468b-a350-e4aa21ee4b89
Files have been successfully downloaded!
downloading fileID: fa92a82a-b0b9-4aac-bca6-89c4ba0722e4
Files have been successfully downloaded!
downloading fileID: 950307b2-aa04-4349-b7fd-e4eca528abea
Files have been successfully downloaded!
downloading fileID: 02948c51-006f-4e71-b836-979fb639071c
Files have been successfully downloaded!
downloading fileID: ffb41f72-793b-4746-8c1e-8db4c7bf07b6
Files have been successfully downloaded!
downloading fileID: f606f3fc-1de9-483a-bd7c-169d32c780bb
Files have been successfully downloaded!
downloading fileID: 4194ddcf-7e55-49f8-989f-57518b7168ea
Files have been successfully downloaded!
downloading fileID: c41bee77-8be4-4549-8277-ab7bf59e0362
Files have been successfully downloaded!
downloading fileID: e728748b-b045-4cfc-be34-fb3638080f2b
Files have been successfully downloaded!
downloading fileID: 5d4bed6e-9dec-4e81-876d-b4f647ca5848
Files have been successfully downloaded!
downloading fileID: 05ce48d8-15a8-4bbe-be5d-7291bd306451
Files have been successfully downloaded!
downloading fileID: bdcc9cd4-f0b3-4b86-bbc8-2e933affa941
Files have been successfully downloaded!
downloading fileID: f12a9110-2f32-4f30-b25e-cf9070d02753
Files have been successfully downloaded!
downloading fileID: fcb7e109-426f-4d61-a170-22764dbbbc73
Files have been successfully downloaded!
downloading fileID: 5a8ef82d-0a44-4ba5-85b6-38a4d0659170
Files have been successfully downloaded!
downloading fileID: 878b55d1-9d30-4fc9-a1d2-2283e9e03825
Files have been successfully downloaded!
downloading fileID: 9d4308b6-6173-4d4e-84e7-0d951a6f8b6d
Files have been successfully downloaded!
downloading fileID: 2d978d0a-3c77-4385-9568-95cd0cfc61a2
Files have been successfully downloaded!
downloading fileID: 2a4c43d1-34ee-4284-8749-c2eaaccd4b91
Files have been successfully downloaded!
downloading fileID: c350c0ed-1c7d-4c0f-8e50-c662c3ab5e5a
Files have been successfully downloaded!
downloading fileID: c8a60a40-1a9a-41b2-86a2-826df0a0af4f
Files have been successfully downloaded!
downloading fileID: ce7cb4d5-9fdc-421f-9cba-bda97c3fda8b
Files have been successfully downloaded!
downloading fileID: f523486c-c61f-4be6-ad97-bcb3f32d285a
Files have been successfully downloaded!
downloading fileID: ea3ad98d-ba28-424f-bff3-58a6ab6840fc
Files have been successfully downloaded!
downloading fileID: a2940177-682b-4681-b03f-4965da6892d3
Files have been successfully downloaded!
downloading fileID: c10ab7d0-6f08-4557-bdf2-bcffc57c2bb7
Files have been successfully downloaded!
downloading fileID: 00168b96-a291-4925-8cb5-1b4471494946
Files have been successfully downloaded!
downloading fileID: 924e781e-34e4-4d1e-aa82-332b2e2b0dda
Files have been successfully downloaded!
downloading fileID: b00943d7-bbbf-4cd9-808d-fb5cebde9ecb
Files have been successfully downloaded!
downloading fileID: 986098fc-f55b-48b1-b10c-684779c5f2fe
Files have been successfully downloaded!
downloading fileID: 59e5f18b-a465-4825-a0ff-bb58c5342ce7
Files have been successfully downloaded!
downloading fileID: 5dbf90ec-9328-4cbb-9d9d-dd8ff5b96434
Files have been successfully downloaded!
downloading fileID: c28f6340-ea4a-431a-b64b-38fb3a168b58
Files have been successfully downloaded!
downloading fileID: 8d16f9bc-0628-48a7-91a8-00e81e1ee0ed
Files have been successfully downloaded!
downloading fileID: 853689e6-d7ab-475a-9f80-f801f8f647c0
Files have been successfully downloaded!
downloading fileID: d8c6cd6b-71e6-4ec7-980c-6c6ca6039194
Files have been successfully downloaded!
downloading fileID: 1ce43409-de8d-4e34-8d70-f0e74f6a733f
Files have been successfully downloaded!
downloading fileID: a71c846b-edba-4ac1-8e14-127ed57ef212
Files have been successfully downloaded!
downloading fileID: 56c6d34e-5b1a-4a7c-9f89-d208f8c2d453
Files have been successfully downloaded!
downloading fileID: 8f8421c5-8966-499e-824e-33db48d64456
Files have been successfully downloaded!
downloading fileID: a95cc1e4-e567-4255-8d60-a66d55acb7d2
Files have been successfully downloaded!
downloading fileID: b081adb1-5edf-4855-b7fe-126eb64fdae2
Files have been successfully downloaded!
downloading fileID: 30cfca6b-1c1d-41e5-99a9-ae369acc5944
Files have been successfully downloaded!
downloading fileID: 3afec9fb-d688-4b9c-9d45-850c2e12fc78
Files have been successfully downloaded!
downloading fileID: 5ce1b9a2-3a5d-4f7b-8e97-ed3aad24ad5e
Files have been successfully downloaded!
downloading fileID: 05fc9398-1f15-4b76-bdba-da9c317c7f6a
Files have been successfully downloaded!
downloading fileID: 7b39c8b7-1212-47ea-b81f-ef1b75a34a77
Files have been successfully downloaded!
downloading fileID: 44dc16a4-95a1-4bf2-bdee-8efa176cbdaf
Files have been successfully downloaded!
downloading fileID: 0f666f41-55bf-41aa-98d4-faa249ca685a
Files have been successfully downloaded!
downloading fileID: 39155e76-f104-4f06-94e9-4e1febfc9ec7
Files have been successfully downloaded!
downloading fileID: beb1704b-915e-470e-8716-183821fc084f
Files have been successfully downloaded!
downloading fileID: bbd1ec30-17e0-405b-b644-ed7f1501c6c0
Files have been successfully downloaded!
downloading fileID: b9dec5cd-eb36-4ec8-889c-e33db1c7fd7f
Files have been successfully downloaded!
downloading fileID: f39a252f-b357-4d23-aee2-255034f49291
Files have been successfully downloaded!
downloading fileID: e03d9c8c-0722-422d-9e9a-4ab0ddb70c70
Files have been successfully downloaded!
downloading fileID: 0d67a6ef-8b3a-4078-a77f-dbb61d9daea8
Files have been successfully downloaded!
downloading fileID: b7816adf-c7e6-4a48-99fd-1558fcac3af0
Files have been successfully downloaded!
downloading fileID: b7f45759-2373-469f-b525-c1b386443386
Files have been successfully downloaded!
downloading fileID: ac74a620-5109-44eb-92e2-38a7f7eff5e5
Files have been successfully downloaded!
downloading fileID: 144b971e-0bf6-4cc5-942f-3843c59c95f6
Files have been successfully downloaded!
downloading fileID: ff9cddef-65d3-48d7-8620-8d1990864a43
Files have been successfully downloaded!
downloading fileID: 64b1f3e1-3ae7-4b63-9c22-80e46f68e304
Files have been successfully downloaded!
downloading fileID: 1c7dbfc7-9e91-445d-8e61-2fd2cc0d860e
Files have been successfully downloaded!
downloading fileID: 7af8fd2b-9fe8-4a78-9e9b-a92d4304fc73
Files have been successfully downloaded!
downloading fileID: c4f5c009-d029-4f9c-880c-090deea63481
Files have been successfully downloaded!
downloading fileID: 7de8e800-1d9b-4c89-81fd-bd3717da4899
Files have been successfully downloaded!
downloading fileID: bdf43804-8f96-4bc9-80a4-3759a6a651ef
Files have been successfully downloaded!
downloading fileID: 4c4bac78-10c9-40b5-8fce-9754275644a4
Files have been successfully downloaded!
downloading fileID: 164c1368-c440-41fe-b74a-1e2884865a9d
Files have been successfully downloaded!
downloading fileID: 88a1cf2d-1fde-4e1a-b247-7f1900594d22
Files have been successfully downloaded!
downloading fileID: 66b810c7-fa3e-4143-b0c9-bf52cec8dd67
Files have been successfully downloaded!
downloading fileID: 70850b9c-fc15-4d4a-985d-1e5c81b6474a
Files have been successfully downloaded!
downloading fileID: 36f78e5d-00cb-4f22-be1a-a42556be1105
Files have been successfully downloaded!

In [44]:
group_adata

AnnData object with n_obs × n_vars = 1981919 × 33538
    obs: 'barcodes', 'batch_id', 'cell_name', 'cell_uuid', 'chip_id', 'hto_barcode', 'hto_category', 'n_genes', 'n_mito_umis', 'n_reads', 'n_umis', 'original_barcodes', 'pbmc_sample_id', 'pool_id', 'seurat_pbmc_type', 'seurat_pbmc_type_score', 'umap_1', 'umap_2', 'well_id'

In [45]:
group_adata_dict.keys()

dict_keys(['set1', 'set2'])

In [46]:
for group_name, adata in group_adata_dict.items():
    print('{g}: {n} cells'.format(g = group_name, n = adata.shape[0]))

set1: 1929009 cells
set2: 1981919 cells

In [47]:
sum(adata.shape[0] for adata in group_adata_dict.values())

3910928

## Update Observations with additional metadata

Now, we'll add the sample metadata, CMV status, and BMI data to our scRNA-seq data.

First, we'll convert `pbmc_sample_id` to `sample.sampleKitGuid` using a regular expression. PBMC samples are derived from kits in our LIMS system, so both share the same numerical core. The difference is that there can be multiple PBMC samples collected at the same time, so PBMC samples are prefixed with PB to indicate their sample type, and suffixed with -XX to indicate an aliquot number.

In [48]:
def sample_to_kit(sample):
    kit = re.sub('PB([0-9]+)-.+','KT\\1',sample)
    return(kit)

To keep things tidy, we'll also drop the `seurat_pbmc_type`, `seurat_pbmc_type_score`, and UMAP coordinates generated by our processing pipeline. These cell type assignments are from a now-outdated reference dataset, and the UMAP coordinates are generated for viewing individual samples - not helpful for our full dataset.

In [49]:
drop_columns = [
    'seurat_pbmc_type','seurat_pbmc_type_score',
    'umap_1', 'umap_2'
]

Then, we'll add our new sample data with a left join on the `sample.sampleKitGuid` values, and add our labels and doublet calls with a left join on cell `barcodes`.

Next, we'll convert all of our text columns to categorical. This is used to make storage of text data more efficient when we write our output file, as we'll only need to store a single instance of our strings.

We do this for all columns except barcodes, which we need to retain as a string type for use as an index.

Finally, we'll add these back to our anndata object

In [50]:
for group_name, adata in group_adata_dict.items():
    print('{g}: {p}'.format(g = group_name, p = adata.obs['pbmc_sample_id'].str.startswith('PB').all()))

set1: True
set2: True

In [51]:
for group_name, adata in group_adata_dict.items():
    print(group_name)
    obs = adata.obs
    
    # Convert sample.sampleKitGuid
    print('converting ids')
    obs['sample.sampleKitGuid'] = [sample_to_kit(sample) for sample in obs['pbmc_sample_id']]
    
    # Drop old columns
    obs = obs.drop(drop_columns, axis = 1)
    
    print('merging sample metadata')
    # Add new metadata
    obs = obs.merge(
        sample_meta,
        how = 'left',
        on = 'sample.sampleKitGuid'
    )
    
    print('merging labels')
    # Add labels
    obs = obs.merge(all_labels, how = 'left', on = 'barcodes')
    
    print('converting to categorical')
    # Convert to categorical
    cat_obs = obs
    for i in range(cat_obs.shape[1]):
        col_name = cat_obs.dtypes.index.tolist()[i]
        col_type = cat_obs.dtypes[col_name]
        if col_name == 'barcodes':
            cat_obs[col_name] = cat_obs[col_name].astype(str)
        elif is_object_dtype(col_type):
            cat_obs[col_name] = cat_obs[col_name].astype('category')
    cat_obs = cat_obs.set_index('barcodes', drop = False)
    
    # Assign final observations back to anndata
    adata.obs = cat_obs
    
    group_adata_dict[group_name] = adata

set1
converting ids
merging sample metadata
merging labels
converting to categorical
set2
converting ids
merging sample metadata
merging labels
converting to categorical

## Write assembled data to disk

In [52]:
out_dir = 'output'
if not os.path.isdir(out_dir):
    os.makedirs(out_dir)

In [53]:
out_h5ads = {}
for group_name, adata in group_adata_dict.items():
    out_h5ad = 'output/up1_pbmc_{g}_raw_labeled_{d}.h5ad'.format(g = group_name, d = date.today())
    adata.write_h5ad(out_h5ad)
    out_h5ads[group_name] = out_h5ad

In [54]:
out_csvs = {}
out_parquets = {}
for group_name, adata in group_adata_dict.items():
    obs = adata.obs
    
    out_csv = 'output/up1_pbmc_{g}_raw_labeled_meta_{d}.csv'.format(g = group_name, d = date.today())
    obs.to_csv(out_csv)
    out_csvs[group_name] = out_csv

    out_parquet = 'output/up1_pbmc_{g}_raw_labeled_meta_{d}.parquet'.format(g = group_name, d = date.today())

    obs = obs.loc[:, ~obs.columns.duplicated()] ## remove duplicate columns 
    obs.to_parquet(out_parquet)
    out_parquets[group_name] = out_parquet

## Upload assembled data to HISE

Finally, we'll use `hisepy.upload.upload_files()` to send a copy of our output to HISE to use for downstream analysis steps.

In [55]:
ss = hisepy.get_study_spaces()

In [56]:
ss

[{'id': '0b6bf907-6985-40e0-944d-677ac932677f',
  'accountGuid': 'b34b9c66-aa5d-45d0-9569-f78ca8f6813f',
  'projectGuid': '7ef501f4-79ea-45f0-ad97-6ed237cd5dd1',
  'driveId': '0AEgFtzSiOc7hUk9PVA',
  'auditInfo': {'added': '2024-08-14T20:42:25.668Z',
   'addedUser': 'temi.adewunmi@alleninstitute.org',
   'lastModified': '2024-08-19T17:19:23.424Z',
   'lastModifiedBy': 'temi.adewunmi@alleninstitute.org',
   'version': 1},
  'name': 'UP1 scRNAseq Study',
  'description': 'Project store for the work done on the scRNAseq samples from the UP1 cohort',
  'externalDrive': {'name': 'up1-studyExternal',
   'id': '1-wdxDzX3eTR2jYmdPEjJXE2HWtujRNWD',
   'parents': ['1NCAXL8ZmeQJawC2wRfG6si-O0CiMW3dN'],
   'webContentLink': '',
   'webViewLink': 'https://drive.google.com/drive/folders/1-wdxDzX3eTR2jYmdPEjJXE2HWtujRNWD',
   'iconLink': 'https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder+48+shared'},
  'reportDrive': {'name': 'up1-studyReport',
   'id': '1G9tr2705kYMDZuTAnkQITgESy4zvU87Y',
   'parents': ['1NCAXL8ZmeQJawC2wRfG6si-O0CiMW3dN'],
   'webContentLink': '',
   'webViewLink': 'https://drive.google.com/drive/folders/1G9tr2705kYMDZuTAnkQITgESy4zvU87Y',
   'iconLink': 'https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder+48+shared'},
  'visualizationsDrive': {'name': 'up1-studyVisualizations',
   'id': '1NFSq0xTznsHsrDo2o2RKyDBjIU4GHxo-',
   'parents': ['1NCAXL8ZmeQJawC2wRfG6si-O0CiMW3dN'],
   'webContentLink': '',
   'webViewLink': 'https://drive.google.com/drive/folders/1NFSq0xTznsHsrDo2o2RKyDBjIU4GHxo-',
   'iconLink': 'https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder+48+shared'},
  'owners': [{'email': 'temi.adewunmi@alleninstitute.org', 'role': 'writer'},
   {'email': 'kathleen.abadie@alleninstitute.org', 'role': 'writer'},
   {'email': 'claire.gustafson@alleninstitute.org', 'role': 'writer'}],
  'sharedWith': [],
  'heroImages': [],
  'notify': 'true',
  'assetTags': ['chlorinesulfursilver'],
  'studyTags': []}]

In [57]:

print(ss[0]['name'])
print(ss[0]['id'])
study_space_uuid = ss[0]['id']

title = 'Labeled Raw scRNA-seq Assembly {d}'.format(d = date.today())

UP1 scRNAseq Study
0b6bf907-6985-40e0-944d-677ac932677f

In [58]:
search_id = element_id()
search_id

'manganese-fermium-selenium'

In [59]:
in_files = [sample_meta_uuid] + search_df['id'].tolist()
in_files = in_files + sample_meta['file.id'].tolist()

In [60]:
len(in_files)

223

In [61]:
in_files[0:10]

['cb01d5b1-40d8-4940-b61c-86d78de4528b',
 'e7c9a970-5075-4af5-a797-403b03848019',
 '041ef46f-483d-4a3d-900c-64c97072da7c',
 'a5300b3e-4739-47be-8fc0-cb1039ff710d',
 '5942d3fa-9efe-43e2-9e48-81b6cecdf089',
 '4aa6a6ac-e14c-4c41-9c44-9783c4252f20',
 'c70d0dfe-4223-467f-998b-254247765793',
 '8eb7283b-0394-4ca9-8646-15ae4a206fe6',
 '92945be5-51fc-4aea-9bcc-fde6bacd2301',
 '6db37504-2857-4774-8263-2331408cc405']

In [62]:
out_files = list(out_h5ads.values()) + list(out_csvs.values()) + list(out_parquets.values())

In [63]:
out_files

['output/up1_pbmc_set1_raw_labeled_2024-08-19.h5ad',
 'output/up1_pbmc_set2_raw_labeled_2024-08-19.h5ad',
 'output/up1_pbmc_set1_raw_labeled_meta_2024-08-19.csv',
 'output/up1_pbmc_set2_raw_labeled_meta_2024-08-19.csv',
 'output/up1_pbmc_set1_raw_labeled_meta_2024-08-19.parquet',
 'output/up1_pbmc_set2_raw_labeled_meta_2024-08-19.parquet']

In [64]:
hisepy.upload.upload_files(
    files = out_files,
    study_space_id = study_space_uuid,
    title = title,
    input_file_ids = in_files,
    destination = search_id
)

you are trying to upload file_ids... ['output/up1_pbmc_set1_raw_labeled_2024-08-19.h5ad', 'output/up1_pbmc_set2_raw_labeled_2024-08-19.h5ad', 'output/up1_pbmc_set1_raw_labeled_meta_2024-08-19.csv', 'output/up1_pbmc_set2_raw_labeled_meta_2024-08-19.csv', 'output/up1_pbmc_set1_raw_labeled_meta_2024-08-19.parquet', 'output/up1_pbmc_set2_raw_labeled_meta_2024-08-19.parquet']. Do you truly want to proceed?

(y/n) y

{'trace_id': '51b4f6c4-5ea3-41bc-b97d-0abe4bdce01d',
 'files': ['output/up1_pbmc_set1_raw_labeled_2024-08-19.h5ad',
  'output/up1_pbmc_set2_raw_labeled_2024-08-19.h5ad',
  'output/up1_pbmc_set1_raw_labeled_meta_2024-08-19.csv',
  'output/up1_pbmc_set2_raw_labeled_meta_2024-08-19.csv',
  'output/up1_pbmc_set1_raw_labeled_meta_2024-08-19.parquet',
  'output/up1_pbmc_set2_raw_labeled_meta_2024-08-19.parquet']}

In [65]:
import session_info
session_info.show()

#### Notes
1. removing majority voting and over clustering columns, rename these 2 columns based on levels?

In [66]:
all_labels.head()

,barcodes,predicted_doublet,doublet_score,AIFI_L1,over_clustering,majority_voting,AIFI_L1_score,AIFI_L2,over_clustering,majority_voting,AIFI_L2_score,AIFI_L3,over_clustering,majority_voting,AIFI_L3_score
0,b9993ec4872b11ebb599de5a8c2059ae,False,0.060170,T cell,70,T cell,0.997307,Proliferating NK cell,70,Memory CD4 T cell,0.027022,Memory CD4 Treg,70,CM CD4 T cell,0.999993
1,b99942fc872b11ebb599de5a8c2059ae,False,0.013071,T cell,22,T cell,0.999338,Memory CD8 T cell,22,Memory CD8 T cell,0.955047,KLRF1- GZMB+ CD27- EM CD8 T cell,22,KLRF1+ GZMB+ CD27- EM CD8 T cell,1.000000
2,b9996f66872b11ebb599de5a8c2059ae,False,0.120700,T cell,142,T cell,1.000000,Naive CD8 T cell,142,Naive CD8 T cell,0.984279,Core naive CD8 T cell,142,Core naive CD8 T cell,1.000000
3,b99971c8872b11ebb599de5a8c2059ae,False,0.018831,Monocyte,23,Monocyte,0.999258,CD14 monocyte,23,CD14 monocyte,0.997393,Core CD14 monocyte,23,Core CD14 monocyte,1.000000
4,b9997290872b11ebb599de5a8c2059ae,False,0.026079,Monocyte,46,Monocyte,0.999999,CD14 monocyte,46,CD14 monocyte,0.999497,ISG+ CD14 monocyte,46,Core CD14 monocyte,1.000000

In [67]:
all_labels.shape

(3910928, 15)