In [1]:
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(tibble))
suppressPackageStartupMessages(library(stringr))
library(parallel)
library(DESeq2)
library(hise)
source('/home//workspace/pediatric_IH/jupyter/IHA-Figure/helper_function/helper_function_IHA.r')

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    Filter, Find, Map, Position, Reduce, anyDuplicated, aperm, append,
    as.data.frame, basename, cbind, colnames, dirname, do.call,
    duplicated, eval, evalq, get, grep, grepl, intersect, is.unsorted,
    lapply, mapply, match, mget, order, paste, pmax, pmax.int, pmin,
    pmin.int, rank, rbind, rownames, sapply, saveRDS, setdiff, table,
    tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:tidyr’:

    expand


The following objects are masked from ‘package:dplyr’:

    first, rename


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    I, expand.grid, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

# Read Meta Data

In [2]:
#meta_data=read.csv("/home/workspace/pediatric_IH/jupyter/certpro_up1/BRI_Analysis/scRNA_meta_data-2024-05-09.csv")
meta_data=read.csv("/home/workspace/pediatric_IH/jupyter/preprocessing_output/UP1_218scRNAsamp_noDuplicates.csv")

In [3]:
colnames(meta_data)
#meta_data$cmv_status

 [1] "X"                                   "Unnamed..0.1"
 [3] "Unnamed..0"                          "lastUpdated"
 [5] "sample.id"                           "sample.bridgingControl"
 [7] "sample.sampleKitGuid"                "sample.visitName"
 [9] "sample.visitDetails"                 "sample.drawDate"
[11] "sample.daysSinceFirstVisit"          "sample.diseaseStatesRecordedAtVisit"
[13] "file.id"                             "file.name"
[15] "file.batchID"                        "file.panel"
[17] "file.pool"                           "file.fileType"
[19] "file.majorVersion"                   "subject.id"
[21] "subject.biologicalSex"               "subject.birthYear"
[23] "subject.ethnicity"                   "subject.partnerCode"
[25] "subject.race"                        "subject.subjectGuid"
[27] "cohort.cohortGuid"                   "file.userTags.details"
[29] "file.userTags.group"                 "file.userTags.name"
[31] "file.userTags.origin"                "file.userTags.other"
[33] "file.userTags.version"               "specimens.specimenType"
[35] "specimens.specimenGuid"              "cmv_status"
[37] "relabeled_visit"

In [4]:
df<-as.data.frame(table(meta_data$subject.subjectGuid))

In [5]:
df$sub<-df$Var1

In [6]:
df$cohort<-substr(as.character(df$Var1),1,3)

In [7]:
as.character(df$Var1)

 [1] "UP1001" "UP1002" "UP1003" "UP1004" "UP1005" "UP1006" "UP1007" "UP1008"
 [9] "UP1009" "UP1010" "UP1011" "UP1012" "UP1013" "UP1014" "UP1015" "UP1016"
[17] "UP1017" "UP1018" "UP1019" "UP1020" "UP1021" "UP1022" "UP1023" "UP1024"
[25] "UP1025" "UP1026" "UP1027" "UP1028" "UP1031" "UP1032" "UP1033" "UP1034"
[33] "UP1035" "UP1036" "UP1037" "UP1038" "UP1039" "UP1041" "UP1042" "UP1043"
[41] "UP1044" "UP1045" "UP1047" "UP1048" "UP1049" "UP1050"

In [8]:
#meta_data=meta_data %>% filter(cohort.cohortGuid == 'BR2')

In [8]:
df
table(meta_data$sample.visitName)

   Var1   Freq sub    cohort
1  UP1001 10   UP1001 UP1
2  UP1002  2   UP1002 UP1
3  UP1003 10   UP1003 UP1
4  UP1004 10   UP1004 UP1
5  UP1005  7   UP1005 UP1
6  UP1006 10   UP1006 UP1
7  UP1007  8   UP1007 UP1
8  UP1008  6   UP1008 UP1
9  UP1009  1   UP1009 UP1
10 UP1010  1   UP1010 UP1
11 UP1011  9   UP1011 UP1
12 UP1012  8   UP1012 UP1
13 UP1013  4   UP1013 UP1
14 UP1014  8   UP1014 UP1
15 UP1015  9   UP1015 UP1
16 UP1016  7   UP1016 UP1
17 UP1017  6   UP1017 UP1
18 UP1018  9   UP1018 UP1
19 UP1019  3   UP1019 UP1
20 UP1020  7   UP1020 UP1
21 UP1021  6   UP1021 UP1
22 UP1022  9   UP1022 UP1
23 UP1023  6   UP1023 UP1
24 UP1024  8   UP1024 UP1
25 UP1025  6   UP1025 UP1
26 UP1026  3   UP1026 UP1
27 UP1027  3   UP1027 UP1
28 UP1028  1   UP1028 UP1
29 UP1031  5   UP1031 UP1
30 UP1032  3   UP1032 UP1
31 UP1033  2   UP1033 UP1
32 UP1034  3   UP1034 UP1
33 UP1035  3   UP1035 UP1
34 UP1036  3   UP1036 UP1
35 UP1037  2   UP1037 UP1
36 UP1038  3   UP1038 UP1
37 UP1039  2   UP1039 UP1
38 UP1041  2   UP1041 UP1
39 UP1042  1   UP1042 UP1
40 UP1043  2   UP1043 UP1
41 UP1044  2   UP1044 UP1
42 UP1045  1   UP1045 UP1
43 UP1047  2   UP1047 UP1
44 UP1048  1   UP1048 UP1
45 UP1049  2   UP1049 UP1
46 UP1050  2   UP1050 UP1

             COVID-19 Visit 1              COVID-19 Visit 3
                            2                            10
             COVID-19 Visit 6        Flu Year 1 Day 180-360
                           12                            12
             Flu Year 1 Day 7             Flu Year 1 Day 90
                           39                            27
Flu Year 1 Pre-Vac 7-12 Weeks        Flu Year 1 Stand-Alone
                           46                             1
       Flu Year 2 Day 180-360              Flu Year 2 Day 7
                           16                            18
            Flu Year 2 Day 90 Flu Year 2 Pre-Vac 7-12 Weeks
                           16                            19

In [31]:
#trying to run on only the subjects that have Year 1 and 2 samples
subjects_with_both_years <- meta_data %>%
  group_by(subject.subjectGuid) %>%
  filter(all(c('Flu Year 1 Pre-Vac 7-12 Weeks', 'Flu Year 1 Day 7', 'Flu Year 2 Pre-Vac 7-12 Weeks','Flu Year 2 Day 7') %in% sample.visitName)) %>%
  ungroup()

meta_data <- meta_data  %>% filter(meta_data$subject.subjectGuid %in% subjects_with_both_years$subject.subjectGuid )

# Perform Deseq2 on Year 1 Day 0 samples

In [9]:
filtered_gene_set<-read.csv("/home/workspace/pediatric_IH/jupyter/Analysis/DEG/Flu_Y2_D0_D7/UP1_filtered_gene_Y2_D0_D90_clean.csv")
cell_list = read.csv('/home/workspace/pediatric_IH/jupyter/Analysis/DEG/cells.csv')

In [10]:
df_list <-list()

In [11]:
#meta_data_subset=meta_data %>% filter(sample.visitName  %in% c("Flu Year 1 Pre-Vac 7-12 Weeks", "Flu Year 1 Day 7"))

aggregated_count_file_list<- paste0('/home/workspace/pediatric_IH/jupyter/pseudobulk_output/Aggregated_Raw_Expression_of_Celltypes_by_celltype_AIFI_L3/',cell_list$celltype,'.csv')
#paste0("/home/jupyter/BRI_Figures_Final_V2/Dataset/scRNA/BRI/Aggregated_Count/Aggregated_Raw_Expression_of_Celltypes_by_Sample_AIFI_L3/",meta_data_subset$pbmc_sample_id,".csv")

In [12]:
df_list<-read_pseudobulk_expression(aggregated_count_file_list)

[1] "Total reading time: 24.5290000000095 seconds"
[1] "The length of the list matches the length of the input path."

In [13]:
df_list[[1]]

            ILC:KT00124 ILC:KT00127 ILC:KT00172 ILC:KT00173 ILC:KT00175
MIR1302-2HG 0           0           0           0           0
FAM138A     0           0           0           0           0
OR4F5       0           0           0           0           0
AL627309.1  0           0           0           0           0
AL627309.3  0           0           0           0           0
AL627309.2  0           0           0           0           0
AL627309.4  0           0           0           0           0
AL732372.1  0           0           0           0           0
OR4F29      0           0           0           0           0
AC114498.1  0           0           0           0           0
OR4F16      0           0           0           0           0
AL669831.2  0           0           0           0           0
AL669831.5  0           0           0           0           0
FAM87B      0           0           0           0           0
LINC00115   0           0           0           0           0
FAM41C      0           0           1           0           0
AL645608.7  0           0           0           0           0
AL645608.3  0           0           0           0           0
AL645608.5  0           0           0           0           0
AL645608.1  0           0           0           0           0
SAMD11      0           0           0           0           0
NOC2L       1           3           3           2           2
KLHL17      0           0           0           0           0
PLEKHN1     0           0           0           0           0
PERM1       0           0           0           0           0
AL645608.8  0           0           0           0           0
HES4        0           0           0           0           0
ISG15       6           0           4           3           6
AL645608.2  0           0           0           0           0
AGRN        0           0           0           0           0
⋮           ⋮           ⋮           ⋮           ⋮           ⋮
MT-CYB      86          67          93          104         169
AC133551.1   0           0           0            0           0
AC136612.1   0           0           0            0           0
AC136616.1   0           0           0            0           0
AC136616.3   0           0           0            0           0
AC136616.2   0           0           0            0           0
AC141272.1   0           0           0            0           0
AC136352.3   0           0           0            0           0
AC136352.2   0           0           0            0           0
AC171558.3   0           0           0            0           0
AC171558.1   0           0           0            0           0
BX004987.1   0           0           0            0           0
AC145212.1   0           0           0            0           0
MAFIP        0           0           0            0           0
AC011841.1   0           0           0            0           0
AC011043.1   0           0           0            0           0
AC011043.2   0           0           0            0           0
AL592183.1   0           0           0            0           3
AC007325.1   0           0           0            0           0
AC007325.4   0           0           0            0           0
AC007325.2   0           0           0            0           0
BX072566.1   0           0           0            0           0
AL354822.1   0           0           0            0           0
AC023491.2   0           0           0            0           0
AC004556.1   0           0           0            0           1
AC233755.2   0           0           0            0           0
AC233755.1   0           0           0            0           0
AC240274.1   0           0           0            0           0
AC213203.1   0           0           0            0           0
FAM231C      0           0           0            0           0
            ILC:KT00180 ILC:KT00182 ILC:KT00190 ILC:KT00192 ILC:KT00193 ⋯
MIR1302-2HG  0           0          0           0           0           ⋯
FAM138A      0           0          0           0           0           ⋯
OR4F5        0           0          0           0           0           ⋯
AL627309.1   1           0          0           0           0           ⋯
AL627309.3   0           0          0           0           0           ⋯
AL627309.2   0           0          0           0           0           ⋯
AL627309.4   0           0          0           0           0           ⋯
AL732372.1   0           0          0           0           0           ⋯
OR4F29       0           0          0           0           0           ⋯
AC114498.1   0           0          0           0           0           ⋯
OR4F16       0           0          0           0           0           ⋯
AL669831.2   0           0          0           0           0           ⋯
AL669831.5   3           0          1           4           0           ⋯
FAM87B       0           0          0           0           0           ⋯
LINC00115    0           1          0           2           0           ⋯
FAM41C       3           1          1           0           0           ⋯
AL645608.7   0           0          0           0           0           ⋯
AL645608.3   0           0          0           0           0           ⋯
AL645608.5   0           0          0           0           0           ⋯
AL645608.1   0           0          0           0           0           ⋯
SAMD11       0           0          0           0           0           ⋯
NOC2L        7           4          0           1           2           ⋯
KLHL17       0           1          0           0           1           ⋯
PLEKHN1      0           1          0           0           0           ⋯
PERM1        0           0          0           0           0           ⋯
AL645608.8   0           0          0           0           0           ⋯
HES4         0           0          0           1           0           ⋯
ISG15       13          11          4           3           0           ⋯
AL645608.2   0           0          0           0           0           ⋯
AGRN         0           0          0           0           0           ⋯
⋮           ⋮           ⋮           ⋮           ⋮           ⋮           ⋱
MT-CYB      656         493         219         224         85          ⋯
AC133551.1    0           0           0           0          0          ⋯
AC136612.1    0           0           0           0          0          ⋯
AC136616.1    0           0           0           0          0          ⋯
AC136616.3    0           0           0           0          0          ⋯
AC136616.2    0           0           0           0          0          ⋯
AC141272.1    0           0           0           0          0          ⋯
AC136352.3    0           0           0           0          0          ⋯
AC136352.2    0           0           0           0          0          ⋯
AC171558.3    0           0           0           0          0          ⋯
AC171558.1    0           0           0           0          0          ⋯
BX004987.1    1           0           0           0          0          ⋯
AC145212.1    0           0           0           0          0          ⋯
MAFIP         0           0           0           0          0          ⋯
AC011841.1    0           0           0           0          0          ⋯
AC011043.1    0           0           0           0          0          ⋯
AC011043.2    0           0           0           0          0          ⋯
AL592183.1    2           2           1           5          0          ⋯
AC007325.1    0           0           0           0          0          ⋯
AC007325.4    0           0           0           0          0          ⋯
AC007325.2    0           0           0           0          0          ⋯
BX072566.1    0           0           0           0          0          ⋯
AL354822.1    0           0           0           0          0          ⋯
AC023491.2    0           0           0           0          0          ⋯
AC004556.1    0           0           0           0          0          ⋯
AC233755.2    0           0           0           0          0          ⋯
AC233755.1    0           0           0           0          0          ⋯
AC240274.1    1           1           1           0          1          ⋯
AC213203.1    0           0           0           0          0          ⋯
FAM231C       0           0           0           0          0          ⋯
            ILC:KT03991 ILC:KT03993 ILC:KT03994 ILC:KT03995 ILC:KT04345
MIR1302-2HG 0           0           0           0           0
FAM138A     0           0           0           0           0
OR4F5       0           0           0           0           0
AL627309.1  0           0           0           0           0
AL627309.3  0           0           0           0           0
AL627309.2  0           0           0           0           0
AL627309.4  0           0           0           0           0
AL732372.1  0           0           0           0           0
OR4F29      0           0           0           0           0
AC114498.1  0           0           0           0           0
OR4F16      0           0           0           0           0
AL669831.2  0           0           0           0           0
AL669831.5  1           1           0           1           0
FAM87B      0           0           0           0           0
LINC00115   0           1           0           0           0
FAM41C      0           0           0           0           0
AL645608.7  0           0           0           0           0
AL645608.3  0           0           0           0           0
AL645608.5  0           0           0           0           0
AL645608.1  0           0           0           0           0
SAMD11      0           0           0           0           0
NOC2L       1           0           2           0           0
KLHL17      0           0           0           0           0
PLEKHN1     0           2           0           1           0
PERM1       0           0           0           0           0
AL645608.8  0           0           0           0           0
HES4        0           0           0           0           0
ISG15       5           3           1           2           1
AL645608.2  0           0           0           0           0
AGRN        0           0           0           0           0
⋮           ⋮           ⋮           ⋮           ⋮           ⋮
MT-CYB      119         123         138         139         55
AC133551.1    0           0           0           0          0
AC136612.1    0           0           0           0          0
AC136616.1    0           0           0           0          0
AC136616.3    0           0           0           0          0
AC136616.2    0           0           0           0          0
AC141272.1    0           0           0           0          0
AC136352.3    0           0           0           0          0
AC136352.2    0           0           0           0          0
AC171558.3    0           0           0           0          0
AC171558.1    0           0           0           0          0
BX004987.1    0           0           0           0          0
AC145212.1    0           0           0           0          0
MAFIP         0           0           0           0          0
AC011841.1    0           0           0           0          0
AC011043.1    0           0           0           0          0
AC011043.2    0           0           0           0          0
AL592183.1    0           2           0           0          1
AC007325.1    0           0           0           0          0
AC007325.4    0           0           0           1          0
AC007325.2    0           0           0           0          0
BX072566.1    0           0           0           0          0
AL354822.1    0           0           0           0          0
AC023491.2    0           0           0           0          0
AC004556.1    0           0           0           0          0
AC233755.2    0           0           0           0          0
AC233755.1    0           0           0           0          0
AC240274.1    0           0           0           0          0
AC213203.1    0           0           0           0          0
FAM231C       0           0           0           0          0
            ILC:KT04348 ILC:KT04349 ILC:KT04351 ILC:KT04352 ILC:KT04356
MIR1302-2HG 0           0           0           0           0
FAM138A     0           0           0           0           0
OR4F5       0           0           0           0           0
AL627309.1  0           0           0           0           0
AL627309.3  0           0           0           0           0
AL627309.2  0           0           0           0           0
AL627309.4  0           0           0           0           0
AL732372.1  0           0           0           0           0
OR4F29      0           0           0           0           0
AC114498.1  0           0           0           0           0
OR4F16      0           0           0           0           0
AL669831.2  0           0           0           0           0
AL669831.5  0           0           1           0           0
FAM87B      0           0           0           0           0
LINC00115   0           0           0           0           1
FAM41C      0           0           1           0           0
AL645608.7  0           0           0           0           0
AL645608.3  0           0           0           0           0
AL645608.5  0           0           0           0           0
AL645608.1  0           0           0           0           0
SAMD11      0           0           0           0           0
NOC2L       0           3           2           2           0
KLHL17      0           0           0           0           0
PLEKHN1     0           0           0           0           0
PERM1       0           0           0           0           0
AL645608.8  0           0           0           0           0
HES4        0           0           0           1           2
ISG15       2           4           8           1           3
AL645608.2  0           0           0           0           0
AGRN        0           0           0           0           0
⋮           ⋮           ⋮           ⋮           ⋮           ⋮
MT-CYB      60          101         148         70          298
AC133551.1   0            0           0          0            0
AC136612.1   0            0           0          0            0
AC136616.1   0            0           0          0            0
AC136616.3   0            0           0          0            0
AC136616.2   0            0           0          0            0
AC141272.1   0            0           0          0            0
AC136352.3   0            0           0          0            0
AC136352.2   0            0           0          0            0
AC171558.3   0            0           0          0            0
AC171558.1   0            0           0          0            0
BX004987.1   0            0           0          0            1
AC145212.1   0            0           0          0            0
MAFIP        0            0           0          0            0
AC011841.1   0            0           0          0            0
AC011043.1   0            0           0          0            0
AC011043.2   0            0           0          0            0
AL592183.1   0            0           0          0            0
AC007325.1   0            0           0          0            0
AC007325.4   0            0           1          0            0
AC007325.2   0            0           0          0            0
BX072566.1   0            0           0          0            0
AL354822.1   0            0           0          0            0
AC023491.2   0            0           0          0            0
AC004556.1   0            0           2          0            0
AC233755.2   0            0           0          0            0
AC233755.1   0            0           0          0            0
AC240274.1   0            1           0          0            0
AC213203.1   0            0           0          0            0
FAM231C      0            0           0          0            0

In [13]:
celltypes <- unlist(lapply(df_list, function(x){
    gsub(":.*","", colnames(x)[1])
}))
names(df_list) <- celltypes

### Deseq analysis for only one sample

In [79]:
exp_matrix<-df_list[[69]]
exp_df <- as.data.frame(exp_matrix)
exp_df

            ASDC:KT00124 ASDC:KT00127 ASDC:KT00172 ASDC:KT00173 ASDC:KT00175
MIR1302-2HG  0           0            0            0            0
FAM138A      0           0            0            0            0
OR4F5        0           0            0            0            0
AL627309.1   0           0            0            0            0
AL627309.3   0           0            0            0            0
AL627309.2   0           0            0            0            0
AL627309.4   0           0            0            0            0
AL732372.1   0           0            0            0            0
OR4F29       0           0            0            0            0
AC114498.1   0           0            0            0            0
OR4F16       0           0            0            0            0
AL669831.2   0           0            0            0            0
AL669831.5   1           0            0            1            2
FAM87B       0           0            0            0            0
LINC00115    0           0            0            0            0
FAM41C       0           0            0            0            0
AL645608.7   0           0            0            0            0
AL645608.3   0           0            0            0            0
AL645608.5   0           0            0            0            0
AL645608.1   0           0            0            0            0
SAMD11       0           0            0            0            0
NOC2L        5           1            5            2            3
KLHL17       0           0            0            0            0
PLEKHN1      0           0            0            0            0
PERM1        0           0            0            0            0
AL645608.8   0           0            0            0            0
HES4         0           0            0            0            0
ISG15       10           3            2            0            2
AL645608.2   0           0            0            0            0
AGRN         0           0            0            0            0
⋮           ⋮            ⋮            ⋮            ⋮            ⋮
MT-CYB      258          73           186          96           159
AC133551.1    0           0             0           0             0
AC136612.1    0           0             0           0             0
AC136616.1    0           0             0           0             0
AC136616.3    0           0             0           0             0
AC136616.2    0           0             0           0             0
AC141272.1    0           0             0           0             0
AC136352.3    0           0             0           0             0
AC136352.2    0           0             0           0             0
AC171558.3    0           0             0           0             0
AC171558.1    0           0             0           0             0
BX004987.1    0           0             0           0             0
AC145212.1    0           0             0           0             0
MAFIP         0           0             0           0             0
AC011841.1    0           0             0           0             0
AC011043.1    0           0             0           0             0
AC011043.2    0           0             0           0             0
AL592183.1    1           0             1           0             0
AC007325.1    0           0             0           0             0
AC007325.4    0           0             0           0             0
AC007325.2    0           0             0           0             0
BX072566.1    0           0             0           0             0
AL354822.1    0           0             0           0             0
AC023491.2    0           0             0           0             0
AC004556.1    0           2             0           0             3
AC233755.2    0           0             0           0             0
AC233755.1    0           0             0           0             0
AC240274.1    0           1             0           0             0
AC213203.1    0           0             0           0             0
FAM231C       0           0             0           0             0
            ASDC:KT00180 ASDC:KT00182 ASDC:KT00190 ASDC:KT00192 ASDC:KT00193 ⋯
MIR1302-2HG 0             0           0            0             0           ⋯
FAM138A     0             0           0            0             0           ⋯
OR4F5       0             0           0            0             0           ⋯
AL627309.1  0             0           0            0             0           ⋯
AL627309.3  0             0           0            0             0           ⋯
AL627309.2  0             0           0            0             0           ⋯
AL627309.4  0             0           0            0             0           ⋯
AL732372.1  0             0           0            0             0           ⋯
OR4F29      0             0           0            0             0           ⋯
AC114498.1  0             0           0            0             0           ⋯
OR4F16      0             0           0            0             0           ⋯
AL669831.2  0             0           0            0             0           ⋯
AL669831.5  1             2           0            1             2           ⋯
FAM87B      0             0           0            1             0           ⋯
LINC00115   0             0           0            0             0           ⋯
FAM41C      0             0           0            0             0           ⋯
AL645608.7  0             0           0            0             0           ⋯
AL645608.3  0             0           0            0             0           ⋯
AL645608.5  0             0           0            0             0           ⋯
AL645608.1  0             0           0            0             0           ⋯
SAMD11      0             0           0            0             0           ⋯
NOC2L       2             7           0            1             4           ⋯
KLHL17      0             0           0            0             0           ⋯
PLEKHN1     0             0           0            0             0           ⋯
PERM1       0             0           0            0             0           ⋯
AL645608.8  0             0           0            0             0           ⋯
HES4        0             0           0            0             0           ⋯
ISG15       7            30           0            0            15           ⋯
AL645608.2  0             0           0            0             0           ⋯
AGRN        0             0           0            0             0           ⋯
⋮           ⋮            ⋮            ⋮            ⋮            ⋮            ⋱
MT-CYB      199          561          92           139          369          ⋯
AC133551.1    0            0           0             0            0          ⋯
AC136612.1    0            0           0             0            0          ⋯
AC136616.1    0            0           0             0            0          ⋯
AC136616.3    0            0           0             0            0          ⋯
AC136616.2    0            0           0             0            0          ⋯
AC141272.1    0            0           0             0            0          ⋯
AC136352.3    0            0           0             0            0          ⋯
AC136352.2    0            0           0             0            0          ⋯
AC171558.3    0            0           0             0            0          ⋯
AC171558.1    0            0           0             0            0          ⋯
BX004987.1    0            0           0             0            0          ⋯
AC145212.1    0            0           0             0            0          ⋯
MAFIP         0            0           0             0            0          ⋯
AC011841.1    0            0           0             0            0          ⋯
AC011043.1    0            0           0             0            0          ⋯
AC011043.2    0            0           0             0            0          ⋯
AL592183.1    0            1           0             0            5          ⋯
AC007325.1    0            0           0             0            0          ⋯
AC007325.4    0            0           0             0            0          ⋯
AC007325.2    0            0           0             0            0          ⋯
BX072566.1    0            0           0             0            0          ⋯
AL354822.1    0            0           0             0            0          ⋯
AC023491.2    0            0           0             0            0          ⋯
AC004556.1    0            0           0             0            4          ⋯
AC233755.2    0            0           0             0            0          ⋯
AC233755.1    0            0           0             0            0          ⋯
AC240274.1    0            0           0             1            0          ⋯
AC213203.1    0            0           0             0            0          ⋯
FAM231C       0            0           0             0            0          ⋯
            ASDC:KT03991 ASDC:KT03993 ASDC:KT03994 ASDC:KT03995 ASDC:KT04345
MIR1302-2HG 0            0            0            0            0
FAM138A     0            0            0            0            0
OR4F5       0            0            0            0            0
AL627309.1  0            0            0            0            0
AL627309.3  0            0            0            0            0
AL627309.2  0            0            0            0            0
AL627309.4  0            0            0            0            0
AL732372.1  0            0            0            0            0
OR4F29      0            0            0            0            0
AC114498.1  0            0            0            0            0
OR4F16      0            0            0            0            0
AL669831.2  0            0            0            0            0
AL669831.5  2            0            1            1            1
FAM87B      0            0            0            0            0
LINC00115   0            0            0            0            0
FAM41C      0            0            0            0            0
AL645608.7  0            0            0            0            0
AL645608.3  0            0            0            0            0
AL645608.5  0            0            0            0            0
AL645608.1  0            0            0            0            0
SAMD11      0            0            0            0            0
NOC2L       4            1            4            0            1
KLHL17      0            0            0            0            1
PLEKHN1     0            0            0            0            0
PERM1       0            0            0            0            0
AL645608.8  0            0            0            0            0
HES4        0            0            2            0            0
ISG15       9            3            5            1            9
AL645608.2  0            0            0            0            0
AGRN        0            0            0            0            0
⋮           ⋮            ⋮            ⋮            ⋮            ⋮
MT-CYB      311          233          456          132          157
AC133551.1    0            0            0            0            0
AC136612.1    0            0            0            0            0
AC136616.1    0            0            0            0            0
AC136616.3    0            0            0            0            0
AC136616.2    0            0            0            0            0
AC141272.1    0            0            0            0            0
AC136352.3    0            0            0            0            0
AC136352.2    0            0            0            0            0
AC171558.3    0            0            0            0            0
AC171558.1    0            0            0            0            0
BX004987.1    0            0            0            0            0
AC145212.1    0            0            0            0            0
MAFIP         0            0            0            0            0
AC011841.1    0            0            0            0            0
AC011043.1    1            0            0            0            0
AC011043.2    0            0            0            0            0
AL592183.1    0            1            5            0            0
AC007325.1    0            0            0            0            0
AC007325.4    0            0            1            0            0
AC007325.2    0            0            0            0            0
BX072566.1    0            0            0            0            0
AL354822.1    0            0            0            0            0
AC023491.2    0            0            0            0            0
AC004556.1    0            0            0            0            0
AC233755.2    0            0            0            0            0
AC233755.1    0            0            0            0            0
AC240274.1    0            0            2            0            0
AC213203.1    0            0            0            0            0
FAM231C       0            0            0            0            0
            ASDC:KT04348 ASDC:KT04349 ASDC:KT04351 ASDC:KT04352 ASDC:KT04356
MIR1302-2HG 0            0            0             0           0
FAM138A     0            0            0             0           0
OR4F5       0            0            0             0           0
AL627309.1  0            0            0             0           0
AL627309.3  0            0            0             0           0
AL627309.2  0            0            0             0           0
AL627309.4  0            0            0             0           0
AL732372.1  0            0            0             0           0
OR4F29      0            0            0             0           0
AC114498.1  0            0            0             0           0
OR4F16      0            0            0             0           0
AL669831.2  0            0            0             0           0
AL669831.5  4            3            1             0           1
FAM87B      0            0            0             0           0
LINC00115   1            1            0             0           0
FAM41C      1            0            2             1           0
AL645608.7  0            0            0             0           0
AL645608.3  0            0            0             0           0
AL645608.5  0            0            0             0           0
AL645608.1  0            0            0             0           0
SAMD11      0            0            0             0           0
NOC2L       5            4            0             2           2
KLHL17      0            0            0             0           0
PLEKHN1     0            0            0             0           0
PERM1       0            0            0             0           0
AL645608.8  0            0            0             0           0
HES4        0            0            0             0           0
ISG15       3            2            3            18           0
AL645608.2  0            0            0             0           0
AGRN        0            0            0             0           0
⋮           ⋮            ⋮            ⋮            ⋮            ⋮
MT-CYB      402          326          142          205          141
AC133551.1    0            0            0            0            0
AC136612.1    0            0            0            0            0
AC136616.1    0            0            0            0            0
AC136616.3    0            0            0            0            0
AC136616.2    0            0            0            0            0
AC141272.1    0            0            0            0            0
AC136352.3    0            0            0            0            0
AC136352.2    0            0            0            0            0
AC171558.3    0            0            0            0            0
AC171558.1    0            0            0            0            0
BX004987.1    0            0            0            1            0
AC145212.1    0            0            0            0            0
MAFIP         0            0            0            0            0
AC011841.1    0            0            0            0            0
AC011043.1    0            0            0            0            0
AC011043.2    0            0            0            0            0
AL592183.1    2            1            0            0            0
AC007325.1    0            0            0            0            0
AC007325.4    0            0            0            0            0
AC007325.2    0            0            0            0            0
BX072566.1    0            0            0            0            0
AL354822.1    0            0            0            0            0
AC023491.2    0            0            0            0            0
AC004556.1    0            0            1            0            0
AC233755.2    0            0            0            0            0
AC233755.1    0            0            0            0            0
AC240274.1    3            0            0            1            0
AC213203.1    0            0            0            0            0
FAM231C       0            0            0            0            0

In [80]:
#rename colnames to only be the kitID
colnames(exp_df) <- gsub(".*:", "", colnames(exp_df))
head(exp_df)

            KT00124 KT00127 KT00172 KT00173 KT00175 KT00180 KT00182 KT00190
MIR1302-2HG 0       0       0       0       0       0       0       0
FAM138A     0       0       0       0       0       0       0       0
OR4F5       0       0       0       0       0       0       0       0
AL627309.1  0       0       0       0       0       0       0       0
AL627309.3  0       0       0       0       0       0       0       0
AL627309.2  0       0       0       0       0       0       0       0
            KT00192 KT00193 ⋯ KT03991 KT03993 KT03994 KT03995 KT04345 KT04348
MIR1302-2HG 0       0       ⋯ 0       0       0       0       0       0
FAM138A     0       0       ⋯ 0       0       0       0       0       0
OR4F5       0       0       ⋯ 0       0       0       0       0       0
AL627309.1  0       0       ⋯ 0       0       0       0       0       0
AL627309.3  0       0       ⋯ 0       0       0       0       0       0
AL627309.2  0       0       ⋯ 0       0       0       0       0       0
            KT04349 KT04351 KT04352 KT04356
MIR1302-2HG 0       0       0       0
FAM138A     0       0       0       0
OR4F5       0       0       0       0
AL627309.1  0       0       0       0
AL627309.3  0       0       0       0
AL627309.2  0       0       0       0

In [81]:
meta_data_subset=meta_data %>% filter(sample.sampleKitGuid	 %in% colnames(exp_df),
                                      sample.visitName %in% c('Flu Year 1 Pre-Vac 7-12 Weeks',
                                                              'Flu Year 1 Day 7'))

In [82]:
dim(meta_data_subset)
dim(exp_df)

[1] 83 33

[1] 33538   214

In [83]:
#looking at the metadata
unique(meta_data_subset$sample.visitName)

[1] "Flu Year 1 Pre-Vac 7-12 Weeks" "Flu Year 1 Day 7"

In [84]:
rownames(meta_data_subset)<-meta_data_subset$sample.sampleKitGuid
#head(meta_data_subset)
dim(meta_data_subset)

[1] 83 33

In [86]:
#Get only 1 cell from df_list
celltype<-celltypes[[69]]
celltype

[1] "ASDC"

In [87]:
dim(exp_df)

[1] 33538   214

In [88]:
length(unique(rownames(meta_data_subset)))
length(unique(colnames(exp_df)))

[1] 83

[1] 214

In [89]:
#now subset exp_df so that its colnames matches the rows on meta data
exp_df <- exp_df[, rownames(meta_data_subset)]
dim(exp_df)

[1] 33538    83

In [92]:
rownames(meta_data_subset)
colnames(exp_df)

 [1] "KT00809" "KT00813" "KT00815" "KT00824" "KT00828" "KT00852" "KT00897"
 [8] "KT00172" "KT00173" "KT00197" "KT00807" "KT00811" "KT00847" "KT00848"
[15] "KT00886" "KT00841" "KT00842" "KT00853" "KT00190" "KT00192" "KT00124"
[22] "KT00175" "KT00180" "KT00193" "KT00182" "KT00127" "KT00199" "KT00810"
[29] "KT00921" "KT00925" "KT00924" "KT00937" "KT00961" "KT00958" "KT00913"
[36] "KT00927" "KT00914" "KT00931" "KT00928" "KT02390" "KT00884" "KT00889"
[43] "KT00910" "KT00833" "KT00892" "KT00907" "KT00825" "KT00879" "KT00882"
[50] "KT03254" "KT03255" "KT03965" "KT03250" "KT03223" "KT02372" "KT02939"
[57] "KT02391" "KT02901" "KT02392" "KT03950" "KT03948" "KT03993" "KT03963"
[64] "KT03020" "KT03036" "KT03253" "KT02415" "KT03974" "KT03951" "KT03984"
[71] "KT04348" "KT03958" "KT03994" "KT03969" "KT03989" "KT03988" "KT03985"
[78] "KT03979" "KT03976" "KT03970" "KT04356" "KT03982" "KT03986"

 [1] "KT00809" "KT00813" "KT00815" "KT00824" "KT00828" "KT00852" "KT00897"
 [8] "KT00172" "KT00173" "KT00197" "KT00807" "KT00811" "KT00847" "KT00848"
[15] "KT00886" "KT00841" "KT00842" "KT00853" "KT00190" "KT00192" "KT00124"
[22] "KT00175" "KT00180" "KT00193" "KT00182" "KT00127" "KT00199" "KT00810"
[29] "KT00921" "KT00925" "KT00924" "KT00937" "KT00961" "KT00958" "KT00913"
[36] "KT00927" "KT00914" "KT00931" "KT00928" "KT02390" "KT00884" "KT00889"
[43] "KT00910" "KT00833" "KT00892" "KT00907" "KT00825" "KT00879" "KT00882"
[50] "KT03254" "KT03255" "KT03965" "KT03250" "KT03223" "KT02372" "KT02939"
[57] "KT02391" "KT02901" "KT02392" "KT03950" "KT03948" "KT03993" "KT03963"
[64] "KT03020" "KT03036" "KT03253" "KT02415" "KT03974" "KT03951" "KT03984"
[71] "KT04348" "KT03958" "KT03994" "KT03969" "KT03989" "KT03988" "KT03985"
[78] "KT03979" "KT03976" "KT03970" "KT04356" "KT03982" "KT03986"

In [91]:
meta_data_subset <-meta_data_subset[match(colnames(exp_df),rownames(meta_data_subset)),] #order
#meta_data_subset

In [95]:
length(filtered_gene_set_filtered)

[1] 6962

In [94]:
#Now working on the filtered_gene_set
filtered_gene_set_filtered<-filtered_gene_set%>% filter(AIFI_L3==celltype)%>% select(gene) %>%pull()

In [99]:
dim(exp_df)

[1] 6962   83

In [97]:
#filtered_gene_set_filtered <- filtered_gene_set_filtered[filtered_gene_set_filtered %in% rownames(exp_df)]
length(filtered_gene_set_filtered)

[1] 6962

In [98]:
exp_df <- exp_df[filtered_gene_set_filtered,]

In [100]:
res=deseq2_analysis(exp_df,
                 meta_data=meta_data_subset,
                 filtered_gene_set=filtered_gene_set_filtered,#rownames(exp_matrix),
                 #add visit to formula
                 formula= ~ sample.visitName,#+subject.race,#subject.biologicalSex+subject.race,
                 comparisons=list(c('sample.visitName', "Flu Year 1 Pre-Vac 7-12 Weeks", "Flu Year 1 Day 7")),
                                  #c("subject.race", "Caucasian", "African American", "Asian")),
                  celltype=celltype)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

-- replacing outliers and refitting for 5 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

estimating dispersions

fitting model and testing

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

In [101]:
res

     baseMean    log2FoldChange lfcSE      stat          pvalue       padj
1     2.4798455  -0.7957567     0.2433718  -3.269717     0.0010765528 0.7030648
2     1.9231031  -0.8830772     0.2631174  -3.356210     0.0007901861 0.7030648
3     6.8855911   0.4660892     0.1297433   3.592395     0.0003276527 0.7030648
4     1.8419689  -0.8461319     0.2608035  -3.244327     0.0011772846 0.7030648
5     0.8105763  -1.2494042     0.3618816  -3.452522     0.0005553727 0.7030648
6     1.1900800  -0.9256112     0.2857731  -3.238973     0.0011996111 0.7030648
7    10.2733591  -0.4539311     0.1274155  -3.562605     0.0003671927 0.7030648
8     7.8632250   0.4594670     0.1350958   3.401046     0.0006712849 0.7030648
9     9.4487901  -0.3679180     0.1113851  -3.303118     0.0009561630 0.7030648
10    4.3330815  -0.6350138     0.1643897  -3.862855     0.0001120694 0.7030648
11    3.6349465  -0.5943967     0.1836780  -3.236080     0.0012118325 0.7030648
12   10.8757371  -0.6389565     0.1869219  -3.418307     0.0006301192 0.7030648
13    1.4892507  -0.8594428     0.2779087  -3.092537     0.0019845343 0.7670807
14    1.6973764  -1.6103561     0.5793730  -2.779481     0.0054445871 0.7670807
15    0.8160695  -1.0097460     0.3542549  -2.850337     0.0043672898 0.7670807
16    0.7365763  -1.0446587     0.3747896  -2.787321     0.0053145840 0.7670807
17    5.2020474  -0.5544699     0.1883737  -2.943456     0.0032456965 0.7670807
18    3.4746965  -0.4840615     0.1706423  -2.836703     0.0045582003 0.7670807
19   12.3133269  -0.5247671     0.1791132  -2.929807     0.0033917205 0.7670807
20    9.4011699  -0.3017479     0.1082776  -2.786800     0.0053231315 0.7670807
21    1.8405191   0.7576574     0.2634392   2.876024     0.0040271863 0.7670807
22    3.2890845  -0.5904965     0.1955077  -3.020323     0.0025250513 0.7670807
23    0.9404421  -1.0813667     0.3618138  -2.988738     0.0028013229 0.7670807
24    1.1361130   1.0439072     0.3645626   2.863451     0.0041905357 0.7670807
25    1.4899481  -0.7639868     0.2752455  -2.775656     0.0055090541 0.7670807
26    2.3253319  -0.7781392     0.2514555  -3.094540     0.0019711803 0.7670807
27    0.5981776  -1.1482969     0.4125720  -2.783264     0.0053814937 0.7670807
28    7.4181478  -0.3979075     0.1325227  -3.002561     0.0026771861 0.7670807
29    0.6424479  -1.3336042     0.4535798  -2.940175     0.0032802654 0.7670807
30    3.1670525  -0.6620140     0.2239847  -2.955621     0.0031204047 0.7670807
⋮    ⋮           ⋮              ⋮          ⋮             ⋮            ⋮
6933   1.0314730 -1.814032e-03  0.30258440 -0.0059951275 0.9952166    0.9992928
6934   6.3552264 -7.539847e-04  0.13577589 -0.0055531563 0.9955692    0.9992928
6935 263.0706426  2.280186e-03  0.06890762  0.0330904794 0.9736024    0.9992928
6936   5.5430594 -1.814322e-03  0.16377314 -0.0110782621 0.9911610    0.9992928
6937  11.1130014  2.611364e-03  0.10693085  0.0244210543 0.9805168    0.9992928
6938   1.3090968  9.147634e-03  0.28442657  0.0321616707 0.9743431    0.9992928
6939   0.5614231  1.908798e-03  0.42045320  0.0045398587 0.9963777    0.9992928
6940   7.1918432 -3.175863e-03  0.12767873 -0.0248738577 0.9801556    0.9992928
6941   1.1369806  4.012835e-03  0.29889928  0.0134253737 0.9892884    0.9992928
6942   1.8686185  2.941162e-03  0.24498348  0.0120055528 0.9904212    0.9992928
6943   1.0975469  5.145297e-03  0.38311491  0.0134301662 0.9892846    0.9992928
6944   1.4472144 -7.633150e-03  0.26915201 -0.0283599982 0.9773750    0.9992928
6945  12.9896492  3.268043e-03  0.11116889  0.0293971037 0.9765479    0.9992928
6946   0.6951509 -1.410693e-02  0.39744908 -0.0354936808 0.9716861    0.9992928
6947   3.5717017 -4.127360e-03  0.18228619 -0.0226421990 0.9819357    0.9992928
6948   5.4693294  5.149151e-03  0.15078058  0.0341499633 0.9727576    0.9992928
6949   3.3448271 -2.959734e-03  0.21295060 -0.0138986880 0.9889108    0.9992928
6950   0.5237731  1.398367e-02  0.40618607  0.0344267640 0.9725368    0.9992928
6951   1.8825329 -6.524117e-04  0.25141461 -0.0025949632 0.9979295    0.9995088
6952   1.7568643  9.489967e-05  0.25319193  0.0003748132 0.9997009    0.9997009
6953   0.8528712  6.858907e-04  0.34550041  0.0019852094 0.9984160    0.9997009
6954   5.4321698  2.838331e-04  0.17552970  0.0016170092 0.9987098    0.9997009
6955   2.1552195 -1.067637e-04  0.22027726 -0.0004846789 0.9996133    0.9997009
6956   3.4524805  8.061762e-05  0.19092521  0.0004222471 0.9996631    0.9997009
6957   2.4918082 -3.403686e-04  0.21847384 -0.0015579378 0.9987569    0.9997009
6958 240.4274944  2.727679e-05  0.04902425  0.0005563938 0.9995561    0.9997009
6959   3.4982778 -1.492258e-04  0.18518696 -0.0008058116 0.9993571    0.9997009
6960   0.6479458  2.816648e-04  0.36788881  0.0007656249 0.9993891    0.9997009
6961   1.0757595  1.198339e-04  0.30334808  0.0003950377 0.9996848    0.9997009
6962   1.7013259  1.083975e-04  0.25800451  0.0004201380 0.9996648    0.9997009
     contrast         Direction                             gene      celltype
1    sample.visitName HigherInFlu Year 1 Day 7              PRDM2     ASDC
2    sample.visitName HigherInFlu Year 1 Day 7              EVI5      ASDC
3    sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks TSTD1     ASDC
4    sample.visitName HigherInFlu Year 1 Day 7              CASP8     ASDC
5    sample.visitName HigherInFlu Year 1 Day 7              FAM193A   ASDC
6    sample.visitName HigherInFlu Year 1 Day 7              RAB6A     ASDC
7    sample.visitName HigherInFlu Year 1 Day 7              AKAP13    ASDC
8    sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks CKLF      ASDC
9    sample.visitName HigherInFlu Year 1 Day 7              EVI2B     ASDC
10   sample.visitName HigherInFlu Year 1 Day 7              CHCHD10   ASDC
11   sample.visitName HigherInFlu Year 1 Day 7              USP16     ASDC
12   sample.visitName HigherInFlu Year 1 Day 7              MT-ND4L   ASDC
13   sample.visitName HigherInFlu Year 1 Day 7              CDC14A    ASDC
14   sample.visitName HigherInFlu Year 1 Day 7              S100A8    ASDC
15   sample.visitName HigherInFlu Year 1 Day 7              SLC1A4    ASDC
16   sample.visitName HigherInFlu Year 1 Day 7              KDM3A     ASDC
17   sample.visitName HigherInFlu Year 1 Day 7              MAP4K4    ASDC
18   sample.visitName HigherInFlu Year 1 Day 7              WDR33     ASDC
19   sample.visitName HigherInFlu Year 1 Day 7              ZEB2      ASDC
20   sample.visitName HigherInFlu Year 1 Day 7              SF3B1     ASDC
21   sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks CTDSP1    ASDC
22   sample.visitName HigherInFlu Year 1 Day 7              INPP5D    ASDC
23   sample.visitName HigherInFlu Year 1 Day 7              SNRK      ASDC
24   sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks CCR2      ASDC
25   sample.visitName HigherInFlu Year 1 Day 7              TOPBP1    ASDC
26   sample.visitName HigherInFlu Year 1 Day 7              PHC3      ASDC
27   sample.visitName HigherInFlu Year 1 Day 7              YEATS2    ASDC
28   sample.visitName HigherInFlu Year 1 Day 7              ACAP2     ASDC
29   sample.visitName HigherInFlu Year 1 Day 7              RELL1     ASDC
30   sample.visitName HigherInFlu Year 1 Day 7              LNPEP     ASDC
⋮    ⋮                ⋮                                     ⋮         ⋮
6933 sample.visitName HigherInFlu Year 1 Day 7              SF3A2     ASDC
6934 sample.visitName HigherInFlu Year 1 Day 7              MAP2K2    ASDC
6935 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks RPS28     ASDC
6936 sample.visitName HigherInFlu Year 1 Day 7              ICAM3     ASDC
6937 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks CDKN2D    ASDC
6938 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks ZNF430    ASDC
6939 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks ZNF675    ASDC
6940 sample.visitName HigherInFlu Year 1 Day 7              UQCRFS1   ASDC
6941 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks PLD3      ASDC
6942 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks GSK3A     ASDC
6943 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks APOC1     ASDC
6944 sample.visitName HigherInFlu Year 1 Day 7              GEMIN7    ASDC
6945 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks NOP53     ASDC
6946 sample.visitName HigherInFlu Year 1 Day 7              CCDC106   ASDC
6947 sample.visitName HigherInFlu Year 1 Day 7              ATP6V1E1  ASDC
6948 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks TXN2      ASDC
6949 sample.visitName HigherInFlu Year 1 Day 7              EP300     ASDC
6950 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks IL10RB-DT ASDC
6951 sample.visitName HigherInFlu Year 1 Day 7              DIDO1     ASDC
6952 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks ELOVL1    ASDC
6953 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks ARNT      ASDC
6954 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks GLUL      ASDC
6955 sample.visitName HigherInFlu Year 1 Day 7              PSMB8-AS1 ASDC
6956 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks FBXO9     ASDC
6957 sample.visitName HigherInFlu Year 1 Day 7              HCCS      ASDC
6958 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks RPS13     ASDC
6959 sample.visitName HigherInFlu Year 1 Day 7              BRI3BP    ASDC
6960 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks RALGAPA1  ASDC
6961 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks ZNF480    ASDC
6962 sample.visitName HigherInFlu Year 1 Pre-Vac 7-12 Weeks TPST2     ASDC

### deseq loop

In [39]:
meta_data %>% filter( sample.visitName %in% c('Flu Year 2 Pre-Vac 7-12 Weeks','Flu Year 2 Day 7'))

   X   Unnamed..0.1 Unnamed..0 lastUpdated
1   47  47           48        2024-08-17T13:57:19.462Z
2   48  48           49        2024-08-17T13:57:19.462Z
3   51  51           52        2024-08-17T13:57:19.462Z
4   84  84           85        2024-08-17T13:57:19.462Z
5   85  85           86        2024-08-17T13:57:19.462Z
6   86  86           87        2024-08-17T13:57:19.462Z
7   87  87           88        2024-08-17T13:57:19.462Z
8   88  88           89        2024-08-17T13:57:19.462Z
9   89  89           90        2024-08-17T13:57:19.462Z
10  90  90           91        2024-08-17T13:57:19.462Z
11  91  91           92        2024-08-17T13:57:19.462Z
12  94  94           95        2024-08-17T13:57:19.462Z
13  95  95           96        2024-08-17T13:57:19.462Z
14  96  96           97        2024-08-17T13:57:19.462Z
15  97  97           98        2024-08-17T13:57:19.462Z
16  98  98           99        2024-08-17T13:57:19.462Z
17  99  99          100        2024-08-17T13:57:19.462Z
18 100 100          101        2024-08-17T13:57:19.462Z
19 104 104          105        2024-08-17T13:57:19.462Z
20 105 105          106        2024-08-17T13:57:19.462Z
21 106 106          107        2024-08-17T13:57:19.462Z
22 107 107          108        2024-08-17T13:57:19.462Z
23 108 108          109        2024-08-17T13:57:19.462Z
24 109 109          110        2024-08-17T13:57:19.462Z
25 121 121          122        2024-08-17T13:57:19.462Z
26 123 123          124        2024-08-17T13:57:19.462Z
27 124 124          125        2024-08-17T13:57:19.462Z
28 126 126          127        2024-08-17T13:57:19.462Z
29 152 152          153        2024-08-17T13:57:19.462Z
30 156 156          157        2024-08-17T13:57:19.462Z
31 194 194          195        2024-08-17T13:57:19.462Z
32 197 197          198        2024-08-17T13:57:19.462Z
33 199 199          200        2024-08-17T13:57:19.462Z
34 201 201          202        2024-08-17T13:57:19.462Z
   sample.id                            sample.bridgingControl
1  45440bf3-f13a-40a6-a56c-56fdbb66b332 False
2  9f091af2-be70-4e87-9456-f41ac1ff73af False
3  cbffe35e-b428-42d3-9127-6c841347bb0e False
4  323d20ee-e555-4664-94f4-79ae84a86181 False
5  3eccd3e2-d1de-4a10-9edb-b9e634197f77 False
6  e8489fd4-02a6-4013-8fab-e4acdeaa8d9d False
7  9f2088a3-6c91-47ae-8d26-4dde9bc05072 False
8  da5f10f0-facd-4ac2-baaa-e86c390e1252 False
9  4f30d6d0-bc17-4041-affc-37ae3a2933b8 False
10 b62c1dd8-d559-481d-91ec-121aa6bc4a36 False
11 78d2ed0e-3085-4d26-8baa-04dd89efe072 False
12 fb9ac004-a8af-42d8-87d9-f1eb5910d3b4 False
13 17dc7a48-9d9e-445d-826c-c73cbd0d45d0 False
14 9b7608c6-2434-4711-a498-39c2e7be635b False
15 8bfbaa64-d42c-456f-9a3c-e91ce35ded0a False
16 7918c2a0-921f-4943-8081-d17e76e6fa9e False
17 a33a7ab3-ae5e-4c8b-bfba-4d5c61ff521d False
18 9ed85bff-6ffb-4e6c-a4a0-9cb8a8d7a2fc False
19 c0a31e9b-d5fb-41bc-94e5-4adcceeba3b6 False
20 0e6f0ef1-19bf-4042-ae7b-079a6ee0412f False
21 3d219199-3d9e-4d16-b4e1-4b926672bbd5 False
22 73adfb49-a6e7-4e5d-ab3b-fd404c46ff21 False
23 b0a75a62-6fb4-4ad8-a0d5-987969097d6d False
24 88bd9251-5eeb-4f3a-bcc0-30f58962f06d False
25 b45501bb-4ef5-419c-b5b4-054b2168eeb0 False
26 2bf79285-08f7-4f3c-9894-99439928a8f9 False
27 cab34f0f-1e81-4055-a39a-8e7d0aa1b4ef False
28 7e79f2ab-db2e-4539-bcc2-25d3513989fb False
29 66d883f7-07e9-46bb-a55f-8ab735c983fa False
30 f35b2788-8d40-4059-a6f6-423f24bfe1fc False
31 f96a83a9-cede-44e8-bfff-f0de56421992 False
32 700550dd-ec68-4151-b308-bb817ae37478 False
33 1886af21-fda4-46b0-b11b-5f40c9507ea4 False
34 753b6d21-1778-40b7-b479-50c6da9c5e3b False
   sample.sampleKitGuid sample.visitName
1  KT02374              Flu Year 2 Pre-Vac 7-12 Weeks
2  KT02379              Flu Year 2 Pre-Vac 7-12 Weeks
3  KT02380              Flu Year 2 Pre-Vac 7-12 Weeks
4  KT02416              Flu Year 2 Day 7
5  KT02394              Flu Year 2 Pre-Vac 7-12 Weeks
6  KT02387              Flu Year 2 Pre-Vac 7-12 Weeks
7  KT02410              Flu Year 2 Day 7
8  KT02385              Flu Year 2 Pre-Vac 7-12 Weeks
9  KT02381              Flu Year 2 Pre-Vac 7-12 Weeks
10 KT02400              Flu Year 2 Day 7
11 KT02417              Flu Year 2 Day 7
12 KT03003              Flu Year 2 Day 7
13 KT03023              Flu Year 2 Day 7
14 KT02924              Flu Year 2 Day 7
15 KT02389              Flu Year 2 Pre-Vac 7-12 Weeks
16 KT02393              Flu Year 2 Pre-Vac 7-12 Weeks
17 KT02411              Flu Year 2 Pre-Vac 7-12 Weeks
18 KT02940              Flu Year 2 Day 7
19 KT02405              Flu Year 2 Pre-Vac 7-12 Weeks
20 KT03013              Flu Year 2 Day 7
21 KT03249              Flu Year 2 Day 7
22 KT02386              Flu Year 2 Pre-Vac 7-12 Weeks
23 KT02636              Flu Year 2 Pre-Vac 7-12 Weeks
24 KT02658              Flu Year 2 Day 7
25 KT02396              Flu Year 2 Pre-Vac 7-12 Weeks
26 KT02656              Flu Year 2 Day 7
27 KT02661              Flu Year 2 Day 7
28 KT02933              Flu Year 2 Day 7
29 KT02996              Flu Year 2 Pre-Vac 7-12 Weeks
30 KT03018              Flu Year 2 Day 7
31 KT02413              Flu Year 2 Pre-Vac 7-12 Weeks
32 KT02640              Flu Year 2 Day 7
33 KT02930              Flu Year 2 Day 7
34 KT02399              Flu Year 2 Pre-Vac 7-12 Weeks
   sample.visitDetails             sample.drawDate      ⋯ file.userTags.details
1  N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
2  N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
3  N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
4  N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
5  N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
6  N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
7  N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
8  N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
9  N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
10 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
11 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
12 N/A - Flu-Series Timepoint Only 2021-11-01T00:00:00Z ⋯ NA
13 N/A - Flu-Series Timepoint Only 2021-12-01T00:00:00Z ⋯ NA
14 N/A - Flu-Series Timepoint Only 2021-11-01T00:00:00Z ⋯ NA
15 N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
16 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
17 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
18 N/A - Flu-Series Timepoint Only 2021-11-01T00:00:00Z ⋯ NA
19 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
20 N/A - Flu-Series Timepoint Only 2021-12-01T00:00:00Z ⋯ NA
21 N/A - Flu-Series Timepoint Only 2022-02-01T00:00:00Z ⋯ NA
22 N/A - Flu-Series Timepoint Only 2021-08-01T00:00:00Z ⋯ NA
23 N/A - Flu-Series Timepoint Only 2021-10-01T00:00:00Z ⋯ NA
24 N/A - Flu-Series Timepoint Only 2021-10-01T00:00:00Z ⋯ NA
25 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
26 N/A - Flu-Series Timepoint Only 2021-10-01T00:00:00Z ⋯ NA
27 N/A - Flu-Series Timepoint Only 2021-10-01T00:00:00Z ⋯ NA
28 N/A - Flu-Series Timepoint Only 2021-11-01T00:00:00Z ⋯ NA
29 N/A - Flu-Series Timepoint Only 2021-11-01T00:00:00Z ⋯ NA
30 N/A - Flu-Series Timepoint Only 2021-12-01T00:00:00Z ⋯ NA
31 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
32 N/A - Flu-Series Timepoint Only 2021-10-01T00:00:00Z ⋯ NA
33 N/A - Flu-Series Timepoint Only 2021-11-01T00:00:00Z ⋯ NA
34 N/A - Flu-Series Timepoint Only 2021-09-01T00:00:00Z ⋯ NA
   file.userTags.group file.userTags.name file.userTags.origin
1  NA                  NA                 NA
2  NA                  NA                 NA
3  NA                  NA                 NA
4  NA                  NA                 NA
5  NA                  NA                 NA
6  NA                  NA                 NA
7  NA                  NA                 NA
8  NA                  NA                 NA
9  NA                  NA                 NA
10 NA                  NA                 NA
11 NA                  NA                 NA
12 NA                  NA                 NA
13 NA                  NA                 NA
14 NA                  NA                 NA
15 NA                  NA                 NA
16 NA                  NA                 NA
17 NA                  NA                 NA
18 NA                  NA                 NA
19 NA                  NA                 NA
20 NA                  NA                 NA
21 NA                  NA                 NA
22 NA                  NA                 NA
23 NA                  NA                 NA
24 NA                  NA                 NA
25 NA                  NA                 NA
26 NA                  NA                 NA
27 NA                  NA                 NA
28 NA                  NA                 NA
29 NA                  NA                 NA
30 NA                  NA                 NA
31 NA                  NA                 NA
32 NA                  NA                 NA
33 NA                  NA                 NA
34 NA                  NA                 NA
   file.userTags.other file.userTags.version specimens.specimenType
1  NA                  NA                    Plasma
2  NA                  NA                    Plasma
3  NA                  NA                    PBMC
4  NA                  NA                    Plasma
5  NA                  NA                    PBMC
6  NA                  NA                    PBMC
7  NA                  NA                    PBMC
8  NA                  NA                    Plasma
9  NA                  NA                    Plasma
10 NA                  NA                    PBMC
11 NA                  NA                    Plasma
12 NA                  NA                    PBMC
13 NA                  NA                    Plasma
14 NA                  NA                    PBMC
15 NA                  NA                    Plasma
16 NA                  NA                    PBMC
17 NA                  NA                    PBMC
18 NA                  NA                    Plasma
19 NA                  NA                    Plasma
20 NA                  NA                    Plasma
21 NA                  NA                    PBMC
22 NA                  NA                    PBMC
23 NA                  NA                    PBMC
24 NA                  NA                    PBMC
25 NA                  NA                    Plasma
26 NA                  NA                    PBMC
27 NA                  NA                    PBMC
28 NA                  NA                    Plasma
29 NA                  NA                    PBMC
30 NA                  NA                    Plasma
31 NA                  NA                    Plasma
32 NA                  NA                    PBMC
33 NA                  NA                    Plasma
34 NA                  NA                    Plasma
   specimens.specimenGuid cmv_status relabeled_visit
1  PL02374-020            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
2  PL02379-002            Positive   Flu Year 2 Pre-Vac 7-12 Weeks
3  PB02380-011            Positive   Flu Year 2 Pre-Vac 7-12 Weeks
4  PL02416-003            Negative   Flu Year 2 Day 7
5  PB02394-002            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
6  PB02387-001            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
7  PB02410-009            Negative   Flu Year 2 Day 7
8  PL02385-016            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
9  PL02381-010            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
10 PB02400-002            Negative   Flu Year 2 Day 7
11 PL02417-006            Negative   Flu Year 2 Day 7
12 PB03003-012            Negative   Flu Year 2 Day 7
13 PL03023-002            Negative   Flu Year 2 Day 7
14 PB02924-004            Negative   Flu Year 2 Day 7
15 PL02389-011            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
16 PB02393-005            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
17 PB02411-001            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
18 PL02940-006            Negative   Flu Year 2 Day 7
19 PL02405-012            Positive   Flu Year 2 Pre-Vac 7-12 Weeks
20 PL03013-016            Positive   Flu Year 2 Day 7
21 PB03249-010            Positive   Flu Year 2 Day 7
22 PB02386-005            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
23 PB02636-011            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
24 PB02658-126            Negative   Flu Year 2 Day 7
25 PL02396-012            Positive   Flu Year 2 Pre-Vac 7-12 Weeks
26 PB02656-060            Negative   Flu Year 2 Day 7
27 PB02661-133            Positive   Flu Year 2 Day 7
28 PL02933-019            Positive   Flu Year 2 Day 7
29 PB02996-005            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
30 PL03018-017            Negative   Flu Year 2 Day 7
31 PL02413-006            Negative   Flu Year 2 Pre-Vac 7-12 Weeks
32 PB02640-032            Negative   Flu Year 2 Day 7
33 PL02930-015            Positive   Flu Year 2 Day 7
34 PL02399-011            Positive   Flu Year 2 Pre-Vac 7-12 Weeks

In [20]:
res_list <- lapply(celltypes, function(celltype){
    print(celltype)
    celltype_list <- lapply(df_list, function(df) { df <- df[, grep(celltype, names(df), fixed = TRUE),drop=FALSE] })
    exp_matrix<-do.call(cbind,celltype_list)
    colnames(exp_matrix)<-gsub(".*:","",colnames(exp_matrix))
    #print(exp_matrix)

    meta_data_subset=meta_data %>% filter(sample.sampleKitGuid	 %in% colnames(exp_matrix),
                                       sample.visitName %in% c('Flu Year 2 Pre-Vac 7-12 Weeks',
                                                               'Flu Year 2 Day 90'))
    rownames(meta_data_subset)<-meta_data_subset$sample.sampleKitGuid
    print(nrow(meta_data_subset))
    
    exp_matrix <- exp_matrix[, rownames(meta_data_subset)] #subsetting exp_matrix so that column matches rownames(meta_data_subset)  
    # print(dim(exp_matrix))
    # print(dim(meta_data_subset))
    filtered_gene_set_filtered<-filtered_gene_set%>% filter(AIFI_L3==celltype)%>% select(gene) %>%pull()
    res=deseq2_analysis(exp_matrix,
                     meta_data=meta_data_subset,
                     filtered_gene_set=filtered_gene_set_filtered,
                     formula= ~ subject.subjectGuid+sample.visitName,   #+cmv_status+subject.biologicalSex,
                     comparisons=list(c('sample.visitName', "Flu Year 2 Day 90", "Flu Year 2 Pre-Vac 7-12 Weeks")),
                                      # c('cmv_status', 'Positive','Negative'),
                                      # c('subject.biologicalSex', 'Male','Female')),
                     celltype=celltype)
    return(res)
})

[1] "ILC"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMK- CD27+ EM CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "KLRB1+ memory CD4 Treg"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD14+ cDC2"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD95 memory B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Proliferating T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ memory CD4 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ CD14 monocyte"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "SOX4+ naive CD4 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Core CD16 monocyte"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ memory CD8 T cell"
[1] 34

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Core naive B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD27- effector B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "KLRF1- GZMB+ CD27- memory CD4 T cell"
[1] 32

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "BaEoMaP cell"
[1] 16

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Early memory B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "KLRB1+ memory CD8 Treg"
[1] 24

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMK+ Vd2 gdT"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Adaptive NK cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "pDC"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMB+ Vd2 gdT"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMK+ CD56dim NK cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "KLRF1- GZMB+ CD27- EM CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "KLRF1- effector Vd1 gdT"
[1] 27

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Proliferating NK cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "DN T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMB- CD27- EM CD4 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Type 2 polarized memory B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Plasma cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ CD56dim NK cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Core memory B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD8 MAIT"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "C1Q+ CD16 monocyte"
[1] 34

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Intermediate monocyte"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMK- CD56dim NK cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ CD16 monocyte"
[1] 34

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD8aa"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "IL1B+ CD14 monocyte"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMK+ CD27+ EM CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Platelet"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Transitional B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ naive B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ naive CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Memory CD4 Treg"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "KLRF1+ GZMB+ CD27- EM CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "HLA-DRhi cDC2"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "SOX4+ Vd1 gdT"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CM CD4 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Naive Vd1 gdT"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Core CD14 monocyte"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "SOX4+ naive CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD56bright NK cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Erythrocyte"
[1] 12

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD4 MAIT"
[1] 27

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMB- CD27+ EM CD4 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ cDC2"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "KLRF1+ effector Vd1 gdT"
[1] 29

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Core naive CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "GZMK+ memory CD4 Treg"
[1] 25

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

-- note: fitType='parametric', but the dispersion trend was not well captured by the
   function: y = a/x + b, and a local regression fit was automatically substituted.
   specify fitType='local' or 'mean' to avoid this message next time.

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Naive CD4 Treg"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CD27+ effector B cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "cDC1"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ naive CD4 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Activated memory B cell"
[1] 33

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "Core naive CD4 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CM CD8 T cell"
[1] 35

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CMP cell"
[1] 31

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ISG+ MAIT"
[1] 34

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "ASDC"
[1] 34

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

[1] "CLP cell"
[1] 29

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

fitting model and testing

In [18]:
res_list <- mclapply(celltypes, function(celltype){
    print(celltype)
    celltype_list <- lapply(df_list, function(df) { df <- df[, grep(celltype, names(df), fixed = TRUE),drop=FALSE] })
    exp_matrix<-do.call(cbind,celltype_list)
    colnames(exp_matrix)<-gsub(".*:","",colnames(exp_matrix))
    #print(exp_matrix)

    meta_data_subset=meta_data %>% filter(sample.sampleKitGuid	 %in% colnames(exp_matrix),
                                       sample.visitName %in% c('Flu Year 2 Pre-Vac 7-12 Weeks',
                                                               'Flu Year 2 Day 90'))
    rownames(meta_data_subset)<-meta_data_subset$sample.sampleKitGuid
    
    exp_matrix <- exp_matrix[, rownames(meta_data_subset)] #subsetting exp_matrix so that column matches rownames(meta_data_subset)  
    # print(dim(exp_matrix))
    # print(dim(meta_data_subset))
    filtered_gene_set_filtered<-filtered_gene_set%>% filter(AIFI_L3==celltype)%>% select(gene) %>%pull()
    res=deseq2_analysis(exp_matrix,
                     meta_data=meta_data_subset,
                     filtered_gene_set=filtered_gene_set_filtered,
                     formula= ~ subject.subjectGuid+sample.visitName,   #+cmv_status+subject.biologicalSex,
                     comparisons=list(c('sample.visitName', "Flu Year 2 Day 90", "Flu Year 2 Pre-Vac 7-12 Weeks")),
                                      # c('cmv_status', 'Positive','Negative'),
                                      # c('subject.biologicalSex', 'Male','Female')),
                     celltype=celltype)
    return(res)
},mc.cores=60)

Warning message in mclapply(celltypes, function(celltype) {:
“scheduled cores 57, 56, 53, 52, 51, 50, 49, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 9, 1, 12, 59, 60, 15, 2, 7, 3, 11, 18, 16, 24, 17, 13, 14, 21, 27, 28, 31, 22, 5, 10, 4, 20, 30, 8, 26, 23, 19, 6, 25, 29 encountered errors in user code, all values of the jobs will be affected”

In [19]:
res_list

[[1]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[2]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[3]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[4]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[5]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[6]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[7]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[8]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[9]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[10]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[11]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[12]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[13]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[14]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[15]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[16]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[17]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[18]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[19]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[20]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[21]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[22]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[23]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[24]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[25]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[26]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[27]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[28]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[29]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[30]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[31]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[32]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[33]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[34]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[35]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[36]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[37]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[38]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[39]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[40]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[41]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[42]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[43]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[44]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[45]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[46]]
[1] "fatal error in wrapper code"
attr(,"class")
[1] "try-error"

[[47]]
         baseMean log2FoldChange      lfcSE          stat       pvalue
1       44.585697   1.549829e+00 0.18384917  8.4298915831 3.459856e-17
2       47.603230   9.094747e-01 0.14621668  6.2200474253 4.970046e-10
3      124.597419   8.395261e-01 0.15270716  5.4976212705 3.849486e-08
4       41.305765   7.244597e-01 0.13879647  5.2195834205 1.793260e-07
5      138.213596   5.654265e-01 0.11341656  4.9853967558 6.183479e-07
6       42.208423  -4.972164e-01 0.13662039 -3.6394015395 2.732724e-04
7      184.924939  -3.241651e-01 0.09141292 -3.5461627912 3.908847e-04
8       19.769252   7.827942e-01 0.22999544  3.4035206386 6.652339e-04
9      299.084181   2.205775e-01 0.06535330  3.3751548374 7.377417e-04
10     133.329013   2.838659e-01 0.08373490  3.3900543384 6.987877e-04
11      31.927663  -4.155689e-01 0.12799266 -3.2468180156 1.167030e-03
12     357.494809  -1.998865e-01 0.06154320 -3.2479051021 1.162580e-03
13      33.320541   4.288834e-01 0.13337396  3.2156456514 1.301514e-03
14      28.704180   4.103733e-01 0.12932987  3.1730745041 1.508338e-03
15     163.251285  -2.147718e-01 0.06978030 -3.0778287253 2.085147e-03
16      22.376889  -5.019165e-01 0.17001178 -2.9522455944 3.154719e-03
17      53.636733   3.110004e-01 0.10670826  2.9144920792 3.562678e-03
18     130.872370   4.795967e-01 0.16374830  2.9288649815 3.402022e-03
19     508.997276   2.234294e-01 0.07776098  2.8732847137 4.062278e-03
20     234.428856  -1.411493e-01 0.04998268 -2.8239634231 4.743380e-03
21      20.201073   4.845661e-01 0.17130120  2.8287371354 4.673207e-03
22     199.156859  -1.556597e-01 0.05615703 -2.7718652349 5.573611e-03
23     140.993157  -1.876553e-01 0.06782466 -2.7667716072 5.661440e-03
24      60.872150   2.858005e-01 0.10512055  2.7187878858 6.552161e-03
25     111.152749   2.270831e-01 0.08342506  2.7220014131 6.488787e-03
26     583.333213   1.902516e-01 0.06949352  2.7376877119 6.187280e-03
27     508.287057   2.359354e-01 0.08708096  2.7093795279 6.740918e-03
28      38.988284   2.994968e-01 0.11205758  2.6727049227 7.524240e-03
29      25.715091   3.546482e-01 0.13555606  2.6162471643 8.890218e-03
30      29.559615   3.505769e-01 0.13363754  2.6233412419 8.707201e-03
31      86.445951   2.102790e-01 0.08064914  2.6073311446 9.125106e-03
32      24.669350   3.731816e-01 0.14384283  2.5943707538 9.476424e-03
33     200.415431  -1.623461e-01 0.06225069 -2.6079411679 9.108861e-03
34      96.291887   2.662437e-01 0.10279743  2.5899837913 9.598045e-03
35     195.512391  -1.509825e-01 0.05868648 -2.5726958022 1.009099e-02
36     351.973294   1.511596e-01 0.05974154  2.5302262655 1.139890e-02
37    1017.160501   1.119208e-01 0.04427622  2.5277859391 1.147843e-02
38      19.121009   3.942569e-01 0.15741293  2.5046031679 1.225888e-02
39     845.408980   1.092255e-01 0.04460443  2.4487587200 1.433494e-02
40     415.773436   1.474810e-01 0.06006702  2.4552737158 1.407774e-02
41     895.943678   1.112143e-01 0.04599861  2.4177753554 1.561571e-02
42      91.662423  -1.886002e-01 0.07794393 -2.4196908738 1.553371e-02
43      21.374120   3.646989e-01 0.15167136  2.4045337889 1.619311e-02
44     643.159794   1.232466e-01 0.05220287  2.3609160505 1.822986e-02
45     173.472304   1.427582e-01 0.06018383  2.3720358035 1.769038e-02
46      29.702368  -2.995847e-01 0.12587663 -2.3799867263 1.731326e-02
47      21.080900  -3.667495e-01 0.15543679 -2.3594770241 1.830071e-02
48      21.702631  -3.887363e-01 0.16875635 -2.3035357178 2.124872e-02
49      32.083150   2.693371e-01 0.11702374  2.3015591814 2.136004e-02
50     199.478902   1.670456e-01 0.07166510  2.3309192704 1.975762e-02
51     144.751479  -1.372915e-01 0.05984778 -2.2940107683 2.178988e-02
52      21.021003   3.584451e-01 0.15506635  2.3115598379 2.080195e-02
53      17.288824   3.984143e-01 0.17404399  2.2891586585 2.207014e-02
54     602.889078   1.302043e-01 0.05631012  2.3122709632 2.076276e-02
55      41.422772   2.462102e-01 0.10930966  2.2524100404 2.429637e-02
56      26.596144  -3.250919e-01 0.14457274 -2.2486392370 2.453546e-02
57      39.317721   2.562750e-01 0.11304132  2.2670914062 2.338464e-02
58     110.144049   1.855039e-01 0.08162743  2.2725687709 2.305218e-02
59     588.607561   1.102848e-01 0.04900170  2.2506320747 2.440885e-02
60      83.789649   1.790455e-01 0.08054655  2.2228826444 2.622371e-02
61     111.550494   1.795422e-01 0.08077279  2.2228055346 2.622892e-02
62      47.075517   2.301789e-01 0.10692482  2.1527167660 3.134095e-02
63      43.811194  -2.242949e-01 0.10468685 -2.1425316317 3.215073e-02
64     216.237433   1.117561e-01 0.05180690  2.1571671354 3.099264e-02
65      89.075900  -2.400173e-01 0.11200018 -2.1430082839 3.211243e-02
66      24.844400  -4.071360e-01 0.18446895 -2.2070704759 2.730914e-02
67      28.977589   3.250118e-01 0.14972147  2.1707758978 2.994812e-02
68     173.227572   1.699837e-01 0.07721487  2.2014369395 2.770511e-02
69     312.970222  -1.079561e-01 0.05027711 -2.1472213268 3.177567e-02
70     542.839161   1.321361e-01 0.06101118  2.1657686086 3.032887e-02
71      48.504410   2.494403e-01 0.11540025  2.1615231126 3.065495e-02
72      24.339739  -3.731342e-01 0.17361145 -2.1492488487 3.161468e-02
73      94.551740  -1.689958e-01 0.07803335 -2.1656872656 3.033509e-02
74      27.232969  -2.926726e-01 0.13351220 -2.1921036482 2.837202e-02
75     125.448447   2.539096e-01 0.11899147  2.1338472440 3.285529e-02
76      18.815499   3.534537e-01 0.16674840  2.1196826181 3.403282e-02
77     119.485211  -1.764540e-01 0.08357900 -2.1112237254 3.475309e-02
78     138.115065  -1.322712e-01 0.06372810 -2.0755547604 3.793515e-02
79      50.895388  -2.043526e-01 0.09916757 -2.0606798055 3.933360e-02
80      36.766008   2.808822e-01 0.13598051  2.0656061495 3.886568e-02
81      89.921155  -1.595392e-01 0.07884421 -2.0234738340 4.302432e-02
82      46.224019   2.131150e-01 0.10579668  2.0143822556 4.396942e-02
83    1372.809720  -1.009059e-01 0.04964555 -2.0325261166 4.210042e-02
84      23.714724  -3.397977e-01 0.16782376 -2.0247297135 4.289513e-02
85      20.860774   3.345545e-01 0.16488046  2.0290729419 4.245086e-02
86     324.887086   1.395536e-01 0.06856808  2.0352558076 4.182514e-02
87      40.242662   2.582374e-01 0.12720448  2.0300968834 4.234669e-02
88     149.647146  -1.381409e-01 0.06842864 -2.0187591858 4.351226e-02
89      48.566324  -2.120760e-01 0.10556106 -2.0090366880 4.453324e-02
90     220.211795   1.758753e-01 0.08780447  2.0030339673 4.517364e-02
91      20.936218   3.458796e-01 0.17366857  1.9916074331 4.641415e-02
92      17.855485  -3.302903e-01 0.16634742 -1.9855448780 4.708388e-02
93      18.739894  -3.100923e-01 0.15615573 -1.9857890499 4.705675e-02
94     170.283696  -1.377443e-01 0.07015165 -1.9635217943 4.958557e-02
95      25.550210   3.040950e-01 0.15610968  1.9479571971 5.142008e-02
96      29.203580   2.459859e-01 0.12621978  1.9488700483 5.131095e-02
97      21.196258   3.023955e-01 0.15573602  1.9417185224 5.217119e-02
98      33.696126   2.453586e-01 0.12757600  1.9232343493 5.445063e-02
99     298.557135   9.191175e-02 0.04786837  1.9200934823 5.484609e-02
100    100.393080  -1.470319e-01 0.07664481 -1.9183540772 5.506613e-02
101     72.543710  -1.579605e-01 0.08264588 -1.9112934242 5.596688e-02
102    194.096718  -1.463884e-01 0.07697261 -1.9018245300 5.719410e-02
103    284.199677  -1.084083e-01 0.05691790 -1.9046426041 5.682654e-02
104     21.267572   2.758770e-01 0.14581515  1.8919635941 5.849583e-02
105     42.641572  -2.181961e-01 0.11555054 -1.8883175525 5.898333e-02
106    115.506173  -1.308349e-01 0.06951966 -1.8819846031 5.983811e-02
107     31.119385   3.670602e-01 0.19564898  1.8761161541 6.063933e-02
108    384.540258   8.604071e-02 0.04602222  1.8695472380 6.154672e-02
109     27.139426  -2.921539e-01 0.15732646 -1.8569912602 6.331240e-02
110     23.036720   2.664717e-01 0.14414177  1.8486781855 6.450430e-02
111     50.010504   2.096220e-01 0.11384448  1.8413008898 6.557748e-02
112     76.126730  -1.457853e-01 0.07940195 -1.8360420862 6.635143e-02
113    111.278806  -1.333639e-01 0.07259236 -1.8371620105 6.618598e-02
114     20.968746  -2.701796e-01 0.14850031 -1.8193875407 6.885233e-02
115     48.805511   1.779465e-01 0.09768861  1.8215682828 6.852052e-02
116     27.459187  -2.485165e-01 0.13634312 -1.8227285697 6.834451e-02
117    104.398531  -1.491386e-01 0.08244116 -1.8090313464 7.044613e-02
118     68.346558  -1.622286e-01 0.08996985 -1.8031438767 7.136562e-02
119     67.045919  -1.541316e-01 0.08568868 -1.7987397896 7.205985e-02
120     38.086622   2.037019e-01 0.11374741  1.7908268885 7.332108e-02
121     41.336244   2.597438e-01 0.14493112  1.7921878152 7.310289e-02
122     18.272737   2.890785e-01 0.16263700  1.7774462413 7.549485e-02
123   1355.850982   6.661007e-02 0.03748409  1.7770223273 7.556457e-02
124     41.018969  -2.008573e-01 0.11277324 -1.7810721600 7.490066e-02
125     53.575168  -1.792028e-01 0.10108865 -1.7727288251 7.627365e-02
126     94.739538   1.369363e-01 0.07754678  1.7658535870 7.742042e-02
127   1743.487935  -5.956936e-02 0.03382790 -1.7609538525 7.824621e-02
128    236.709330   1.156769e-01 0.06593652  1.7543677980 7.936751e-02
129     20.879052  -3.067341e-01 0.17473432 -1.7554313674 7.918555e-02
130     32.817351  -2.126379e-01 0.12048200 -1.7648931872 7.758172e-02
131     52.708145   2.331619e-01 0.13355682  1.7457879760 8.084780e-02
132     28.399738  -2.223493e-01 0.12720239 -1.7479960039 8.046472e-02
133    204.231095  -1.046887e-01 0.06071727 -1.7241996050 8.467182e-02
134     72.032375   1.637759e-01 0.09487730  1.7261860884 8.431394e-02
135    290.647358  -8.647307e-02 0.05126624 -1.6867447762 9.165244e-02
136     26.650130   2.491309e-01 0.14783988  1.6851400723 9.196155e-02
137     29.702090  -2.137781e-01 0.12693252 -1.6841870397 9.214553e-02
138     17.685890  -2.852402e-01 0.16817059 -1.6961360105 8.986013e-02
139     29.667555  -2.210199e-01 0.12949229 -1.7068189858 8.785570e-02
140     44.971692  -1.737106e-01 0.10141221 -1.7129158038 8.672803e-02
141    647.731480  -6.870458e-02 0.04053552 -1.6949226334 9.009010e-02
142     48.169849  -1.721701e-01 0.10180180 -1.6912289345 9.079309e-02
143     62.336753  -1.522657e-01 0.09048448 -1.6827828002 9.241715e-02
144   2352.441623  -5.609826e-02 0.03313792 -1.6928720198 9.047983e-02
145     38.010151  -1.902035e-01 0.11151052 -1.7056998342 8.806398e-02
146     35.107529  -2.026915e-01 0.12155172 -1.6675332009 9.540843e-02
147     31.065244   2.357742e-01 0.14215028  1.6586260721 9.719116e-02
148     29.870472  -2.056455e-01 0.12348744 -1.6653154869 9.584983e-02
149     42.841485   1.885572e-01 0.11350410  1.6612366322 9.666593e-02
150     31.198165  -2.366147e-01 0.14181367 -1.6684899953 9.521850e-02
151    115.017696   1.132940e-01 0.06808351  1.6640449098 9.610345e-02
152     20.933594   2.542337e-01 0.15415039  1.6492578815 9.909481e-02
153     47.382347  -1.722633e-01 0.10431972 -1.6513013461 9.867706e-02
154    565.230703  -6.678931e-02 0.04061175 -1.6445809549 1.000563e-01
155    124.692373  -1.079490e-01 0.06615559 -1.6317442300 1.027334e-01
156     25.179605   2.243067e-01 0.13708373  1.6362749207 1.017821e-01
157     29.094137   2.327282e-01 0.14216624  1.6370144500 1.016275e-01
158     49.455562  -2.121019e-01 0.13012958 -1.6299285794 1.031166e-01
159     20.471660   2.529425e-01 0.15533914  1.6283243587 1.034561e-01
160     54.533089   2.149667e-01 0.13278208  1.6189438778 1.054593e-01
161     50.339451   2.101448e-01 0.13011194  1.6151076691 1.062874e-01
162     55.591172  -1.483607e-01 0.09281596 -1.5984399218 1.099451e-01
163     21.068892  -2.435041e-01 0.15324598 -1.5889752477 1.120660e-01
164     21.591077  -2.317693e-01 0.14550796 -1.5928286591 1.111986e-01
165     23.008496  -2.337706e-01 0.14691918 -1.5911508761 1.115756e-01
166     34.727155   2.859731e-01 0.18033856  1.5857564919 1.127946e-01
167     22.685858  -2.287469e-01 0.14642055 -1.5622591781 1.182269e-01
168     52.060908  -1.556523e-01 0.09879052 -1.5755790306 1.151229e-01
169     42.836528   1.687850e-01 0.10702914  1.5770006410 1.147954e-01
170     25.522640   2.227194e-01 0.14150386  1.5739457534 1.155000e-01
171     27.793737  -2.118732e-01 0.13526006 -1.5664137644 1.172518e-01
172     25.425799  -2.073175e-01 0.13260036 -1.5634760103 1.179407e-01
173     53.158091  -1.516074e-01 0.09697018 -1.5634434100 1.179483e-01
174     59.456356   1.369016e-01 0.08783572  1.5586093849 1.190889e-01
175     20.965887   2.380340e-01 0.15367506  1.5489438391 1.213952e-01
176     21.222824   2.294432e-01 0.14858760  1.5441608217 1.225494e-01
177     23.212728  -2.259533e-01 0.14633815 -1.5440493952 1.225764e-01
178     28.822996  -1.992468e-01 0.12889201 -1.5458430945 1.221425e-01
179     25.066605   2.162657e-01 0.14450907  1.4965543735 1.345092e-01
180    105.088589  -1.092090e-01 0.07275320 -1.5010890899 1.333325e-01
181     31.971039  -1.993848e-01 0.13032327 -1.5299245760 1.260354e-01
182     45.116631   1.727132e-01 0.11424357  1.5117980020 1.305853e-01
183     64.801365   2.931822e-01 0.19252115  1.5228569055 1.277945e-01
184     26.772023   2.123232e-01 0.14185766  1.4967342476 1.344624e-01
185    352.811515   8.561099e-02 0.05678846  1.5075419543 1.316718e-01
186     98.106728  -1.272883e-01 0.08323522 -1.5292601227 1.262000e-01
187     18.380973   2.495823e-01 0.16637242  1.5001421086 1.335776e-01
188     44.582679  -1.646635e-01 0.10868311 -1.5150794311 1.297523e-01
189     29.424227  -1.970317e-01 0.12892249 -1.5282959676 1.264391e-01
190    335.595336   8.396329e-02 0.05565739  1.5085739768 1.314077e-01
191     23.675086  -2.191374e-01 0.14587250 -1.5022531894 1.330317e-01
192     22.832483   2.301308e-01 0.15115857  1.5224462999 1.278973e-01
193     30.083283   1.902264e-01 0.12576201  1.5125904079 1.303837e-01
194    279.277776   1.302366e-01 0.08483913  1.5351012214 1.247590e-01
195     21.210989  -2.299979e-01 0.15591431 -1.4751561470 1.401706e-01
196     37.617506  -1.790601e-01 0.12150931 -1.4736330729 1.405804e-01
197     69.253187  -1.326647e-01 0.08947359 -1.4827249894 1.381475e-01
198    118.159857  -1.056622e-01 0.07152522 -1.4772720449 1.396027e-01
199    118.554238   1.006896e-01 0.06832809  1.4736197166 1.405840e-01
200     17.965359   2.562171e-01 0.17212757  1.4885301919 1.366111e-01
201     22.034340   2.627007e-01 0.17684846  1.4854568072 1.374229e-01
202     25.474095  -2.039013e-01 0.13785009 -1.4791524546 1.390996e-01
203    407.500820  -7.132581e-02 0.04847658 -1.4713458831 1.411976e-01
204     67.708639  -1.441515e-01 0.10241714 -1.4074939014 1.592810e-01
205     25.604925  -2.086398e-01 0.14348349 -1.4541032885 1.459177e-01
206     20.128548  -2.350977e-01 0.16523149 -1.4228381863 1.547831e-01
207     27.324193   1.907248e-01 0.13072815  1.4589422727 1.445810e-01
208     31.989476  -1.749833e-01 0.12474160 -1.4027661998 1.606866e-01
209     29.467472   1.964740e-01 0.13803640  1.4233489577 1.546350e-01
210     66.309620  -1.420077e-01 0.09671769 -1.4682700397 1.420309e-01
211     27.318469  -2.229468e-01 0.15430894 -1.4448077895 1.485119e-01
212     24.222277  -2.249599e-01 0.15701528 -1.4327260272 1.519361e-01
213     65.811433  -1.842380e-01 0.13001831 -1.4170155417 1.564784e-01
214     36.884689   1.911474e-01 0.13133893  1.4553753654 1.455654e-01
215     18.440851  -2.329675e-01 0.16089065 -1.4479863934 1.476209e-01
216     26.444481  -1.931336e-01 0.13762409 -1.4033418163 1.605149e-01
217     20.871168   2.240310e-01 0.15516873  1.4437895129 1.487982e-01
218     23.445249  -2.072001e-01 0.14330502 -1.4458674845 1.482144e-01
219     62.610328   1.395000e-01 0.09771749  1.4275844168 1.534115e-01
220    311.546113   7.737806e-02 0.05418426  1.4280540098 1.532763e-01
221     47.035453  -1.575205e-01 0.11186453 -1.4081359106 1.590908e-01
222     26.134880  -1.960680e-01 0.13611444 -1.4404645456 1.497360e-01
223    148.832923   9.183145e-02 0.06450283  1.4236808537 1.545389e-01
224     21.348134  -2.119533e-01 0.14480117 -1.4637542764 1.432611e-01
225     22.269202   2.001999e-01 0.14098948  1.4199634012 1.556183e-01
226     23.721398   2.050951e-01 0.14272240  1.4370207760 1.507121e-01
227     22.699549   2.190751e-01 0.15446618  1.4182725743 1.561112e-01
228     58.237098  -1.310097e-01 0.09296915 -1.4091735979 1.587838e-01
229     19.451131   3.170224e-01 0.22379199  1.4165942552 1.566016e-01
230     22.595204  -2.316069e-01 0.16490783 -1.4044627368 1.601811e-01
231     68.883868  -1.497948e-01 0.10473205 -1.4302673527 1.526403e-01
232     23.549339  -2.016773e-01 0.14720860 -1.3700105015 1.706836e-01
233     20.373000   2.175550e-01 0.15876007  1.3703384464 1.705813e-01

In [21]:
res_all<-do.call(rbind,res_list)

In [25]:
res_all

       baseMean   log2FoldChange lfcSE      stat          pvalue      padj
1       3.298319   0.107949275   0.44477867  0.24270335   0.80823521  0.9986237
2       3.657115  -0.125371511   0.40205015 -0.31183052   0.75516932  0.9986237
3      26.286094  -0.071188685   0.17063776 -0.41719186   0.67653808  0.9986237
4      21.335181   0.267740850   0.17457115  1.53370613   0.12510196  0.9986237
5       3.529923  -0.212888857   0.37938235 -0.56114591   0.57469807  0.9986237
6       2.715087   0.329381690   0.47014452  0.70059668   0.48355475  0.9986237
7       1.626662   0.539080172   0.63053026  0.85496320   0.39257152  0.9986237
8       5.371769  -0.287098333   0.32736883 -0.87698739   0.38049349  0.9986237
9       1.806097  -0.316148121   0.61783345 -0.51170444   0.60885788  0.9986237
10      5.135964   0.089489415   0.34897861  0.25643238   0.79761699  0.9986237
11      5.332485   0.111546913   0.32416697  0.34410327   0.73076863  0.9986237
12      1.782299   0.631475288   0.59082109  1.06880966   0.28515544  0.9986237
13      1.466202   0.169513369   0.61336487  0.27636628   0.78226675  0.9986237
14      3.501403  -0.512506087   0.40316572 -1.27120452   0.20365590  0.9986237
15      2.411878  -0.880908704   0.52809966 -1.66807286   0.09530126  0.9986237
16      4.286129   0.246169964   0.35125980  0.70082021   0.48341522  0.9986237
17      2.596041  -0.099213987   0.47901080 -0.20712265   0.83591407  0.9986237
18      1.429156   0.628759172   0.69716649  0.90187807   0.36712164  0.9986237
19     87.193033  -0.136038856   0.09342744 -1.45609094   0.14536748  0.9986237
20      3.435560   0.008381308   0.45387544  0.01846610   0.98526702  0.9986237
21      1.937533  -0.366949329   0.56216323 -0.65274516   0.51392058  0.9986237
22      8.633011  -0.157115534   0.25465991 -0.61696219   0.53725966  0.9986237
23      9.462153  -0.289158594   0.25963940 -1.11369306   0.26541089  0.9986237
24      1.739726  -0.798744002   0.66150911 -1.20745730   0.22725608  0.9986237
25      1.826267   0.319069637   0.59460991  0.53660329   0.59154167  0.9986237
26      1.707310   0.171689411   0.59838883  0.28691948   0.77417398  0.9986237
27      1.465101  -0.070634169   0.67052442 -0.10534168   0.91610469  0.9986237
28      3.464553   0.009293346   0.42202531  0.02202083   0.98243134  0.9986237
29      2.786861  -0.275242804   0.49406345 -0.55710012   0.57745903  0.9986237
30      1.734437  -0.086049150   0.56450115 -0.15243397   0.87884467  0.9986237
⋮      ⋮          ⋮              ⋮          ⋮             ⋮           ⋮
352609  4.5755045  5.783440e-01  0.4972200   1.163155e+00 0.244766571 0.9999578
352610  1.1835133 -2.443974e-01  0.8409760  -2.906116e-01 0.771348409 0.9999578
352611  0.6617910 -2.832398e-01  2.1092347  -1.342856e-01 0.893176755 0.9999578
352612  0.8571203 -2.361316e-01  1.1850362  -1.992611e-01 0.842058540 0.9999578
352613  1.4865807  2.498168e-01  0.8042811   3.106088e-01 0.756098013 0.9999578
352614  1.4514367 -2.432058e-01  0.7510869  -3.238052e-01 0.746085539 0.9999578
352615  1.5412977  4.040974e-01  0.8002611   5.049570e-01 0.613589038 0.9999578
352616  2.3169737  3.403512e-01  0.6591310   5.163635e-01 0.605600547 0.9999578
352617  1.0222879  9.302683e-01  1.0790386   8.621270e-01 0.388617644 0.9999578
352618  0.8253452  9.053400e-01  1.0626714   8.519472e-01 0.394243382 0.9999578
352619  0.6741701 -6.319981e-01  2.0376634  -3.101582e-01 0.756440645 0.9999578
352620  0.7014802 -1.018961e+00  1.3626850  -7.477596e-01 0.454605145 0.9999578
352621  0.6975472  1.218542e+00  1.6911124   7.205565e-01 0.471182443 0.9999578
352622  0.6738455 -3.847391e-01  1.2484584  -3.081713e-01 0.757951960 0.9999578
352623  4.6918586  2.231930e-01  0.4336529   5.146813e-01 0.606775766 0.9999578
352624 26.4946919  6.222233e-01  0.3822979   1.627588e+00 0.103612330 0.9999578
352625 29.8668566  4.627619e-01  0.3233821   1.431006e+00 0.152428365 0.9999578
352626 93.7049839  3.232507e-01  0.1982378   1.630621e+00 0.102970371 0.9999578
352627 68.8881690  4.086639e-01  0.2369583   1.724624e+00 0.084595316 0.9999578
352628  1.3443136  9.822131e-01  0.8823473   1.113182e+00 0.265630272 0.9999578
352629 54.5784985  2.610027e-01  0.3128385   8.343050e-01 0.404109130 0.9999578
352630 67.4721361  2.104969e-01  0.2343072   8.983801e-01 0.368982920 0.9999578
352631 44.5026970  2.743814e-01  0.3502485   7.833907e-01 0.433397742 0.9999578
352632  7.1339742  1.103356e+00  0.3675596   3.001843e+00 0.002683508 0.9999578
352633 40.1125804  3.819936e-01  0.2673866   1.428619e+00 0.153113745 0.9999578
352634 18.2530877  4.111920e-01  0.2709579   1.517549e+00 0.129128027 0.9999578
352635  0.9527140  1.355828e+00  1.4956905   9.064894e-01 0.364676877 0.9999578
352636 57.3573081  2.641123e-01  0.2156600   1.224669e+00 0.220699790 0.9999578
352637  0.6119078 -9.106850e-01  2.1120680  -4.311817e-01 0.666336278 0.9999578
352638  0.3306743  7.874705e-05  3.5418768   2.223314e-05 0.999982261 0.9999823
       contrast         Direction                 gene       celltype
1      sample.visitName HigherInFlu Year 2 Day 90 ISG15      ILC
2      sample.visitName HigherInFlu Year 2 Day 7  TTLL10     ILC
3      sample.visitName HigherInFlu Year 2 Day 7  TNFRSF18   ILC
4      sample.visitName HigherInFlu Year 2 Day 90 TNFRSF4    ILC
5      sample.visitName HigherInFlu Year 2 Day 7  SDF4       ILC
6      sample.visitName HigherInFlu Year 2 Day 90 UBE2J2     ILC
7      sample.visitName HigherInFlu Year 2 Day 90 INTS11     ILC
8      sample.visitName HigherInFlu Year 2 Day 7  AURKAIP1   ILC
9      sample.visitName HigherInFlu Year 2 Day 7  CCNL2      ILC
10     sample.visitName HigherInFlu Year 2 Day 90 MRPL20     ILC
11     sample.visitName HigherInFlu Year 2 Day 90 SSU72      ILC
12     sample.visitName HigherInFlu Year 2 Day 90 CDK11B     ILC
13     sample.visitName HigherInFlu Year 2 Day 90 CDK11A     ILC
14     sample.visitName HigherInFlu Year 2 Day 7  GNB1       ILC
15     sample.visitName HigherInFlu Year 2 Day 7  FAAP20     ILC
16     sample.visitName HigherInFlu Year 2 Day 90 RER1       ILC
17     sample.visitName HigherInFlu Year 2 Day 7  TNFRSF14   ILC
18     sample.visitName HigherInFlu Year 2 Day 90 TPRG1L     ILC
19     sample.visitName HigherInFlu Year 2 Day 7  RPL22      ILC
20     sample.visitName HigherInFlu Year 2 Day 90 TNFRSF25   ILC
21     sample.visitName HigherInFlu Year 2 Day 7  CAMTA1     ILC
22     sample.visitName HigherInFlu Year 2 Day 7  PARK7      ILC
23     sample.visitName HigherInFlu Year 2 Day 7  ENO1       ILC
24     sample.visitName HigherInFlu Year 2 Day 7  PIK3CD     ILC
25     sample.visitName HigherInFlu Year 2 Day 90 CTNNBIP1   ILC
26     sample.visitName HigherInFlu Year 2 Day 90 LZIC       ILC
27     sample.visitName HigherInFlu Year 2 Day 7  SRM        ILC
28     sample.visitName HigherInFlu Year 2 Day 90 PRDM2      ILC
29     sample.visitName HigherInFlu Year 2 Day 7  EFHD2      ILC
30     sample.visitName HigherInFlu Year 2 Day 7  SPEN       ILC
⋮      ⋮                ⋮                         ⋮          ⋮
352609 sample.visitName HigherInFlu Year 2 Day 90 CSTB       CLP cell
352610 sample.visitName HigherInFlu Year 2 Day 7  TRAPPC10   CLP cell
352611 sample.visitName HigherInFlu Year 2 Day 7  PFKL       CLP cell
352612 sample.visitName HigherInFlu Year 2 Day 7  C21orf2    CLP cell
352613 sample.visitName HigherInFlu Year 2 Day 90 UBE2G2     CLP cell
352614 sample.visitName HigherInFlu Year 2 Day 7  SUMO3      CLP cell
352615 sample.visitName HigherInFlu Year 2 Day 90 PTTG1IP    CLP cell
352616 sample.visitName HigherInFlu Year 2 Day 90 ITGB2      CLP cell
352617 sample.visitName HigherInFlu Year 2 Day 90 FAM207A    CLP cell
352618 sample.visitName HigherInFlu Year 2 Day 90 SPATC1L    CLP cell
352619 sample.visitName HigherInFlu Year 2 Day 7  MCM3AP     CLP cell
352620 sample.visitName HigherInFlu Year 2 Day 7  YBEY       CLP cell
352621 sample.visitName HigherInFlu Year 2 Day 90 PCNT       CLP cell
352622 sample.visitName HigherInFlu Year 2 Day 7  DIP2A      CLP cell
352623 sample.visitName HigherInFlu Year 2 Day 90 PRMT2      CLP cell
352624 sample.visitName HigherInFlu Year 2 Day 90 MT-ND1     CLP cell
352625 sample.visitName HigherInFlu Year 2 Day 90 MT-ND2     CLP cell
352626 sample.visitName HigherInFlu Year 2 Day 90 MT-CO1     CLP cell
352627 sample.visitName HigherInFlu Year 2 Day 90 MT-CO2     CLP cell
352628 sample.visitName HigherInFlu Year 2 Day 90 MT-ATP8    CLP cell
352629 sample.visitName HigherInFlu Year 2 Day 90 MT-ATP6    CLP cell
352630 sample.visitName HigherInFlu Year 2 Day 90 MT-CO3     CLP cell
352631 sample.visitName HigherInFlu Year 2 Day 90 MT-ND3     CLP cell
352632 sample.visitName HigherInFlu Year 2 Day 90 MT-ND4L    CLP cell
352633 sample.visitName HigherInFlu Year 2 Day 90 MT-ND4     CLP cell
352634 sample.visitName HigherInFlu Year 2 Day 90 MT-ND5     CLP cell
352635 sample.visitName HigherInFlu Year 2 Day 90 MT-ND6     CLP cell
352636 sample.visitName HigherInFlu Year 2 Day 90 MT-CYB     CLP cell
352637 sample.visitName HigherInFlu Year 2 Day 7  AL592183.1 CLP cell
352638 sample.visitName HigherInFlu Year 2 Day 90 CLPTM1     CLP cell

In [22]:
#write.csv(res_all, 'BR2_deseq_y2_d7_d0_subj_clean.csv')
write.csv(res_all, 'UP1_deseq_Y2D90D0.csv')